import {useState,useRef,useEffect} from 'react';
import type {createControlledIdentityClient,ControlledPrincipal} from './controlled-identity-api.js';
const labels={ACCESS:'查阅资料',EXPORT:'申请导出',CORRECTION:'申请更正',CLOSURE:'申请注销',WITHDRAWAL:'申请撤回'} as const;
type Right={id:string;kind:keyof typeof labels;acceptedAt:string;state:string;referenceRequestId:string|null;caseOwner:string|null;actionsApplied:false};
export function FormalRightsInbox({client,identity,onSessionLost}:{client:ReturnType<typeof createControlledIdentityClient>;identity:ControlledPrincipal;onSessionLost:()=>void}):JSX.Element{
 const [rows,setRows]=useState<Right[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const mounted=useRef(true),pending=useRef(false);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function load(next?:string){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const result=await client.business<{requests:Right[];nextCursor:string|null}>('/api/v11/ops/formal/rights'+(next?'?cursor='+encodeURIComponent(next):''));if(!Array.isArray(result.requests)||result.requests.some(r=>!r||!Object.hasOwn(labels,r.kind)||r.actionsApplied!==false))throw Error('资料权利记录不完整');if(mounted.current&&client.current()?.id===identity.id){setRows(old=>next?[...old,...result.requests.filter(r=>!old.some(x=>x.id===r.id))]:result.requests);setCursor(result.nextCursor);}}catch(e){if(mounted.current){setError(e instanceof Error?e.message:'读取未完成');if(!client.current())onSessionLost();}}finally{if(mounted.current){pending.current=false;setBusy(false);}}}
 return <section aria-label="正式资料权利待办"><h3>资料与账号权利待办</h3><button disabled={busy} onClick={()=>void load()}>读取资料权利待办</button>{cursor&&<button disabled={busy} onClick={()=>void load(cursor)}>下一页资料权利待办</button>}<p>这里只读受理记录与责任人，尚未执行导出、更正、注销或撤销资金；内部工作队列期限不是业务承诺。</p>{rows.map(r=><article key={r.id}><p>{labels[r.kind]}；请求 {r.id}；原受理 {r.acceptedAt}；{r.state}；责任人 {r.caseOwner??'待核对'}</p>{r.referenceRequestId&&<p>关联本人请求 {r.referenceRequestId}</p>}</article>)}{error&&<p role="alert">{error}</p>}</section>;
}
