import { useEffect, useRef, useState } from "react";
import { fundingLabel, type PrelaunchPolicy } from "@timeleft-shanghai/shared/prelaunch-client";
import { prelaunchClient as api } from "./prelaunch-api.js";
import "./app.css";
import { shanghaiInputToIso } from "./prelaunch-time.js";

type Row = { id: string; state?: string; status?: string; kind?: string; activityId?: string; registrationId?: string; F?: number; D?: number; serviceFeeCents?: number; depositCents?: number; blockerIds?: string[]; allowedActions?: string[]; ordinal?: string; revision?: number; snapshot?: Record<string,unknown>; minSize?:number;targetSize?:number;maxSize?:number;maxTables?:number;capacity?:number;strategy?:string;waitlistMax?:number|null };
type Values = Record<string, string>;
interface Field { name: string; label: string; type?: "number" | "datetime-local" | "password"; optional?: boolean; }
const freshKey = () => `ops-ui-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
function number(values: Values, name: string) { const raw = values[name]?.trim(); if (!raw || !/^\d+$/.test(raw)) throw Error("请填写明确的非负整数测试参数"); const value = Number(raw); if (!Number.isSafeInteger(value)) throw Error("测试参数超出范围"); return value; }
function text(values: Values, name: string) { const value = values[name]?.trim(); if (!value) throw Error("请填写所有必填项"); return value; }
function iso(values: Values, name: string) { return shanghaiInputToIso(text(values, name)); }

export function PrelaunchWorkspace(): JSX.Element {
  const [session, setSession] = useState(api.session()); const [actorId, setActorId] = useState(""); const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false); const simulationPolicy = useRef(false); const pending = useRef(false); const generation = useRef(0);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [policy, setPolicy] = useState<PrelaunchPolicy | null>(null);
  const [supplies, setSupplies] = useState<Row[]>([]); const [registrations, setRegistrations] = useState<Row[]>([]); const [requests, setRequests] = useState<Row[]>([]);
  const [jobs, setJobs] = useState<Row[]>([]); const [cases, setCases] = useState<Row[]>([]); const [summary, setSummary] = useState<Record<string, unknown>>({});
  const [rights, setRights] = useState<Row[]>([]); const [changes, setChanges] = useState<Row[]>([]); const [decisionReason, setDecisionReason] = useState("");
  const [queue, setQueue] = useState<Row[]>([]); const [history, setHistory] = useState<Row[]>([]);const [revisionFees,setRevisionFees]=useState<Array<{label:string;amountCents:number}>>([]);const [revisionDefaults,setRevisionDefaults] = useState<Values>({});const [funding,setFunding]=useState<Record<string,Record<string,number>>>({});
  const [timeDemand,setTimeDemand]=useState<{scope:string;profileCount:number;emptyPreferenceCount:number;unrecognizedPreferenceProfileCount:number;slots:Array<{code:string;label:string;count:number}>}|null>(null);
  const [partialErrors, setPartialErrors] = useState<string[]>([]);
  const [restaurantId, setRestaurantId] = useState(""); const [activityId, setActivityId] = useState(""); const [supplyId, setSupplyId] = useState("");
  const role = session?.actor.role;
  useEffect(() => { void reload(); return () => { generation.current++; }; }, []);
  async function act(operation: () => Promise<void>) {
    if (pending.current) return; const before = generation.current; pending.current = true; setBusy(true); setError(""); setNotice("");
    try { await operation(); } catch (cause) { if (before === generation.current) setError(cause instanceof Error ? cause.message : "操作未完成，请刷新查看进度"); }
    finally { if (!api.session()) { setRegistrations([]); setRequests([]); setJobs([]); setCases([]); setSummary({}); setTimeDemand(null); setSupplies([]); setRights([]); setChanges([]); } pending.current = false; if (before === generation.current) { setBusy(false); setSession(api.session()); } }
  }
  async function reload() {
    const before = generation.current; const current = api.session();
    const results = await Promise.allSettled([
      api.call<PrelaunchPolicy>("GET", simulationPolicy.current ? "/policy/current?scope=SIMULATION_ONLY" : "/policy/current", undefined, false),
      ...(current?.actor.role === "RESTAURANT" ? [api.list<Row>("/restaurant/supplies", "supplies").then(rows => ({supplies:rows})), api.list<Row>("/restaurant/registrations", "registrations").then(rows => ({registrations:rows}))] : current && ["OPS", "REVIEWER"].includes(current.actor.role) ? [api.list<Row>("/ops/supplies", "supplies").then(rows => ({supplies:rows})), api.list<Row>("/ops/registrations", "registrations").then(rows => ({registrations:rows})), api.list<Row>("/ops/requests", "requests").then(rows => ({requests:rows})), api.list<Row>("/ops/jobs", "jobs").then(rows => ({jobs:rows})), api.list<Row>("/ops/financial-cases", "cases").then(rows => ({cases:rows})), api.call<{ summary: Record<string, unknown> }>("GET", "/ops/summary"), api.list<Row>("/ops/rights", "rights").then(rights=>({rights})), api.list<Row>("/ops/changes", "changes").then(changes=>({changes})),api.call<{components:Record<string,Record<string,number>>}>("GET","/ops/funding-summary"),api.call<{demand:NonNullable<typeof timeDemand>}>("GET","/ops/time-demand")] : []),
    ]);
    if (before !== generation.current) return; setSession(api.session());
    const errors: string[] = [];
    const names = ["政策", "供给", "报名", "申请", "任务", "资金待办", "统计", "隐私申请", "变更", "资金组件", "开局时间需求"];
    results.forEach((r, index) => { if (r.status === "rejected") errors.push(`${names[index]}：${r.reason instanceof Error ? r.reason.message : "暂时不可用"}`); });
    const p = results[0]; if (p?.status === "fulfilled") setPolicy(p.value as PrelaunchPolicy);
    const s = results[1]; if (s?.status === "fulfilled") setSupplies((s.value as { supplies: Row[] }).supplies);
    const r = results[2]; if (r?.status === "fulfilled") setRegistrations((r.value as { registrations: Row[] }).registrations);
    const q = results[3]; if (q?.status === "fulfilled") setRequests((q.value as { requests: Row[] }).requests);
    const j = results[4]; if (j?.status === "fulfilled") setJobs((j.value as { jobs: Row[] }).jobs);
    const c = results[5]; if (c?.status === "fulfilled") setCases((c.value as { cases: Row[] }).cases);
    const t = results[6]; if (t?.status === "fulfilled") setSummary((t.value as { summary: Record<string, unknown> }).summary);
    if (results[7]?.status === "fulfilled") setRights((results[7].value as {rights:Row[]}).rights);
    if (results[8]?.status === "fulfilled") setChanges((results[8].value as {changes:Row[]}).changes);
    if(results[10]?.status==="fulfilled")setTimeDemand((results[10].value as {demand:NonNullable<typeof timeDemand>}).demand);
    if(results[9]?.status==="fulfilled")setFunding((results[9].value as {components:Record<string,Record<string,number>>}).components);
    setPartialErrors(errors);
  }
  async function action(path: string, body: unknown, message: string) { await api.call("POST", path, body); setNotice(message); await reload(); }
  function logout() { generation.current++; api.logout(); setSession(null); setPolicy(null); setSupplies([]); setRegistrations([]); setRequests([]); setJobs([]); setCases([]); setSummary({}); setTimeDemand(null); setPassword(""); setRights([]); setChanges([]); }
  return <main className="ops-shell prelaunch-workspace">
    <header className="section-header"><div><h1>饭局 · 本地验收工作区</h1><p>仅使用合成账号、测试供给和模拟资金。政策仍为草案，真实收费与正式启用保持关闭。</p></div></header>
    {error ? <p role="alert" className="ops-alert">{error}</p> : null}{notice ? <p role="status">{notice}</p> : null}
    {!session ? <form onSubmit={e => { e.preventDefault(); void act(async () => { const result = await api.login(actorId.trim(), password); setPassword(""); setSession(result); await reload(); }); }}><label>受控测试账号<input aria-label="受控测试账号" value={actorId} onChange={e => setActorId(e.target.value)} autoComplete="username" /></label><label>测试密码<input aria-label="测试密码" type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" /></label><button disabled={busy || !actorId || !password}>登录</button></form> : <div><p>当前账号 {session.actor.id} · {role}</p><button onClick={logout}>退出登录</button><button disabled={busy} onClick={() => void act(reload)}>刷新工作区</button></div>}
    {partialErrors.length ? <aside aria-label="局部加载提示">{partialErrors.map(item => <p key={item}>{item}</p>)}</aside> : null}
    <section><h2>政策预览</h2><button disabled={busy || !session} onClick={()=>void act(async()=>{simulationPolicy.current=true;await reload();})}>读取已有独立合成政策</button>{policy ? <><p>{policy.bundleVersion} · {policy.status} · {policy.activation}</p><p>同一摘要仅证明完整性。合成测试确认不能代替正式法务、财务或餐厅签收。</p>{policy.documents.map(d => <details key={d.documentId}><summary>{d.documentId} / {d.version}</summary><p style={{ whiteSpace: "pre-wrap" }}>{d.publicText}</p></details>)}{role === "OPS" ? <button disabled={busy} onClick={() => void act(async () => { await api.call("POST", "/ops/simulation-policy", {sourcePolicyId:policy.policyId}); simulationPolicy.current=true;setNotice("独立测试政策快照已建立；正式政策未启用");await reload();})}>建立独立合成测试快照</button> : null}</> : <p>尚无可读取的政策快照。</p>}</section>
    {role === "OPS" ? <>
      <section><h2>1. 创建测试餐厅</h2><Form title="绑定餐厅测试人员" busy={busy} fields={[{name:"actorId",label:"已有餐厅测试账号 ID"},{name:"restaurantId",label:"授权餐厅 ID"}]} defaults={{restaurantId}} onSubmit={v=>act(()=>action(`/ops/actors/${encodeURIComponent(text(v,"actorId"))}/restaurant`, {restaurantId:text(v,"restaurantId")}, "已绑定现有餐厅人员到本场餐厅；未授予新角色"))}/><Form title="餐厅" busy={busy} fields={[{ name: "name", label: "名称" }, { name: "district", label: "区域" }, { name: "businessArea", label: "商圈" }, { name: "address", label: "合成地址" }, { name: "capacity", label: "总容量", type: "number" }, { name: "budgetCents", label: "预计餐费（分）", type: "number" }]} onSubmit={v => act(async () => { const row = await api.call<{ id: string }>("POST", "/ops/restaurants", { name: text(v, "name"), district: text(v, "district"), businessArea: text(v, "businessArea"), address: text(v, "address"), capacity: number(v, "capacity"), budgetCents: number(v, "budgetCents") }); setRestaurantId(row.id); setNotice(`测试餐厅已创建：${row.id}`); })} /></section>
      <section><h2>2. 创建测试活动</h2><p>餐厅 {restaurantId || "尚未创建或选择"}</p><Form title="活动" busy={busy} fields={[{ name: "restaurantId", label: "餐厅 ID" }, { name: "title", label: "活动名称" }, { name: "startsAt", label: "开始时间（上海时区）", type: "datetime-local" }, { name: "endsAt", label: "结束时间", type: "datetime-local" }, { name: "registrationEndsAt", label: "报名截止时间", type: "datetime-local" }]} defaults={{ restaurantId }} onSubmit={v => act(async () => { const row = await api.call<{ id: string }>("POST", "/ops/activities", { restaurantId: text(v, "restaurantId"), title: text(v, "title"), startsAt: iso(v, "startsAt"), endsAt: iso(v, "endsAt"), registrationEndsAt: iso(v, "registrationEndsAt") }); setActivityId(row.id); setNotice(`测试活动已创建：${row.id}`); })} /></section>
      <section><h2>3. 供给修订与明确报价</h2><p>F、D、候补上限及范围均需填写明确的 TEST_ONLY 参数；这里不会补正式默认金额。</p><Form title="供给" busy={busy} fields={[{ name: "activityId", label: "活动 ID" }, { name: "policyId", label: "测试政策 ID" }, { name: "min", label: "最低成团人数", type: "number" }, { name: "target", label: "偏好人数", type: "number" }, { name: "max", label: "每桌上限", type: "number" }, { name: "maxTables", label: "最大桌数", type: "number" }, { name: "capacity", label: "确认总容量", type: "number" }, { name: "F", label: "服务费 F（分）", type: "number" }, { name: "D", label: "保证金 D（分）", type: "number" }, { name: "WAITLIST_MAX", label: "测试候补上限（留空保留未定）", type: "number", optional: true }, { name: "strategy", label: "策略：FILL_TO_TARGET 或 FILL_TO_MAX" }, { name: "estimatedMealMinCents", label: "预计餐费下限（分）", type: "number" }, { name: "estimatedMealMaxCents", label: "预计餐费上限（分）", type: "number" }, { name: "fixedFeeLabel", label: "固定餐厅费用名称（可选）", optional: true }, { name: "fixedFeeCents", label: "固定餐厅费用（分，可选）", type: "number", optional: true }]} defaults={{ activityId, policyId: policy?.policyId ?? "", min: "4", target: "6", max: "8" }} onSubmit={v => act(async () => { const row = await api.call<{ id: string }>("POST", "/ops/supplies", { activityId: text(v, "activityId"), policyId: text(v, "policyId"), min: number(v, "min"), target: number(v, "target"), max: number(v, "max"), maxTables: number(v, "maxTables"), capacity: number(v, "capacity"), F: number(v, "F"), D: number(v, "D"), WAITLIST_MAX: v.WAITLIST_MAX?.trim() ? number(v, "WAITLIST_MAX") : null, strategy: text(v, "strategy"), estimatedMealMinCents: number(v, "estimatedMealMinCents"), estimatedMealMaxCents: number(v, "estimatedMealMaxCents"), fixedFees: v.fixedFeeLabel?.trim() ? [{ label: text(v, "fixedFeeLabel"), amountCents: number(v, "fixedFeeCents") }] : [] }); setSupplyId(row.id); setNotice(`供给草案已创建：${row.id}，等待餐厅测试账号独立确认`); await reload(); })} /></section>
      <section><h2>4. 审批与发布</h2><p>供给必须先由本场餐厅账号确认。运营不能代签。</p><Form title="供给审批" busy={busy} fields={[{ name: "supplyId", label: "供给 ID" }, { name: "D_MIN", label: "TEST_ONLY D_MIN（分）", type: "number" }, { name: "D_MAX", label: "TEST_ONLY D_MAX（分）", type: "number" }, { name: "simulationBatchHour", label: "测试次日批次小时（0—23）", type: "number" }]} defaults={{ supplyId }} onSubmit={v => act(() => action(`/ops/supplies/${encodeURIComponent(text(v, "supplyId"))}/approve`, { D_MIN: number(v, "D_MIN"), D_MAX: number(v, "D_MAX"), simulationBatchHour: number(v, "simulationBatchHour") }, "测试审批已记录，正式金额范围仍未确认"))} /><label>待发布活动 ID<input value={activityId} onChange={e => setActivityId(e.target.value)} /></label><button disabled={busy || !activityId} onClick={() => void act(() => action(`/ops/activities/${encodeURIComponent(activityId)}/publish`, {}, "测试活动已发布"))}>发布测试活动</button></section>
    </> : null}
    <section><h2>供给与餐厅确认</h2>{supplies.map(s => <article className="ops-ticket" key={s.id}><p>{s.id} · {s.status ?? s.state}</p>{Number.isInteger(s.F ?? s.serviceFeeCents) && Number.isInteger(s.D ?? s.depositCents) ? <p>{fundingLabel((s.F ?? s.serviceFeeCents)!, (s.D ?? s.depositCents)!)}</p> : null}<button disabled={busy} onClick={() => { setSupplyId(s.id); if (s.activityId) setActivityId(s.activityId); }}>选择此供给</button>{role === "RESTAURANT" ? <button disabled={busy} onClick={() => void act(() => action(`/restaurant/supplies/${encodeURIComponent(s.id)}/confirm`, {}, "本场测试确认已记录"))}>餐厅确认本场修订</button> : null}</article>)}</section>
    <section><h2>报名与履约</h2>{registrations.map(r => <article className="ops-ticket" key={r.id}><p>{r.id} · {r.state ?? r.status}</p>{role === "RESTAURANT" ? <><button disabled={busy} onClick={() => void act(() => action(`/restaurant/registrations/${encodeURIComponent(r.id)}/fulfillment`, { result: "NORMAL" }, "正常履约事实已提交，资金处置由独立任务处理"))}>确认正常履约</button><button disabled={busy} onClick={() => void act(() => action(`/restaurant/registrations/${encodeURIComponent(r.id)}/fulfillment`, { result: "ABNORMAL" }, "异常事实已提交，不会直接扣保证金"))}>提交履约异常</button></> : null}</article>)}</section>
    {role && ["OPS", "REVIEWER"].includes(role) ? <><section><h2>全库统计</h2><p>以下来自服务端完整聚合，不由当前列表页计数。平台业务保留不等于会计收入。</p><dl>{Object.entries(summary).filter(([, value]) => typeof value === "number" || typeof value === "string").map(([name, value]) => <div key={name}><dt>{name}</dt><dd>{String(value)}</dd></div>)}</dl></section><section><h2>申请与异人复核</h2><label>审核理由（合成事实）<input value={decisionReason} maxLength={500} onChange={e=>setDecisionReason(e.target.value)}/></label>{requests.map(r => <article className="ops-ticket" key={r.id}><p>{r.id} · {r.kind} · {r.state} · {r.blockerIds?.join("、")}</p>{([['REFUND_D', '正常退D'], ['REFUND_FD', '特殊情形全退F+D'], ['BREACH', '违约结论（结算仍受门禁）'], ['REJECT', '拒绝特殊申请并执行原规则']] as const).map(([decision, label]) => <button key={label} disabled={busy || !decisionReason.trim() || !r.allowedActions?.includes(decision)} onClick={() => void act(() => action(`/ops/requests/${encodeURIComponent(r.id)}/decision`, {decision, reason:decisionReason.trim()}, "测试审核决定已记录；实际异人及不利效果的专项门禁仍保留"))}>{label}</button>)}</article>)}</section><section><h2>持久任务与资金待办</h2>{jobs.map(j => <p key={j.id}>{j.id} · {j.kind} · {j.state}</p>)}{cases.map(c => <p key={c.id}>{c.id} · {c.kind} · {c.state}</p>)}</section></> : null}
    {role === "OPS" ? <section><h2>活动取消与恢复查询</h2><p>取消申请保留原受理时刻；未定政策效果会登记待办，不抹除资金事实。</p><Form title="取消活动" busy={busy} fields={[{name:"activityId", label:"活动 ID"}]} defaults={{activityId}} onSubmit={v => act(() => action(`/ops/activities/${encodeURIComponent(text(v,"activityId"))}/cancel`, {businessKey:freshKey()}, "活动取消申请已记录，请查看退款待办"))}/><Form title="资金查询" busy={busy} fields={[{name:"registrationId", label:"报名 ID"}]} onSubmit={v => act(() => action(`/ops/registrations/${encodeURIComponent(text(v,"registrationId"))}/query`, {}, "已安排模拟渠道恢复查询，请刷新资金状态"))}/></section> : null}
    {role === "RESTAURANT" ? <section><h2>本场合成签到码</h2><Form title="签到码" busy={busy} fields={[{name:"activityId",label:"授权活动 ID"}]} onSubmit={v => act(async () => {const code = await api.call<{qrToken:string}>("POST", `/restaurant/activities/${encodeURIComponent(text(v,"activityId"))}/checkin-code`, {}); setNotice(`合成签到码：${code.qrToken}。仅本场使用，不代表确认正常履约。`);})}/></section> : null}
    {role === "OPS" ? <section><h2>安排变更与权利处理</h2><Form title="核心变更" busy={busy} fields={[{name:"activityId",label:"活动 ID"},{name:"supplyId",label:"供给 ID"},{name:"kind",label:"类型 RESTAURANT 或 OTHER_CORE"},{name:"restaurantId",label:"提案餐厅 ID"},{name:"startsAt",label:"提案上海开始时间",type:"datetime-local"},{name:"deadlineAt",label:"合成确认截止（未定可留空）",type:"datetime-local",optional:true},{name:"extraCompensationCents",label:"明确的合成额外补偿（分，可选）",type:"number",optional:true}]} defaults={{activityId,supplyId}} onSubmit={v=>act(()=>action("/ops/changes", {activityId:text(v,"activityId"),supplyId:text(v,"supplyId"),kind:text(v,"kind"),proposedSnapshot:{restaurantId:text(v,"restaurantId"),startsAt:iso(v,"startsAt")},businessKey:freshKey(),...(v.deadlineAt?.trim()?{deadlineAt:iso(v,"deadlineAt")}:{}),...(v.extraCompensationCents?.trim()?{extraCompensationCents:number(v,"extraCompensationCents")}: {})}, "变更提案已保存；逐人同意与原资金事实分别保留"))}/>{changes.map(c=><p key={c.id}>变更 {c.id} · {c.kind} · {c.state}</p>)}{rights.map(q=><article key={q.id}><p>{q.id} · {q.kind} · {q.state} · {q.blockerIds?.join("、")}</p><button disabled={busy} onClick={()=>void act(()=>action(`/ops/rights/${encodeURIComponent(q.id)}/process`, {}, "权利处理已执行或登记具体阻塞；本人可查询进度"))}>处理本人权利请求</button></article>)}</section>:null}
    {role && ["OPS","REVIEWER"].includes(role) ? <section><h2>候补与资金组件</h2><Form title="候补队列" busy={busy} fields={[{name:"activityId",label:"活动 ID"}]} defaults={{activityId}} onSubmit={v=>act(async()=>{const rows=await api.list<Row>(`/ops/activities/${encodeURIComponent(text(v,"activityId"))}/waitlist`,"queue");setQueue(rows);})}/><p>当前排序是合成事务序号；正式排序时钟仍 OP-05，不能作为实际批准。</p>{queue.map(q=><p key={q.id}>{q.id} · 序号 {q.ordinal} · {q.state}</p>)}{Object.entries(funding).map(([component,buckets])=><article key={component}><h3>{component}（分）</h3>{Object.entries(buckets).filter(([,v])=>typeof v==="number").map(([bucket,amount])=><p key={bucket}>{bucket}：{amount}</p>)}</article>)}<p>组件互斥资金桶来自服务端全库聚合；平台业务保留不等于会计收入。</p>{role==="OPS"?<button disabled={busy} onClick={()=>void act(()=>action("/ops/reconciliation",{},"渠道双向对账已执行；缺失账单保留UNKNOWN待办"))}>执行本地持久渠道对账</button>:null}{cases.map(c=><article key={c.id}><p>{c.id} · {c.kind} · {c.state}</p><button disabled={busy || !c.allowedActions?.includes("CLAIM")} onClick={()=>void act(()=>action(`/ops/financial-cases/${encodeURIComponent(c.id)}/claim`,{},"资金待办已认领"))}>认领资金待办</button><button disabled={busy || !c.allowedActions?.includes("RESOLVE") || !decisionReason.trim()} onClick={()=>void act(()=>action(`/ops/financial-cases/${encodeURIComponent(c.id)}/resolve`,{reason:decisionReason.trim()},"已依据独立渠道事实核查；请查看结果"))}>核查并处理资金待办</button></article>)}</section>:null}
    {role && ["OPS","REVIEWER","RESTAURANT"].includes(role) ? <section><h2>不可变供给修订与历史</h2><Form title="供给历史" busy={busy} fields={[{name:"supplyId",label:"供给 ID"}]} defaults={{supplyId}} onSubmit={v=>act(async()=>{const id=text(v,"supplyId");setSupplyId(id);const prefix=role==="RESTAURANT"?"restaurant":"ops";const [detail,rows]=await Promise.all([api.call<{supply:Row}>("GET",`/${prefix}/supplies/${encodeURIComponent(id)}`),api.list<Row>(`/${prefix}/supplies/${encodeURIComponent(id)}/history`,"history")]);setHistory(rows);const values:Values={};for(const [key,val]of Object.entries(detail.supply.snapshot??{}))if(typeof val==="number" || typeof val==="string")values[key]=String(val);const fees=detail.supply.snapshot?.fixedFees;const priorFees=Array.isArray(fees)?fees as Array<{label:string;amountCents:number}>:[];setRevisionFees(priorFees);if(priorFees[0]){values.fixedFeeLabel=priorFees[0].label;values.fixedFeeCents=String(priorFees[0].amountCents);}setRevisionDefaults(values);})}/>{history.map(h=><p key={h.id}>{h.id} · 修订 {h.revision} · {h.status} · F {h.serviceFeeCents} · D {h.depositCents}</p>)}{role==="OPS"?<><p>新修订只创建DRAFT，保留旧订单快照；签收、审批与既有报名的核心变更分别处理。</p><p>原固定收费逐项保留：{revisionFees.map(f=>`${f.label} ¥${(f.amountCents/100).toFixed(2)}`).join("；") || "无"}。下方仅编辑第一项；其余已确认收费保留，删除第一项请明确清空名称。</p><Form title="新供给修订" busy={busy} fields={[{name:"min",label:"最低人数",type:"number"},{name:"target",label:"偏好人数",type:"number"},{name:"max",label:"每桌上限",type:"number"},{name:"maxTables",label:"最大桌数",type:"number"},{name:"capacity",label:"总容量",type:"number"},{name:"F",label:"F（分）",type:"number"},{name:"D",label:"D（分）",type:"number"},{name:"WAITLIST_MAX",label:"测试候补上限",type:"number",optional:true},{name:"strategy",label:"FILL_TO_TARGET 或 FILL_TO_MAX"},{name:"estimatedMealMinCents",label:"餐费下限（分）",type:"number"},{name:"estimatedMealMaxCents",label:"餐费上限（分）",type:"number"},{name:"fixedFeeLabel",label:"固定费名称（可选）",optional:true},{name:"fixedFeeCents",label:"固定费（分）",type:"number",optional:true}]} defaults={revisionDefaults} onSubmit={v=>act(async()=>{if(!supplyId)throw Error("请先读取旧供给");const next=await api.call<{supply:Row}>("POST",`/ops/supplies/${encodeURIComponent(supplyId)}/revision`,{min:number(v,"min"),target:number(v,"target"),max:number(v,"max"),maxTables:number(v,"maxTables"),capacity:number(v,"capacity"),F:number(v,"F"),D:number(v,"D"),WAITLIST_MAX:v.WAITLIST_MAX?.trim()?number(v,"WAITLIST_MAX"):null,strategy:text(v,"strategy"),estimatedMealMinCents:number(v,"estimatedMealMinCents"),estimatedMealMaxCents:number(v,"estimatedMealMaxCents"),fixedFees:[...(v.fixedFeeLabel?.trim()?[{label:text(v,"fixedFeeLabel"),amountCents:number(v,"fixedFeeCents")}]:[]),...revisionFees.slice(1)]});setSupplyId(next.supply.id);setNotice("新草案已创建，原订单未变；请餐厅独立签收并走核心变更治理");await reload();})}/></>:null}</section>:null}
    {role && ["OPS","REVIEWER"].includes(role) && timeDemand ? <section><h2>合成开局时间需求</h2><p>仅内部匿名聚合；选填偏好不作为报名、付款或排桌条件。上海时间，午餐11:00—15:00、晚餐17:00—22:00（结束时刻不计入）。</p><p>资料数 {timeDemand.profileCount}；空偏好 {timeDemand.emptyPreferenceCount}；旧/未识别时段资料 {timeDemand.unrecognizedPreferenceProfileCount}</p>{timeDemand.slots.map(slot=><p key={slot.code}>{slot.label}：{slot.count}</p>)}<p>每份资料每个时段最多计一次，多选可计入多个时段；不展示账号、手机号或个人资料。</p></section>:null}
    {role === "USER" ? <p>该账号为用户角色，请使用小程序查看本人报名。</p> : null}
  </main>;
}
function Form({ title, fields, defaults = {}, busy, onSubmit }: { title: string; fields: Field[]; defaults?: Values; busy: boolean; onSubmit: (values: Values) => Promise<void> }): JSX.Element {
  const [values, setValues] = useState<Values>(defaults);
  useEffect(() => { setValues(previous => ({ ...previous, ...Object.fromEntries(Object.entries(defaults).filter(([, value]) => value !== "")) })); }, [JSON.stringify(defaults)]);
  return <form aria-label={title} onSubmit={event => { event.preventDefault(); void onSubmit(values); }}><div className="prelaunch-fields">{fields.map(f => <label key={f.name}>{f.label}<input aria-label={`${title} ${f.label}`} type={f.type ?? "text"} value={values[f.name] ?? ""} required={!f.optional} min={f.type === "number" ? 0 : undefined} step={f.type === "number" ? 1 : undefined} onChange={event => setValues(previous => ({ ...previous, [f.name]: event.target.value }))} /></label>)}</div><button disabled={busy} type="submit">{busy ? "处理中…" : `提交${title}`}</button></form>;
}
