import {useEffect,useRef,useState} from 'react';
import {View,Text,Button,Input} from '@tarojs/components';
import {useDidShow,useDidHide,navigateTo} from '@tarojs/taro';
import {listFormalRights,submitFormalRight,formalRightLabels,type FormalRightKind,type FormalRightRequest} from './formal-rights-api';
export function FormalRights():JSX.Element{
 const [rows,setRows]=useState<FormalRightRequest[]>([]),[cursor,setCursor]=useState<string|null>(null),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const epoch=useRef(0),pending=useRef(false);
 useEffect(()=>()=>{epoch.current++;},[]);useDidShow(()=>{epoch.current++;pending.current=false;setRows([]);setCursor(null);setReference('');setMessage('');setError('');void run(()=>load());});useDidHide(()=>{epoch.current++;setRows([]);setCursor(null);setReference('');setMessage('');setError('');});
 async function run(action:()=>Promise<void>){if(pending.current)return;pending.current=true;const generation=epoch.current;setBusy(true);setError('');setMessage('');try{await action();}catch(e){if(generation===epoch.current)setError(e instanceof Error?e.message:'请求未完成');}finally{if(generation===epoch.current){pending.current=false;setBusy(false);}}}
 async function load(next?:string){const generation=epoch.current,data=await listFormalRights(next);if(generation===epoch.current){setRows(old=>next?[...old,...data.requests.filter(row=>!old.some(x=>x.id===row.id))]:data.requests);setCursor(data.nextCursor);}}
 async function submit(kind:FormalRightKind){const generation=epoch.current,value=reference.trim();if(value&&!/^[A-Za-z0-9_.:-]{1,160}$/.test(value))throw Error('仅填写本人已有请求编号，不填写个人资料');const row=await submitFormalRight(kind,value||undefined);if(generation===epoch.current)setMessage(formalRightLabels[kind]+'请求已受理，原受理时间：'+row.acceptedAt+'。待人工处理，尚未执行资料或账号变更。');await load();}
 return <View className="page"><Text className="title">资料与账号权利请求</Text><Text>此入口保存请求与原受理时间，不立即导出、修改资料、注销账号或撤销资金。历史收退款与未结义务继续保留。</Text><Text>仅提交请求类型及本人已有请求编号；请勿输入证明附件或敏感个人资料。</Text><Input value={reference} maxlength={160} placeholder="关联本人已有请求编号（可选）" onInput={e=>setReference(e.detail.value)}/>{(Object.keys(formalRightLabels) as FormalRightKind[]).map(kind=><Button key={kind} disabled={busy} onClick={()=>void run(()=>submit(kind))}>{formalRightLabels[kind]}</Button>)}<Button disabled={busy} onClick={()=>void run(()=>load())}>刷新权利请求</Button>{cursor&&<Button disabled={busy} onClick={()=>void run(()=>load(cursor))}>下一页权利请求</Button>}{rows.map(row=><View key={row.id}><Text>{formalRightLabels[row.kind]}；请求编号：{row.id}；原受理：{row.acceptedAt}；待人工处理</Text>{row.referenceRequestId&&<Text>关联请求：{row.referenceRequestId}</Text>}<Text>尚未执行资料或账号变更；未结资金义务不会因此消失。</Text></View>)}{message&&<Text>{message}</Text>}{error&&<Text className="error-text">{error}</Text>}<Button onClick={()=>navigateTo({url:'/pages/order-list/index'})}>查看历史报名与资金进度</Button></View>;
}
