import {useState,useRef,useEffect} from 'react';
import {View,Text,Button} from '@tarojs/components';
import {formalRequest} from './api';
type Snapshot={startsAt:string;endsAt:string;F:number;D:number;min:number;target:number;max:number;maxTables:number;restaurantName:string|null;district:string;businessArea:string};
type Change={id:string;pendingReview:boolean;reviewRequestId:string|null;originalChangeAcceptedAt:string;reviewAcceptedAt:string|null;canAccept:boolean;restaurantChanged:boolean;original:Snapshot;proposed:Snapshot;choice:'ACCEPT'|'REJECT'|null;responseAt:string|null;applied:false;deadline:null;silenceAccepted:false};
export function FormalCoreChanges({registrationId}:{registrationId:string}):JSX.Element{
 const [rows,setRows]=useState<Change[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const generation=useRef(0),pending=useRef(false);
 useEffect(()=>{generation.current++;setRows([]);setMessage('');return()=>{generation.current++;};},[registrationId]);
 async function load(){const result=await formalRequest<{changes:Change[]}>('/api/v11/formal/registrations/'+encodeURIComponent(registrationId)+'/core-changes');if(!Array.isArray(result.changes)||result.changes.some(r=>r.applied!==false||r.deadline!==null||r.silenceAccepted!==false||typeof r.canAccept!=='boolean'||![r.original,r.proposed].every(s=>s&&(s.restaurantName===null||typeof s.restaurantName==='string'&&s.restaurantName.length>0)&&typeof s.district==='string'&&typeof s.businessArea==='string')))throw Error('变更记录尚无法核实');return result.changes;}
 async function run(action:()=>Promise<string>){if(pending.current)return;pending.current=true;const epoch=generation.current;setBusy(true);try{const text=await action();const next=await load();if(epoch===generation.current){setRows(next);setMessage(text);}}catch(e){if(epoch===generation.current)setMessage(e instanceof Error?e.message:'变更请求未完成');}finally{pending.current=false;if(epoch===generation.current)setBusy(false);}}
 async function respond(id:string,choice:'ACCEPT'|'REJECT'){const result=await formalRequest<{choice:string;membershipEnded:boolean;pendingReview?:boolean;applied:boolean;newMoneySubmitted:boolean}>('/api/v11/formal/core-changes/'+encodeURIComponent(id)+'/choices',{method:'POST',data:{registrationId,choice}});if(result.pendingReview===true&&choice==='REJECT'&&result.membershipEnded===false&&result.applied===false&&result.newMoneySubmitted===false)return '拒绝意向已受理；已有正常履约事实，进入人工权益核查，尚未退出、释放席位或建立全额退款义务。原服务费留存及保证金退款进度保持独立。';if(result.choice!==choice||result.applied!==false||result.newMoneySubmitted!==false||result.membershipEnded!==(choice==='REJECT'))throw Error('答复结果尚无法核实');return choice==='ACCEPT'?'已记录本人同意意向，等待后续处理；原活动及费用尚未变更。':'已记录本人拒绝并结束成员资格、释放席位；按原 F+D 保存退款义务，核定、原渠道执行与到账独立。';}
 return <View><Text>核心事项变更</Text><Text>仅已核验供给与专门签收的正式变更可答复；不设默认答复期限，不以沉默视为同意。</Text><Button disabled={busy} onClick={()=>void run(async()=>'变更记录已读取')}>读取核心变更</Button>{rows.map(r=><View key={r.id}><Text>原餐厅：{r.original.restaurantName??'尚未按成团规则披露'}；{r.original.district} · {r.original.businessArea}</Text><Text>拟议餐厅：{r.proposed.restaurantName??'尚未按成团规则披露'}；{r.proposed.district} · {r.proposed.businessArea}</Text><Text>详细地址与联系方式不在变更入口披露。</Text><Text>原时间：{r.original.startsAt}；原 F/D：{r.original.F}/{r.original.D} 分</Text><Text>拟议时间：{r.proposed.startsAt}；拟议 F/D：{r.proposed.F}/{r.proposed.D} 分</Text><Text>同意只记录意向，尚未应用变更或产生新增收费。</Text>{r.pendingReview?<Text>拒绝意向待人工权益核查；请求：{r.reviewRequestId}；本次受理：{r.reviewAcceptedAt}；原变更提出：{r.originalChangeAcceptedAt}。尚未退出或建立全额退款义务。</Text>:r.choice?<Text>本人答复：{r.choice==='ACCEPT'?'同意意向':'拒绝'}；受理：{r.responseAt}</Text>:<><Button disabled={busy||!r.canAccept} onClick={()=>void run(()=>respond(r.id,'ACCEPT'))}>记录本人同意意向</Button>{!r.canAccept&&<Text>拟议餐厅尚不可披露，不能记录同意；可拒绝或通过咨询入口申请人工处理。</Text>}<Button disabled={busy} onClick={()=>void run(()=>respond(r.id,'REJECT'))}>拒绝变更并退出</Button></>}</View>)}{message&&<Text>{message}</Text>}</View>;
}
