import {beforeEach,describe,it,expect,vi} from 'vitest';
const mock=vi.hoisted(()=>({storage:new Map<string,string>(),request:vi.fn()}));
vi.mock('@tarojs/taro',()=>({default:{getStorageSync:(key:string)=>mock.storage.get(key),setStorageSync:(key:string,value:string)=>mock.storage.set(key,value),removeStorageSync:(key:string)=>mock.storage.delete(key),request:mock.request}}));
beforeEach(()=>{vi.resetModules();vi.clearAllMocks();mock.storage.clear();mock.storage.set('fanju_session_v2','current');vi.stubGlobal('__FANJU_API_BASE_URL__','https://api.example.invalid');vi.stubGlobal('__FANJU_DEMO_MODE__',false);});
const capability={statusCode:200,data:{version:'v11-identity-1',identityEnabled:true}};
const principal={id:'actor',userId:'user',personId:'person',role:'USER',version:1,restaurantId:null};
describe('formal V1.1 account initialization client',()=>{
 it('initializes only using current WeChat token and projects user fields without caching credentials',async()=>{mock.request.mockResolvedValueOnce(capability).mockResolvedValueOnce({statusCode:200,data:{version:'v11-identity-1',principal:{...principal,passwordHash:'must-not-propagate'}}});const api=await import('./api');expect(await api.initializeAvailableV11Identity('current')).toEqual({id:'actor',userId:'user',personId:'person',role:'USER',version:1});expect(mock.request.mock.calls[1]![0]).toMatchObject({method:'POST',data:{},header:{authorization:'Bearer current'}});expect(mock.storage.size).toBe(1);});
 it('does not mutate when server explicitly disables V1.1 identity',async()=>{mock.request.mockResolvedValue({statusCode:200,data:{version:'v11-identity-1',identityEnabled:false}});const api=await import('./api');expect(await api.initializeAvailableV11Identity('current')).toBeNull();expect(mock.request).toHaveBeenCalledOnce();});
 it('rejects an obsolete token before making a request',async()=>{const api=await import('./api');await expect(api.initializeAvailableV11Identity('old')).rejects.toThrow('登录状态已改变');expect(mock.request).not.toHaveBeenCalled();});
 it('stops initialization when account changes during capability discovery',async()=>{let finish!:(x:unknown)=>void;mock.request.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));const api=await import('./api');const pending=api.initializeAvailableV11Identity('current');mock.storage.set('fanju_session_v2','new');finish(capability);await expect(pending).rejects.toThrow('登录状态已改变');expect(mock.request).toHaveBeenCalledOnce();});
 it('does not accept late successful initialization after account change',async()=>{let finish!:(x:unknown)=>void;mock.request.mockResolvedValueOnce(capability).mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));const api=await import('./api');const pending=api.initializeAvailableV11Identity('current');await vi.waitFor(()=>expect(mock.request).toHaveBeenCalledTimes(2));mock.storage.set('fanju_session_v2','new');finish({statusCode:200,data:{version:'v11-identity-1',principal}});await expect(pending).rejects.toThrow('登录状态已改变');expect(mock.storage.get('fanju_session_v2')).toBe('new');});
 it('retains a newer session on an older initialization 401',async()=>{mock.request.mockResolvedValueOnce(capability).mockImplementationOnce(async()=>{mock.storage.set('fanju_session_v2','new');return{statusCode:401,data:{}};});const api=await import('./api');await expect(api.initializeAvailableV11Identity('current')).rejects.toThrow('登录已失效');expect(mock.storage.get('fanju_session_v2')).toBe('new');});
 it('rejects backend errors without simulating account creation or replaying',async()=>{mock.request.mockResolvedValueOnce(capability).mockResolvedValueOnce({statusCode:503,data:{error:'unavailable'}});const api=await import('./api');await expect(api.initializeAvailableV11Identity('current')).rejects.toThrow('unavailable');expect(mock.request).toHaveBeenCalledTimes(2);expect(mock.storage.size).toBe(1);});
 it.each([{role:'OPS'},{userId:''},{restaurantId:'foreign'},{version:-1}])('rejects incompatible user identity %j',async change=>{mock.request.mockResolvedValueOnce(capability).mockResolvedValueOnce({statusCode:200,data:{version:'v11-identity-1',principal:{...principal,...change}}});const api=await import('./api');await expect(api.initializeAvailableV11Identity('current')).rejects.toThrow('账号初始化失败');});
 it('refuses missing capability contract without mutation',async()=>{mock.request.mockResolvedValue({statusCode:200,data:{}});const api=await import('./api');await expect(api.initializeAvailableV11Identity('current')).rejects.toThrow('账号服务暂不可用');expect(mock.request).toHaveBeenCalledOnce();});
});
