import { createHash, createPublicKey, verify } from "node:crypto";
import { readFileSync, realpathSync, lstatSync } from "node:fs";
import { isAbsolute, relative, resolve } from "node:path";
import { z } from "zod";
import type { ProviderEnv } from "../providers.js";
import { bindingFor } from "./intents.js";
import type { LegacyAuthorization } from "./original-recovery.js";

const digest = z.string().regex(/^[a-f0-9]{64}$/);
const schema = z.object({ scope: z.enum(["FORMAL_LEGACY_RECOVERY", "TEST_ONLY"]), releaseVersion: z.string().min(1),
  expiresAt: z.string().datetime(), owner: z.string().min(1), reviewer: z.string().min(1), approvalReference: z.string().min(1),
  target: z.object({ reference: z.string().min(1), host: z.string().min(1), port: z.number().int().positive(),
    database: z.string().min(1), user: z.string().min(1), systemIdentifier: z.string().regex(/^\d+$/).optional() }).strict(),
  configuration: z.object({ envPath: z.string().min(1), envSha256: digest, merchantScope: digest, providerConfigId: z.string().min(1),
    credentials: z.array(z.object({ path: z.string().min(1), sha256: digest }).strict()).default([]) }).strict(),
  grants: z.array(z.object({ kind: z.enum(["PAYMENT", "REFUND"]), id: z.string().min(1), amountCents: z.number().int().positive(),
    actions: z.array(z.enum(["QUERY", "SEND"])).min(1) }).strict()).min(1),
}).strict();
const hash = (raw: Buffer) => createHash("sha256").update(raw).digest("hex");
// Signed external approval is a trust input, not an approval generated by the worker.
export function loadOriginalRecoveryAuthority(env: ProviderEnv, repoRoot: string) {
  function external(path: string | undefined, secret = true, limit = 1_048_576) {
    if (!path || !isAbsolute(path)) throw Error("Explicit external recovery authority path required");
    const actual = realpathSync(path), rel = relative(realpathSync(repoRoot), actual);
    if (actual !== resolve(path)) throw Error("Recovery external symlink paths forbidden");
    if (rel === "" || (!rel.startsWith("..") && !isAbsolute(rel))) throw Error("Recovery authority and credentials must be outside repository");
    const stat = lstatSync(path);
    if (!stat.isFile() || stat.isSymbolicLink() || stat.size > limit || stat.uid !== process.getuid?.()
      || (secret && (stat.mode & 0o077) !== 0)) throw Error("Recovery external file permissions or size invalid");
    return readFileSync(actual);
  }
  function read() {
    const raw = external(env.LEGACY_RECOVERY_MANIFEST_PATH);
    if (!/^[a-f0-9]{64}$/.test(env.LEGACY_RECOVERY_MANIFEST_SHA256 ?? "") || hash(raw) !== env.LEGACY_RECOVERY_MANIFEST_SHA256)
      throw Error("Pinned recovery manifest integrity invalid");
    const publicKey = external(env.LEGACY_RECOVERY_APPROVAL_PUBLIC_KEY_PATH, false, 16_384);
    if (!/^[a-f0-9]{64}$/.test(env.LEGACY_RECOVERY_APPROVAL_PUBLIC_KEY_SHA256 ?? "")
      || hash(publicKey) !== env.LEGACY_RECOVERY_APPROVAL_PUBLIC_KEY_SHA256) throw Error("Pinned recovery approval key invalid");
    const key = createPublicKey(publicKey);
    if (key.asymmetricKeyType !== "ed25519" || !verify(null, raw, key, external(env.LEGACY_RECOVERY_SIGNATURE_PATH, true, 1024)))
      throw Error("Independent recovery approval signature invalid");
    const manifest = schema.parse(JSON.parse(raw.toString("utf8")));
    const production = env.NODE_ENV === "production" && env.APP_ENV === "production";
    const test = env.NODE_ENV === "test" && env.APP_ENV === "ci";
    if ((!production && !test) || manifest.scope !== (production ? "FORMAL_LEGACY_RECOVERY" : "TEST_ONLY")
      || manifest.releaseVersion !== env.RELEASE_VERSION || Date.parse(manifest.expiresAt) <= Date.now()
      || manifest.owner === manifest.reviewer || manifest.approvalReference.startsWith("SIMULATION")) throw Error("Recovery approval scope invalid");
    if (new Set(manifest.grants.map(g => `${g.kind}:${g.id}`)).size !== manifest.grants.length
      || manifest.grants.some(g => g.kind === "PAYMENT" && g.actions.includes("SEND"))) throw Error("Recovery grant ambiguity or new payment forbidden");
    const configRaw = external(manifest.configuration.envPath, true, 65_536);
    if (hash(configRaw) !== manifest.configuration.envSha256) throw Error("Original recovery configuration integrity invalid");
    const config: ProviderEnv = {};
    for (const line of configRaw.toString("utf8").split(/\r?\n/)) {
      if (!line.trim() || line.trim().startsWith("#")) continue;
      const match = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line);
      if (!match || !match[1]!.startsWith("WECHAT_") || config[match[1]!] !== undefined) throw Error("Original recovery configuration syntax invalid");
      let value = match[2]!.trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1,-1);
      config[match[1]!] = value;
    }
    const binding = bindingFor(config, "wechat");
    if (binding.merchantScope !== manifest.configuration.merchantScope || binding.providerConfigId !== manifest.configuration.providerConfigId)
      throw Error("Original recovery manifest binding conflict");
    for (const name of ["WECHAT_PAY_PRIVATE_KEY_PATH", "WECHAT_PAY_PLATFORM_CERT_PATH"]) {
      const path = config[name];
      if (!path && !production) continue;
      const credential = manifest.configuration.credentials.find(c => c.path === path);
      if (!credential || hash(external(path, true, 65_536)) !== credential.sha256) throw Error("Original recovery credential reference or integrity invalid");
    }
    return { manifest, config, binding };
  }
  const loaded = read();
  const authorize: LegacyAuthorization = async (kind, row, action) => {
    const current = read(); // Revocation/config drift is checked again before every I/O.
    const grant = current.manifest.grants.find(g => g.kind === kind && g.id === row.id);
    if (!grant || grant.amountCents !== row.amountCents || !grant.actions.includes(action)
      || row.channel !== current.binding.channel || row.merchantScope !== current.binding.merchantScope
      || row.providerConfigId !== current.binding.providerConfigId) throw Error("Original recovery action outside signed grant");
  };
  const readCredential = (path: string) => {
    const current = read();
    const credential = current.manifest.configuration.credentials.find(c => c.path === path);
    const raw = external(path, true, 65_536);
    if (!credential || hash(raw) !== credential.sha256) throw Error("Original recovery credential unavailable");
    return raw.toString("utf8");
  };
  return { ...loaded, authorize, readCredential };
}
