// @vitest-environment jsdom
import React from '../../apps/ops/node_modules/react/index.js';
import {createRoot,type Root} from '../../apps/ops/node_modules/react-dom/client.js';
import {act} from '../../apps/ops/node_modules/react-dom/test-utils.js';
import {it,expect,vi} from 'vitest';
const bridge=vi.hoisted(()=>({storage:new Map<string,unknown>(),paths:[] as string[],params:{id:process.env.FORMAL_ACTIVITY_ID!} as Record<string,string>,navigation:'',corrupt:'',origin:process.env.FORMAL_ORIGIN!}));
vi.mock('../../apps/miniapp/node_modules/@tarojs/taro/index.js',async()=>{const r=await import('../../apps/ops/node_modules/react/index.js');const navigateTo=async({url}:{url:string})=>{bridge.navigation=url;};return{default:{getCurrentInstance:()=>({router:{params:bridge.params}}),getStorageSync:(k:string)=>bridge.storage.get(k),setStorageSync:(k:string,v:unknown)=>bridge.storage.set(k,v),requestPayment:async()=>{},request:async(x:{url:string;method:string;header:Record<string,string>;data?:unknown})=>{const path=new URL(x.url).pathname+new URL(x.url).search;bridge.paths.push(path);const res=await fetch(bridge.origin+path,{method:x.method,headers:x.header,...(x.data===undefined?{}:{body:JSON.stringify(x.data)})});const data=await res.json();if(bridge.corrupt==='policy'&&path.endsWith('/delivery'))data.documents=[];if(bridge.corrupt==='record'&&data.registration)data.registration.total=-1;if(bridge.corrupt==='list'&&Array.isArray(data.activities))data.unavailableCount=1;return{statusCode:res.status,data};}},navigateTo,useRouter:()=>({params:bridge.params}),useDidShow:(f:()=>void)=>r.useEffect(f,[]),useDidHide:()=>{}};});
vi.mock('../../apps/miniapp/node_modules/@tarojs/components/dist/index.js',async()=>{const r=await import('../../apps/ops/node_modules/react/index.js');const wrap=(tag:string)=>(p:Record<string,unknown>)=>r.createElement(tag,p,p.children as React.ReactNode);return{View:wrap('div'),ScrollView:wrap('div'),Text:wrap('span'),Button:wrap('button'),Input:wrap('input'),Textarea:wrap('textarea'),Switch:(p:{checked:boolean;disabled:boolean;onChange:Function})=>r.createElement('input',{type:'checkbox',checked:p.checked,disabled:p.disabled,onChange:(e:Event)=>p.onChange({detail:{value:(e.target as HTMLInputElement).checked}})})};});
let root:Root,box:HTMLDivElement;
async function mount(Page:React.ComponentType<any>,props={}){box=document.createElement('div');document.body.append(box);root=createRoot(box);await act(async()=>root.render(React.createElement(Page,props)));}
async function unmount(){await act(async()=>root.unmount());box.remove();}
async function wait(predicate:()=>boolean,timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){await act(async()=>{await new Promise(r=>setTimeout(r,40));});if(predicate())return;}throw Error('Formal main-page HTTP convergence timed out: '+box.textContent);}
function button(label:string){const scoped=['批准此供给及报价','发布此活动供给','按原申请时刻核定退款','加入这一桌'].includes(label);return [...box.querySelectorAll('button')].find(x=>x.textContent===label&&(!scoped||x.closest('article,.meal-card')?.textContent?.includes(process.env.FORMAL_ACTIVITY_ID!)));}
async function click(label:string){
 const paged=['批准此供给及报价','发布此活动供给','按原申请时刻核定退款'].includes(label);
 if(paged)for(let page=0;page<100;page++){
  await wait(()=>!!button('刷新正式业务记录')&&!button('刷新正式业务记录')!.disabled);
  if(button(label))break;
  const next=button('加载下一页正式业务记录');if(!next)throw Error('Formal record missing across available pages: '+label+'; '+box.textContent);
  await act(async()=>next.click());
 }
 await wait(()=>!!button(label)&&!button(label)!.disabled);await act(async()=>button(label)!.click());}
async function field(label:string,value:string){const input=[...box.querySelectorAll('label')].find(l=>l.textContent?.startsWith(label))!.querySelector('input')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));});}
it('actual main activity/order and controlled ops components use formal HTTP supply/signup/receipt/refund routes and recover after remount',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('__FANJU_DEMO_MODE__',false);vi.stubGlobal('__FANJU_FORMAL_BUSINESS__',true);vi.stubGlobal('__FANJU_API_BASE_URL__',bridge.origin);vi.stubGlobal('__FANJU_PRELAUNCH_ENABLED__',false);
 const {createControlledIdentityClient}=await import('../../apps/ops/src/controlled-identity-api.js');const {FormalBusinessWorkspace}=await import('../../apps/ops/src/FormalBusinessWorkspace.js');
 const transport=async(path:string,options:RequestInit)=>{bridge.paths.push(path);const res=await fetch(bridge.origin+path,options);return{status:res.status,data:await res.json()};};
 const client=createControlledIdentityClient(transport);const restaurant=await client.login(process.env.FORMAL_RESTAURANT_USERNAME!,process.env.FORMAL_PASSWORD!);
 await mount(FormalBusinessWorkspace,{client,identity:restaurant,onSessionLost:()=>{throw Error('Unexpected controlled session loss');}});
 try{
  await field('活动编号',process.env.FORMAL_ACTIVITY_ID!);await field('政策版本编号',process.env.FORMAL_POLICY_ID!);await field('D 保证金', '200');await click('提交餐厅供给');await wait(()=>box.textContent!.includes('供给申请：'));
 }finally{await unmount();}
 client.logout();const ops=await client.login(process.env.FORMAL_OPS_USERNAME!,process.env.FORMAL_PASSWORD!);await mount(FormalBusinessWorkspace,{client,identity:ops,onSessionLost:()=>{throw Error('Unexpected controlled session loss');}});
 try{await click('刷新正式业务记录');await wait(()=>box.textContent!.includes('批准此供给及报价'));await click('批准此供给及报价');await click('发布此活动供给');await wait(()=>box.textContent!.includes('活动已按此供给发布'));}finally{await unmount();}
 bridge.storage.set('fanju_session_v2',process.env.FORMAL_USER_TOKEN!);
 const Activity=(await import('../../apps/miniapp/src/pages/activity-detail/index.js')).default,Order=(await import('../../apps/miniapp/src/pages/order-detail/index.js')).default;
 const Home=(await import('../../apps/miniapp/src/pages/home/index.js')).default;await mount(Home);try{for(let page=0;page<100&&!box.textContent!.includes(process.env.FORMAL_ACTIVITY_ID!);page++){await wait(()=>box.textContent!.includes(process.env.FORMAL_ACTIVITY_ID!)||!!button('下一页活动'));if(box.textContent!.includes(process.env.FORMAL_ACTIVITY_ID!))break;await click('下一页活动');await wait(()=>!button('下一页活动')?.disabled);}await wait(()=>box.textContent!.includes(process.env.FORMAL_ACTIVITY_ID!));expect(box.textContent).toContain('保证金 D 2 元；合计 3 元');await click('资料与账号权利请求');expect(bridge.navigation).toBe('/pages/rights/index');await click('加入这一桌');expect(bridge.navigation).toContain('/pages/activity-detail/index?id='+process.env.FORMAL_ACTIVITY_ID);}finally{await unmount();}
 await mount(Activity);try{
  await wait(()=>box.textContent!.includes('本次合计：¥3.00'));await click('阅读报名协议与退款规则');await wait(()=>box.querySelectorAll('input[type=checkbox]').length===3);
  await click('男性');await act(async()=>box.querySelectorAll<HTMLInputElement>('input[type=checkbox]').forEach(x=>x.click()));await click('提交报名并锁定报价');await wait(()=>bridge.navigation.includes('/pages/order-detail/index?id='));
 }finally{await unmount();}
 const id=new URL('http://owned'+bridge.navigation).searchParams.get('id')!;bridge.params={id};await mount(Order);
 try{await wait(()=>box.textContent!.includes('报名状态：PENDING_PAYMENT'));await click('继续支付');await wait(()=>box.textContent!.includes('报名状态：FORMAL'));expect(box.textContent).not.toContain('合成受限地址');for(const label of ['提交咨询请求','提交补证受理请求','提交履约争议','提交申诉']){await click(label);await wait(()=>box.textContent!.includes('请求已受理'));expect(box.textContent).toContain('不自动取消报名或释放席位');expect(box.textContent).toContain('报名状态：FORMAL');expect(box.textContent).not.toContain('取消已接受');}await click('申请取消及退款');await wait(()=>box.textContent!.includes('取消已接受'));expect(box.textContent).toContain('退款金额核定、执行及到账分别处理');}finally{await unmount();}
 await mount(FormalBusinessWorkspace,{client,identity:ops,onSessionLost:()=>{throw Error('Unexpected controlled session loss');}});
 try{await click('刷新正式业务记录');for(let page=0;page<100&&!['咨询','补证','履约争议','申诉'].every(category=>[...box.querySelectorAll('article')].some(x=>x.textContent?.includes('请求类别：'+category)&&x.textContent?.includes(process.env.FORMAL_ACTIVITY_ID!)));page++){await wait(()=>!button('刷新正式业务记录')!.disabled);if(!button('加载下一页正式业务记录'))break;await click('加载下一页正式业务记录');}for(const category of ['咨询','补证','履约争议','申诉']){const inquiry=[...box.querySelectorAll('article')].find(x=>x.textContent?.includes('请求类别：'+category)&&x.textContent?.includes(process.env.FORMAL_ACTIVITY_ID!));expect(inquiry).toBeDefined();expect(inquiry!.textContent).toContain('只受理待人工处理');expect(inquiry!.textContent).not.toContain('责任人待核对');expect(inquiry!.querySelector('button')).toBeNull();}await wait(()=>box.textContent!.includes('按原申请时刻核定退款'));await click('按原申请时刻核定退款');await wait(()=>box.textContent!.includes('退款处理：'));expect(box.textContent).toContain('WAITING_BATCH');}finally{await unmount();}
 // Clear all client state and reauthenticate: recover original server record.
 bridge.storage.clear();bridge.storage.set('fanju_session_v2',process.env.FORMAL_USER_TOKEN!);await mount(Order);
 try{await wait(()=>box.textContent!.includes('F 服务费：¥1.00'));const deadline=Date.now()+70000;while(Date.now()<deadline&&!box.textContent!.includes('渠道已确认退回')){await click('核对收款与退款进度');await wait(()=>![...box.querySelectorAll('button')].find(x=>x.textContent==='刷新报名')!.disabled);if(!box.textContent!.includes('渠道已确认退回'))await act(async()=>{await new Promise(r=>setTimeout(r,300));});}expect(box.textContent).toContain('渠道已确认退回');expect(bridge.paths.some(p=>p.includes('/api/prelaunch/'))).toBe(false);expect(bridge.paths.some(p=>p.endsWith('/payment/prepare'))).toBe(true);expect(bridge.paths.some(p=>p.endsWith('/decide'))).toBe(true);}finally{await unmount();client.logout();vi.unstubAllGlobals();}
},100000);

it('actual formal activity and order pages block malformed delivery and monetary records',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('__FANJU_DEMO_MODE__',false);vi.stubGlobal('__FANJU_FORMAL_BUSINESS__',true);vi.stubGlobal('__FANJU_API_BASE_URL__',bridge.origin);vi.stubGlobal('__FANJU_PRELAUNCH_ENABLED__',false);bridge.storage.set('fanju_session_v2',process.env.FORMAL_USER_TOKEN!);
 const orderId=new URL('http://owned'+bridge.navigation).searchParams.get('id')!;
 bridge.params={id:process.env.FORMAL_ACTIVITY_ID!};bridge.corrupt='policy';const Activity=(await import('../../apps/miniapp/src/pages/activity-detail/index.js')).default;
 await mount(Activity);try{await wait(()=>box.textContent!.includes('本次合计'));await click('阅读报名协议与退款规则');await wait(()=>box.textContent!.includes('报名规则资料不完整'));expect(button('提交报名并锁定报价')!.disabled).toBe(true);expect(box.querySelectorAll('input[type=checkbox]')).toHaveLength(2);}finally{await unmount();}
 bridge.params={id:orderId};bridge.corrupt='record';const Order=(await import('../../apps/miniapp/src/pages/order-detail/index.js')).default;
 await mount(Order);try{await wait(()=>box.textContent!.includes('报名记录资料不完整'));expect(box.textContent).not.toContain('合成受限地址');expect(button('继续支付')).toBeUndefined();expect(button('申请取消及退款')).toBeUndefined();}finally{await unmount();}
 bridge.corrupt='list';const Home=(await import('../../apps/miniapp/src/pages/home/index.js')).default;await mount(Home);try{await wait(()=>box.textContent!.includes('1 项活动暂不可报名'));await click('刷新活动');await wait(()=>!button('刷新活动')!.disabled);expect(box.textContent).toContain('1 项活动暂不可报名');}finally{await unmount();bridge.corrupt='';vi.unstubAllGlobals();}
});

it('actual formal main order entry preserves original legacy order and refund history and rejects another user record',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('__FANJU_DEMO_MODE__',false);vi.stubGlobal('__FANJU_FORMAL_BUSINESS__',true);vi.stubGlobal('__FANJU_API_BASE_URL__',bridge.origin);vi.stubGlobal('__FANJU_PRELAUNCH_ENABLED__',false);bridge.storage.set('fanju_session_v2',process.env.FORMAL_USER_TOKEN!);bridge.params={history:'legacy'};
 const List=(await import('../../apps/miniapp/src/pages/order-list/index.js')).default;await mount(List);try{await wait(()=>box.textContent!.includes('合成旧订单菜单体验'));expect(box.textContent).toContain('原订单金额：¥12.34');expect(box.textContent).not.toContain('98.76');await click('查看旧订单记录');expect(bridge.navigation).toContain('history=legacy');}finally{await unmount();}
 const Order=(await import('../../apps/miniapp/src/pages/order-detail/index.js')).default;bridge.params={id:process.env.FORMAL_LEGACY_ORDER_ID!,history:'legacy'};await mount(Order);try{await wait(()=>box.textContent!.includes('退款记录：¥2.34'));expect(box.textContent).toContain('REFUNDING');expect(button('继续支付')).toBeUndefined();expect(button('申请取消及退款')).toBeUndefined();expect(box.textContent).not.toContain('合成受限地址');}finally{await unmount();}
 bridge.params={id:process.env.FORMAL_FOREIGN_ORDER_ID!,history:'legacy'};await mount(Order);try{await wait(()=>box.querySelector('.error-text')!==null);expect(box.textContent).not.toContain('98.76');expect(box.textContent).not.toContain('合成受限地址');}finally{await unmount();vi.unstubAllGlobals();}
});


it('actual restaurant and owner main pages record formal normal fulfillment without claiming channel refund completion',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('__FANJU_DEMO_MODE__',false);vi.stubGlobal('__FANJU_FORMAL_BUSINESS__',true);vi.stubGlobal('__FANJU_API_BASE_URL__',bridge.origin);vi.stubGlobal('__FANJU_PRELAUNCH_ENABLED__',false);
 const {createControlledIdentityClient}=await import('../../apps/ops/src/controlled-identity-api.js'),{FormalBusinessWorkspace}=await import('../../apps/ops/src/FormalBusinessWorkspace.js');
 const client=createControlledIdentityClient(async(path,options)=>{bridge.paths.push(path);const r=await fetch(bridge.origin+path,options);return{status:r.status,data:await r.json()};});const restaurant=await client.login(process.env.FORMAL_RESTAURANT_USERNAME!,process.env.FORMAL_PASSWORD!);await mount(FormalBusinessWorkspace,{client,identity:restaurant,onSessionLost:()=>{throw Error('Unexpected session loss');}});
 try{await click('刷新正式履约记录');for(let i=0;i<100&&!box.textContent!.includes(process.env.FORMAL_FULFILLMENT_REGISTRATION_ID!);i++){await wait(()=>!!button('加载下一页履约记录')||box.textContent!.includes(process.env.FORMAL_FULFILLMENT_REGISTRATION_ID!));if(box.textContent!.includes(process.env.FORMAL_FULFILLMENT_REGISTRATION_ID!))break;await click('加载下一页履约记录');}await wait(()=>box.textContent!.includes(process.env.FORMAL_FULFILLMENT_REGISTRATION_ID!));const row=[...box.querySelectorAll('article')].find(x=>x.textContent!.includes(process.env.FORMAL_FULFILLMENT_REGISTRATION_ID!))!;const confirm=[...row.querySelectorAll('button')].find(x=>x.textContent==='确认正常履约并登记退保证金义务')!;await act(async()=>confirm.click());await wait(()=>box.textContent!.includes('履约事实已保存：NORMAL'));expect(box.textContent).toContain('不代表渠道退款到账');}finally{await unmount();client.logout();}
 bridge.storage.set('fanju_session_v2',process.env.FORMAL_USER_TOKEN!);bridge.params={id:process.env.FORMAL_FULFILLMENT_REGISTRATION_ID!};const Order=(await import('../../apps/miniapp/src/pages/order-detail/index.js')).default;await mount(Order);try{await wait(()=>box.textContent!.includes('餐厅已确认正常履约'));expect(box.textContent).toContain('保证金退款义务与渠道到账分别处理');expect(box.textContent).toContain('消息记录不代表可靠送达');expect(box.textContent).not.toContain('渠道已确认退回');expect(bridge.paths.some(x=>x.includes('/api/prelaunch/'))).toBe(false);}finally{await unmount();vi.unstubAllGlobals();}
},30000);


it('actual user rights main page persists five request kinds and controlled owner inbox exposes only intake work',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('__FANJU_DEMO_MODE__',false);vi.stubGlobal('__FANJU_FORMAL_BUSINESS__',true);vi.stubGlobal('__FANJU_API_BASE_URL__',bridge.origin);vi.stubGlobal('__FANJU_PRELAUNCH_ENABLED__',false);bridge.storage.set('fanju_session_v2',process.env.FORMAL_USER_TOKEN!);
 const Rights=(await import('../../apps/miniapp/src/pages/rights/index.js')).default;await mount(Rights);try{await wait(()=>!!button('刷新权利请求')&&!button('刷新权利请求')!.disabled);for(const label of ['查阅资料','申请导出','申请更正','申请注销','申请撤回']){await click(label);await wait(()=>box.textContent!.includes(label+'请求已受理'));expect(box.textContent).toContain('尚未执行资料或账号变更');}await click('申请注销');await wait(()=>box.textContent!.includes('申请注销请求已受理'));}finally{await unmount();}
 const {formalRequest}=await import('../../apps/miniapp/src/api.js');const list=await formalRequest<{requests:Array<{id:string;kind:string}>}>('/api/v11/formal/rights');expect(list.requests).toHaveLength(5);
 await mount(Rights);try{await wait(()=>list.requests.every(r=>box.textContent!.includes(r.id)));expect(box.textContent).toContain('未结资金义务不会因此消失');}finally{await unmount();}
 const {createControlledIdentityClient}=await import('../../apps/ops/src/controlled-identity-api.js'),{FormalBusinessWorkspace}=await import('../../apps/ops/src/FormalBusinessWorkspace.js');const client=createControlledIdentityClient(async(path,options)=>{bridge.paths.push(path);const response=await fetch(bridge.origin+path,options);return{status:response.status,data:await response.json()};});const ops=await client.login(process.env.FORMAL_OPS_USERNAME!,process.env.FORMAL_PASSWORD!);await mount(FormalBusinessWorkspace,{client,identity:ops,onSessionLost:()=>{throw Error('Unexpected rights session loss');}});try{await click('读取资料权利待办');for(let page=0;page<100&&!list.requests.every(r=>box.textContent!.includes(r.id));page++){await wait(()=>!button('读取资料权利待办')!.disabled);if(!button('下一页资料权利待办'))break;await click('下一页资料权利待办');}await wait(()=>list.requests.every(r=>box.textContent!.includes(r.id)));const section=box.querySelector('[aria-label="正式资料权利待办"]')!;expect(section.textContent).toContain('内部工作队列期限不是业务承诺');for(const request of list.requests){const row=[...section.querySelectorAll('article')].find(x=>x.textContent!.includes(request.id))!;expect(row.textContent).not.toContain('待核对');expect(row.querySelector('button')).toBeNull();}expect(bridge.paths.some(path=>path.includes('/api/prelaunch/'))).toBe(false);}finally{await unmount();client.logout();vi.unstubAllGlobals();}
},30000);
