// @vitest-environment jsdom
import React from '../../apps/ops/node_modules/react/index.js';
import {createRoot,type Root} from '../../apps/ops/node_modules/react-dom/client.js';
import {act} from '../../apps/ops/node_modules/react-dom/test-utils.js';
import {afterEach,it,expect,vi} from 'vitest';
const fixture=vi.hoisted(()=>({accepted:true as boolean|undefined,failure:false,requests:[] as any[],history:[] as any[],responsibilityReviews:[] as any[],linkage:'ROOT'}));
vi.mock('../../apps/miniapp/node_modules/@tarojs/taro/index.js',async()=>{const r=await import('../../apps/ops/node_modules/react/index.js');return{useRouter:()=>({params:{id:'owned-registration'}}),useDidShow:(f:()=>void)=>r.useEffect(f,[]),useDidHide:()=>{},navigateTo:async()=>{}};});
vi.mock('../../apps/miniapp/node_modules/@tarojs/components/dist/index.js',async()=>{const r=await import('../../apps/ops/node_modules/react/index.js');const wrap=(tag:string)=>(p:any)=>r.createElement(tag,p,p.children);return{View:wrap('div'),Text:wrap('span'),Button:wrap('button')};});
vi.mock('../../apps/miniapp/src/api',()=>({formalRefundRequestKey:async()=> 'owned-request',beginNewFormalAttempt:vi.fn(),prepareFormalPayment:vi.fn(),formalRequest:async(path:string,options:any)=>{if(path.endsWith('/refund-requests')){fixture.requests.push(options);if(fixture.failure)throw Error('申请处理失败，请重试');return{acceptedAt:'2026-10-02T00:00:00Z',state:'ACCEPTED',linkageState:fixture.linkage,originalRequestId:fixture.linkage==='LINKED'?'root-request':null,originalAcceptedAt:fixture.linkage==='LINKED'?'2026-09-30T00:00:00Z':null,cancellationAccepted:fixture.accepted,membershipEnded:fixture.accepted};}return{registration:{id:'owned-registration',title:'菜单体验',state:'FORMAL',F:100,D:200,total:300,acceptedAt:'2026-10-01T00:00:00Z',holdExpiresAt:null,restaurantName:null,address:null,refunds:[],requests:fixture.history,responsibilityReviews:fixture.responsibilityReviews,tableState:'INVALIDATED',cancelAcceptedAt:'2026-10-02T00:00:00Z',queueOrdinal:'9',notices:[{id:'notice',kind:'TABLE_INVALIDATE',state:'CREATED',receivedAt:null}]}};}}));
import {FormalOrderDetail} from '../../apps/miniapp/src/FormalOrderDetail';
let root:Root|undefined,box:HTMLDivElement;
afterEach(async()=>{if(root){await act(async()=>root!.unmount());root=undefined;box.remove();}fixture.requests=[];fixture.history=[];fixture.responsibilityReviews=[];fixture.linkage='ROOT';fixture.failure=false;vi.unstubAllGlobals();});
async function apply(accepted:boolean|undefined,failure=false,label='申请取消及退款'){fixture.accepted=accepted;fixture.failure=failure;vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);box=document.createElement('div');document.body.append(box);root=createRoot(box);await act(async()=>root!.render(React.createElement(FormalOrderDetail)));await act(async()=>{[...box.querySelectorAll('button')].find(x=>x.textContent===label)!.click();});}
it('explicit ordinary cancellation displays accepted exit separately from refund completion',async()=>{await apply(true);expect(fixture.requests).toEqual([{method:'POST',data:{businessKey:'owned-request',requestCategory:'ORDINARY_CANCEL'}}]);expect(box.textContent).toContain('取消已接受，正式成员资格已结束、席位已释放');expect(box.textContent).toContain('退款金额核定、执行及到账分别处理');expect(box.textContent).not.toContain('退款已完成');});
it.each([false,undefined])('does not claim cancellation or released membership when acceptance is %s',async accepted=>{await apply(accepted);expect(box.textContent).toContain('取消尚待核实');expect(box.textContent).not.toContain('取消已接受');expect(box.textContent).not.toContain('正式成员资格已结束');});
it('HTTP failure displays error without claiming accepted cancellation',async()=>{await apply(true,true);expect(box.textContent).toContain('申请处理失败，请重试');expect(box.textContent).not.toContain('取消已接受');});

it('renders original cancellation, table and queue facts without promoting inbox creation to delivery',async()=>{await apply(false);expect(box.textContent).toContain('桌态：当前成团失效');expect(box.textContent).toContain('原取消受理时间：2026-10-02T00:00:00Z');expect(box.textContent).toContain('候补受理序号：9（不代表当前排名）');expect(box.textContent).toContain('已创建，待投递');expect(box.textContent).toContain('消息记录不代表可靠送达');});

it.each([['CONSULTATION','提交咨询请求'],['EVIDENCE','提交补证受理请求'],['DISPUTE','提交履约争议'],['APPEAL','提交申诉']])('explicit %s submits intake only without claiming cancellation',async(category,label)=>{await apply(false,false,label);expect(fixture.requests[0].data.requestCategory).toBe(category);expect(box.textContent).toContain('不自动取消报名或释放席位');expect(box.textContent).not.toContain('取消已接受');});

it('submits the selected owned parent and retains the original accepted time for a linked supplement',async()=>{
 fixture.history=[{id:'root-request',kind:'CORE_CHANGE_REJECTION_REVIEW',requestCategory:'SPECIAL_REFUND',acceptedAt:'2026-09-30T00:00:00Z',state:'ACCEPTED',blockerIds:[],linkageState:'ROOT',originalRequestId:'root-request',originalAcceptedAt:'2026-09-30T00:00:00Z'}];fixture.linkage='LINKED';
 await apply(false,false,'提交咨询请求');fixture.requests=[];
 await act(async()=>{[...box.querySelectorAll('button')].find(x=>x.textContent==='选择原申请 root-request')!.click();});
 await act(async()=>{[...box.querySelectorAll('button')].find(x=>x.textContent==='提交补证受理请求')!.click();});
 expect(fixture.requests[0].data).toEqual({businessKey:'owned-request',requestCategory:'EVIDENCE',parentRequestId:'root-request'});expect(box.textContent).toContain('已关联原申请：root-request；原受理时间：2026-09-30T00:00:00Z');expect(box.textContent).toContain('本次受理：2026-10-02T00:00:00Z');expect(box.textContent).not.toContain('取消已接受');
});
it('reports an unlinked appeal as awaiting linkage without consuming a review allowance',async()=>{fixture.linkage='UNLINKED';await apply(false,false,'提交申诉');expect(fixture.requests[0].data).not.toHaveProperty('parentRequestId');expect(box.textContent).toContain('尚未关联原申请');expect(box.textContent).toContain('不代表已补到某案或已使用复审额度');});

it('shows activity responsibility review separately without making it a personal refund parent',async()=>{fixture.responsibilityReviews=[{id:'activity-review',state:'AWAITING_FULFILLMENT_RIGHTS_REVIEW',originalRequestAcceptedAt:'2026-10-02T00:00:00Z',reviewOwner:'ops-owner',membershipEnded:false,cancellationAccepted:false}];await apply(false,false,'提交咨询请求');expect(box.textContent).toContain('责任取消请求待独立履约权益审核');expect(box.textContent).toContain('审核负责人：ops-owner');expect(box.textContent).toContain('尚未接受取消，成员与席位保留，原资金处置不变');expect([...box.querySelectorAll('button')].some(b=>b.textContent==='选择原申请 activity-review')).toBe(false);expect(fixture.requests[0].data).not.toHaveProperty('parentRequestId');});
