// @vitest-environment jsdom
import React from '../../apps/ops/node_modules/react/index.js';
import {createRoot,type Root} from '../../apps/ops/node_modules/react-dom/client.js';
import {act} from '../../apps/ops/node_modules/react-dom/test-utils.js';
import {it,expect,vi} from 'vitest';
const state=vi.hoisted(()=>({registration:'',authorization:''}));
vi.mock('../../apps/miniapp/node_modules/@tarojs/taro/index.js',async()=>{const r=await import('../../apps/ops/node_modules/react/index.js');return{useRouter:()=>({params:{id:state.registration}}),useDidShow:(f:()=>void)=>r.useEffect(f,[]),useDidHide:()=>{},navigateTo:async()=>{}};});
vi.mock('../../apps/miniapp/node_modules/@tarojs/components/dist/index.js',async()=>{const r=await import('../../apps/ops/node_modules/react/index.js');const wrap=(tag:string)=>(p:any)=>r.createElement(tag,p,p.children);return{View:wrap('div'),Text:wrap('span'),Button:wrap('button')};});
vi.mock('../../apps/miniapp/src/api',()=>({formalRefundRequestKey:vi.fn(),beginNewFormalAttempt:vi.fn(),prepareFormalPayment:vi.fn(),formalRequest:async(path:string,options:any={})=>{const res=await fetch(process.env.CORE_ORIGIN+path,{method:options.method??'GET',headers:{authorization:state.authorization,'content-type':'application/json'},...(options.data?{body:JSON.stringify(options.data)}:{})});if(!res.ok)throw Error('Synthetic HTTP operation failed '+res.status);return res.json();}}));
import {createControlledIdentityClient} from '../../apps/ops/src/controlled-identity-api.js';
import {FormalBusinessWorkspace} from '../../apps/ops/src/FormalBusinessWorkspace.js';
import {FormalOrderDetail} from '../../apps/miniapp/src/FormalOrderDetail.js';
it('actual main OPS proposes only signed candidate and own order records ACCEPT or REJECT without applying shared changes',async()=>{
 vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);let box:HTMLDivElement,root:Root;
 async function mount(node:React.ReactElement){box=document.createElement('div');document.body.append(box);root=createRoot(box);await act(async()=>root.render(node));}
 async function unmount(){await act(async()=>root.unmount());box.remove();}
 async function wait(predicate:()=>boolean){const end=Date.now()+10000;while(Date.now()<end){await act(async()=>{await new Promise(r=>setTimeout(r,30));});if(predicate())return;}throw Error('Core change DOM timeout: '+box.textContent);}
 const button=(label:string)=>[...box.querySelectorAll('button')].find(b=>b.textContent===label);
 async function click(label:string){await wait(()=>!!button(label)&&!button(label)!.disabled);await act(async()=>button(label)!.click());}
 const client=createControlledIdentityClient(async(path,options)=>{const res=await fetch(process.env.CORE_ORIGIN+path,options);return{status:res.status,data:await res.json()};});
 const identity=await client.login(process.env.CORE_OPS_USERNAME!,process.env.CORE_PASSWORD!);await mount(React.createElement(FormalBusinessWorkspace,{client,identity,onSessionLost:()=>{throw Error('Session lost');}}));
 try{for(const [text,value] of [['原活动编号',process.env.CORE_ACTIVITY_ID],['候选供给编号',process.env.CORE_SUPPLY_ID],['签收业务编号',process.env.CORE_KEY]]){const el=[...box.querySelectorAll('label')].find(l=>l.textContent===text)!.querySelector('input')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});}await click('按专门签收提出核心变更');await wait(()=>box.textContent!.includes('正式核心变更已提出'));expect(box.textContent).toContain('尚未应用');}finally{await unmount();}
 state.registration=process.env.CORE_REGISTRATION_ID!;state.authorization=process.env.CORE_USER_AUTHORIZATION!;await mount(React.createElement(FormalOrderDetail));
 try{await click('读取核心变更');await wait(()=>box.textContent!.includes('拟议餐厅：合成候选江边餐厅'));expect(box.textContent).toContain('原餐厅：合成正式餐厅');expect(box.textContent).toContain('合成江边商圈');expect(box.textContent).not.toContain('合成候选完整受限地址');expect(box.textContent).not.toContain('synthetic-candidate-phone');await click('记录本人同意意向');await wait(()=>box.textContent!.includes('已记录本人同意意向'));expect(box.textContent).toContain('原活动及费用尚未变更');expect(box.textContent).toContain('本人答复：同意意向');}finally{await unmount();}
 state.registration=process.env.CORE_REJECT_REGISTRATION_ID!;state.authorization=process.env.CORE_REJECT_AUTHORIZATION!;await mount(React.createElement(FormalOrderDetail));
 try{await click('读取核心变更');await click('拒绝变更并退出');await wait(()=>box.textContent!.includes('已记录本人拒绝并结束成员资格、释放席位'));expect(box.textContent).toContain('按原 F+D 保存退款义务');expect(box.textContent).toContain('本人答复：拒绝');expect(box.textContent).not.toContain('退款已完成');}finally{await unmount();}
 await mount(React.createElement(FormalOrderDetail));try{await click('读取核心变更');await wait(()=>box.textContent!.includes('本人答复：拒绝'));expect(button('拒绝变更并退出')).toBeUndefined();}finally{await unmount();}
 state.registration=process.env.CORE_NORMAL_REGISTRATION_ID!;state.authorization=process.env.CORE_NORMAL_AUTHORIZATION!;await mount(React.createElement(FormalOrderDetail));try{await click('读取核心变更');await click('拒绝变更并退出');await wait(()=>box.textContent!.includes('拒绝意向已受理；已有正常履约事实'));expect(box.textContent).toContain('尚未退出、释放席位或建立全额退款义务');expect(box.textContent).toContain('拒绝意向待人工权益核查');expect(box.textContent).not.toContain('已记录本人拒绝并结束成员资格');}finally{await unmount();}
 await mount(React.createElement(FormalOrderDetail));try{await click('读取核心变更');await wait(()=>box.textContent!.includes('拒绝意向待人工权益核查'));expect(button('拒绝变更并退出')).toBeUndefined();}finally{await unmount();}
 await mount(React.createElement(FormalBusinessWorkspace,{client,identity,onSessionLost:()=>{throw Error('Session lost');}}));try{await click('读取核心变更及答复');await wait(()=>!!button('读取核心变更及答复')&&!button('读取核心变更及答复')!.disabled);for(let page=0;page<100&&!box.querySelector('[data-core-review-registration="'+state.registration+'"]');page++){if(!button('加载下一页核心变更及答复'))break;await click('加载下一页核心变更及答复');await wait(()=>!button('读取核心变更及答复')!.disabled);}const review=box.querySelector('[data-core-review-registration="'+state.registration+'"]');expect(review).not.toBeNull();expect(review!.textContent).toContain('AWAITING_FULFILLMENT_RIGHTS_REVIEW');expect(review!.textContent).toContain('原变更提出：');expect(review!.textContent).toContain('负责人：'+identity.id);expect(box.textContent).toContain('尚未退出或建立全额退款义务');}finally{await unmount();}
});
