// @vitest-environment jsdom
// Real owned HTTP + React DOM. Native render surfaces are adapters, not a WeChat device.
import React from "../../apps/ops/node_modules/react/index.js";
import {createRoot,type Root} from "../../apps/ops/node_modules/react-dom/client.js";
import {act} from "../../apps/ops/node_modules/react-dom/test-utils.js";
import {afterAll,beforeAll,describe,expect,it,vi} from "vitest";
const bridge=vi.hoisted(()=>({storage:new Map<string,unknown>(),requests:[] as Array<{method:string;path:string;status:number}>,base:process.env.PRELAUNCH_HTTP_DOM_ORIGIN!}));
vi.mock("../../apps/miniapp/node_modules/@tarojs/taro/index.js",async()=>{const react=await import("../../apps/ops/node_modules/react/index.js");return{default:{getStorageSync:(k:string)=>bridge.storage.get(k),setStorageSync:(k:string,v:unknown)=>bridge.storage.set(k,v),removeStorageSync:(k:string)=>bridge.storage.delete(k),request:async(r:{url:string;method:string;header:Record<string,string>;data?:unknown})=>{const path=new URL(r.url).pathname+new URL(r.url).search;const result=await fetch(bridge.base+path,{method:r.method,headers:r.header,...(r.data===undefined?{}:{body:JSON.stringify(r.data)})});bridge.requests.push({method:r.method,path,status:result.status});return{statusCode:result.status,data:await result.json()};}},useDidShow:(f:()=>void)=>react.useEffect(f,[]),useDidHide:()=>{}};});
vi.mock("../../apps/miniapp/node_modules/@tarojs/components/dist/index.js",async()=>{const react=await import("../../apps/ops/node_modules/react/index.js");const wrap=(tag:string)=>(props:Record<string,unknown>)=>{const {children,scrollY,selectable,password,onInput,...rest}=props;return react.createElement(tag,{...rest,...(tag==='input'?{type:password?'password':'text',onInput:(e:Event)=>(onInput as Function)?.({detail:{value:(e.target as HTMLInputElement).value}})}:{})},children as React.ReactNode);};return{Button:wrap('button'),Input:wrap('input'),ScrollView:wrap('div'),Text:wrap('span'),View:wrap('div')};});
let Page:React.ComponentType;let container:HTMLDivElement;let root:Root;
async function waitFor(predicate:()=>boolean){for(let i=0;i<100;i++){await act(async()=>{await new Promise(r=>setTimeout(r,20));});if(predicate())return;}throw Error('Owned HTTP DOM convergence timed out');}
async function mount(){container=document.createElement('div');document.body.append(container);root=createRoot(container);await act(async()=>root.render(React.createElement(Page)));}
async function unmount(){await act(async()=>root.unmount());container.remove();}
function input(placeholder:string,value:string){const el=container.querySelector<HTMLInputElement>(`input[placeholder="${placeholder}"]`)!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));}
async function click(label:string){await act(async()=>[...container.querySelectorAll('button')].find(b=>b.textContent===label)!.click());}
async function login(){await act(async()=>{input('测试账号 ID',process.env.PRELAUNCH_HTTP_DOM_ACTOR_ID!);input('测试密码',process.env.PRELAUNCH_HTTP_DOM_PASSWORD!);});await click('登录');await waitFor(()=>container.textContent!.includes(process.env.PRELAUNCH_HTTP_DOM_REGISTRATION_ID!));}
beforeAll(async()=>{vi.stubGlobal('__FANJU_PRELAUNCH_ENABLED__',true);vi.stubGlobal('__FANJU_API_BASE_URL__',bridge.base);Page=(await import('../../apps/miniapp/src/pages/prelaunch/index.js')).default;await mount();});
afterAll(async()=>{await unmount();vi.unstubAllGlobals();});
describe('PRE040/041 owned HTTP and DOM joint scope',()=>{
 it('recovers the same server registration after DOM process remount and cleared client cache with explicit reauthentication',async()=>{await login();await click('查看详情');expect(container.textContent).toContain(process.env.PRELAUNCH_HTTP_DOM_REGISTRATION_ID!);await unmount();bridge.storage.clear();await mount();await waitFor(()=>container.textContent!.includes('受控测试账号'));expect(container.textContent).not.toContain(process.env.PRELAUNCH_HTTP_DOM_REGISTRATION_ID!);await login();await click('查看详情');expect(container.textContent).toContain(process.env.PRELAUNCH_HTTP_DOM_REGISTRATION_ID!);expect(bridge.requests.some(r=>r.path==='/api/prelaunch/v11/registrations'&&r.method==='GET'&&r.status===200)).toBe(true);expect(bridge.requests.some(r=>r.path==='/api/prelaunch/v11/registrations'&&r.method==='POST')).toBe(false);});
 it('keeps real HTTP orders and detail usable when only the owned notice-list query returns a sanitized HTTP500',async()=>{await waitFor(()=>container.textContent!.includes('消息暂时不可用'));expect(container.textContent).toContain(process.env.PRELAUNCH_HTTP_DOM_REGISTRATION_ID!);expect(bridge.requests.some(r=>r.path==='/api/prelaunch/v11/notices'&&r.status===500)).toBe(true);await click('查询付款与退款进度');expect(container.textContent).toContain('服务费 ¥1.00');expect(container.textContent).toContain('保证金 ¥2.00');expect(bridge.requests.some(r=>r.path.endsWith('/receive')&&r.method==='POST')).toBe(false);expect(container.textContent).not.toContain('synthetic notice list unavailable');});
});
