import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}

function atClock(dbClient,at){return new Proxy(dbClient,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field==='$queryRaw')return(...args)=>Array.isArray(args[0])&&args[0].join(' ').trim()==='SELECT clock_timestamp() AS at'?Promise.resolve([{at}]):inner.$queryRaw(...args);const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});}

const {aftersalesRoute,aftersalesHandlers}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/aftersales.js`));
async function roleActor(role,restaurantId=null){return db.v11Actor.create({data:{personId:prefix+sequence++,role,restaurantId,passwordHash:'synthetic-unused-direct-test'}});}
async function approvedBatch(f){f.supply=await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{snapshot:{scope:'TEST_ONLY',approval:{scope:'TEST_ONLY',simulationBatchHour:10}}}});return f;}
for(const [name,end,expected]of [['morning activity','2026-10-10T02:00:00Z','2026-10-11T02:00:00Z'],['cross Shanghai midnight','2026-10-10T16:30:00Z','2026-10-12T02:00:00Z']])test(`BR38 RB11 PRE027 native ${name} normal fulfillment schedules exact next Shanghai day D only and channel confirmation remains separate`,async()=>{
 const f=await approvedBatch(await fixture());const r=await registration(f,'FORMAL');const paid=await pay(r);const endsAt=new Date(end);await db.activity.update({where:{id:f.activity.id},data:{startsAt:new Date(endsAt.getTime()-2*3600_000),endsAt}});const rest=await roleActor('RESTAURANT',f.activity.restaurantId);const result=await aftersalesRoute(atClock(db,new Date(endsAt.getTime()+1)),rest,'fulfillment',{body:{registrationId:r.reg.id,result:'NORMAL'}});assert.equal(result.channelConfirmed,false);const instruction=await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:r.reg.id}});assert.equal(instruction.state,'WAITING_BATCH');assert.deepEqual([instruction.serviceFeeCents,instruction.depositCents],[0,200]);const job=await db.durableJob.findUniqueOrThrow({where:{businessKey:'v11:refund:'+instruction.id}});assert.equal(job.runAt.toISOString(),new Date(expected).toISOString());assert.equal(await channelDb.mockChannelTransaction.count({where:{kind:'REFUND',originalTradeNo:paid.fact.channelNo}}),0);const lease=await ownClaim(job);await domain.recoveryHandlers(atClock(db,new Date(expected)),channel).V11_REFUND(lease);assert.equal((await db.v11RefundInstruction.findUniqueOrThrow({where:{id:instruction.id}})).state,'CONFIRMED');assert.equal(await channelDb.mockChannelTransaction.count({where:{kind:'REFUND',originalTradeNo:paid.fact.channelNo,amountCents:200}}),1);const binding=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:r.reg.id}});assert.equal(await db.v11Disposition.count({where:{component:{receiptId:binding.receiptId,kind:'F'}}}),0);
});
test('BR39 native next-day scan without restaurant confirmation creates operational todo without automatic refund or violation',async()=>{
 const f=await approvedBatch(await fixture());const r=await registration(f,'FORMAL');await pay(r);const rest=await roleActor('RESTAURANT',f.activity.restaurantId);const code=await aftersalesRoute(db,rest,'checkinCode',{id:f.activity.id});await aftersalesRoute(db,r.actor,'checkin',{body:{registrationId:r.reg.id,qrToken:code.qrToken}});const now=await db.$transaction(domain.dbNow);await db.activity.update({where:{id:f.activity.id},data:{startsAt:new Date(now.getTime()-2*3600_000),endsAt:new Date(now.getTime()-3600_000)}});const lease=await leaseJob('V11_FULFILLMENT_CHECK',f.activity.id);await aftersalesHandlers(atClock(db,new Date(now.getTime()+24*3600_000))).V11_FULFILLMENT_CHECK(lease);const request=await db.v11Request.findUniqueOrThrow({where:{businessKey:'missing-confirmation:'+r.reg.id}});assert.equal(request.kind,'MISSING_RESTAURANT_CONFIRMATION');assert.equal(request.payload.notBreach,true);assert.ok(request.blockerIds.includes('OP-12'));assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0);assert.equal(await db.v11Request.count({where:{registrationId:r.reg.id,kind:'DISPUTE'}}),0);assert.equal((await db.v11Attendance.findUniqueOrThrow({where:{registrationId:r.reg.id}})).restaurantResult,null);
});
for(const scope of ['REFUND_D','REFUND_FD','REJECT'])test(`BR46 BR47 native special ${scope} respects legal scope and original formed T25 facts at later T20 review`,async()=>{
 const f=await approvedBatch(await fixture());const members=[];for(let i=0;i<4;i++){const r=await registration(f,'FORMAL');members.push(r);await pay(r);}const r=members[0];const originalAt=new Date(f.activity.startsAt.getTime()-25*3600_000);const request=await aftersalesRoute(atClock(db,originalAt),r.actor,'specialRefund',{id:r.reg.id,body:{businessKey:prefix+sequence++,reasonCode:'TRANSPORT_INTERRUPTED',syntheticEvidence:'SIMULATION_ONLY_MINIMAL_EVIDENCE'}});const stored=await db.v11Request.findUniqueOrThrow({where:{id:request.request.id}});assert.equal(stored.acceptedAt.getTime(),originalAt.getTime());assert.deepEqual([stored.payload.originalCancellation.effect.refundF,stored.payload.originalCancellation.effect.refundD],[0,0]);assert.equal(stored.payload.originalCancellation.effect.depositDisposition,'PLATFORM_RETAINED');const ops=await roleActor('OPS');await assert.rejects(aftersalesRoute(db,ops,'decision',{id:stored.id,body:{decision:'REFUND_D',reason:'合成非法比例',refundPercent:50}}),e=>e.code==='INVALID_INPUT');await assert.rejects(aftersalesRoute(db,ops,'decision',{id:stored.id,body:{decision:'BREACH',reason:'特殊申请不属异常履约'}}),e=>e.code==='SPECIAL_DECISION_INVALID');const decisionAt=new Date(f.activity.startsAt.getTime()-20*3600_000);await aftersalesRoute(atClock(db,decisionAt),ops,'decision',{id:stored.id,body:{decision:scope,reason:'合成批准范围'}});const instructions=await db.v11RefundInstruction.findMany({where:{registrationId:r.reg.id}});if(scope==='REJECT')assert.equal(instructions.length,0);else{assert.equal(instructions.length,1);assert.deepEqual([instructions[0].serviceFeeCents,instructions[0].depositCents],scope==='REFUND_D'?[0,200]:[100,200]);const job=await db.durableJob.findUniqueOrThrow({where:{businessKey:'v11:refund:'+instructions[0].id}});const day=new Date(decisionAt.getTime()+8*3600_000);const expected=new Date(Date.UTC(day.getUTCFullYear(),day.getUTCMonth(),day.getUTCDate()+1,2));assert.equal(job.runAt.getTime(),expected.getTime());}const after=await db.v11Request.findUniqueOrThrow({where:{id:stored.id}});assert.equal(after.acceptedAt.getTime(),originalAt.getTime());assert.deepEqual(after.payload.originalCancellation,stored.payload.originalCancellation);assert.equal((await db.v11Membership.findUniqueOrThrow({where:{registrationId:r.reg.id}})).active,true,'OP04 self-removal remains blocked, scope approval alone does not invent removal');
});
test('BR53 RB11 native approval before Shanghai midnight schedules next day without an extra calendar day',async()=>{
 const f=await approvedBatch(await fixture()),r=await registration(f,'FORMAL');await pay(r);const original=await aftersalesRoute(db,r.actor,'specialRefund',{id:r.reg.id,body:{businessKey:prefix+sequence++,reasonCode:'OTHER_EXCEPTION'}});const ops=await roleActor('OPS');const approvedAt=new Date('2026-10-10T15:59:59Z');await aftersalesRoute(atClock(db,approvedAt),ops,'decision',{id:original.request.id,body:{decision:'REFUND_D',reason:'合成午夜前批准'}});const instruction=await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:r.reg.id}});const job=await db.durableJob.findUniqueOrThrow({where:{businessKey:'v11:refund:'+instruction.id}});assert.equal(job.runAt.toISOString(),'2026-10-11T02:00:00.000Z');assert.equal(instruction.state,'WAITING_BATCH');
});
test('BR64 PRE030 native CREATED or SENT without received proof cannot start adverse worker clock or deduct D',async()=>{
 for(const state of ['CREATED','SENT']){const f=await fixture(),r=await registration(f,'FORMAL');await pay(r);const request=await db.$transaction(tx=>domain.requestRecord(tx,{businessKey:prefix+sequence++,kind:'DISPUTE',userId:r.reg.userId,registrationId:r.reg.id,state:'WAITING_EXPLANATION',payload:{scope:'SIMULATION_ONLY',initialDeliveredAt:null,resultDeliveredAt:null,finalReviewUsed:false}}));const notice=await db.v11DeliveryProof.create({data:{registrationId:r.reg.id,requestId:request.id,noticeKey:prefix+sequence++,kind:'ABNORMAL_NOTICE',state,proofType:'SIMULATED'}});const lease=await leaseJob('V11_DISPUTE_EXPIRE',request.id);await aftersalesHandlers(atClock(db,new Date(f.activity.startsAt.getTime()+7*24*3600_000))).V11_DISPUTE_EXPIRE(lease);assert.equal((await db.v11Request.findUniqueOrThrow({where:{id:request.id}})).state,'WAITING_EXPLANATION');assert.equal((await db.v11DeliveryProof.findUniqueOrThrow({where:{id:notice.id}})).receivedAt,null);assert.equal(await db.v11SettlementObligation.count({where:{sourceRef:request.id}}),0);assert.equal(await db.v11Decision.count({where:{requestId:request.id}}),0);assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0);const binding=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:r.reg.id}});assert.equal(await db.v11Disposition.count({where:{component:{receiptId:binding.receiptId}}}),0);}
});
