import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}

function atClock(dbClient,at){return new Proxy(dbClient,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field==='$queryRaw')return(...args)=>Array.isArray(args[0])&&args[0].join(' ').trim()==='SELECT clock_timestamp() AS at'?Promise.resolve([{at}]):inner.$queryRaw(...args);const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});}

const H=3600_000;
async function paidFixture(count=1){const f=await fixture();await db.restaurant.update({where:{id:f.activity.restaurantId},data:{capacity:6}});f.supply=await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{targetSize:6,maxSize:6,capacity:6}});const members=[];for(let i=0;i<count;i++){const r=await registration(f,'FORMAL');members.push(r);await pay(r);}return{...f,members};}
const cases=[['BR29 ordinary waiting T25',1,'ORDINARY',25,100,200,'REFUND'],['BR30 ordinary formed T25',4,'ORDINARY',25,0,0,'PLATFORM_RETAINED'],['BR31 ordinary formed exact T24',4,'ORDINARY',24,0,0,'RESTAURANT_COMPENSATION'],['BR62 ordinary waiting exact T24',1,'ORDINARY',24,100,200,'REFUND'],['BR62 ordinary waiting exact T8',1,'ORDINARY',8,0,200,'REFUND'],['ordinary waiting T7',1,'ORDINARY',7,0,0,'RESTAURANT_COMPENSATION'],['BR32 late formed T10',4,'LATE_FORMED',10,0,200,'REFUND'],['BR62 late formed exact T8',4,'LATE_FORMED',8,0,200,'REFUND'],['BR33 late formed T7',4,'LATE_FORMED',7,0,0,'RESTAURANT_COMPENSATION']];
for(const [name,count,category,hours,F,D,disposition]of cases)test(`native cancellation matrix: ${name} snapshots exact F D and original acceptedAt without unauthorized member removal`,async()=>{
 const f=await paidFixture(count);let r=f.members[0];if(category==='LATE_FORMED'){const t24=await leaseJob('V11_T24',f.activity.id);await domain.recoveryHandlers(db,channel).V11_T24(t24);const who=await actor(f);const joining=new Date(f.activity.startsAt.getTime()-20*H);const reg=await domain.createRegistration(atClock(db,joining),who.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:who.consent.id,membership:'FORMAL',businessKey:prefix+sequence++});const intent=await domain.startPayment(atClock(db,joining),who.actor,reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(atClock(db,joining),{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:300});r={reg,actor:who.actor};assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:reg.id}})).category,'LATE_FORMED');assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:reg.id}})).eligibilityState,'FORMAL');}
 const acceptedAt=new Date(f.activity.startsAt.getTime()-hours*H);const request=await domain.acceptCancellation(atClock(db,acceptedAt),r.actor,r.reg.id,prefix+sequence++);assert.equal(request.acceptedAt.getTime(),acceptedAt.getTime());assert.equal(request.payload.decision.effect.refundF,F);assert.equal(request.payload.decision.effect.refundD,D);assert.equal(request.payload.decision.effect.depositDisposition,disposition);assert.equal(request.payload.decision.effect.accountingRevenue,null);assert.ok(request.blockerIds.includes('OP-04'));const again=await domain.acceptCancellation(atClock(db,new Date(acceptedAt.getTime()+H)),r.actor,r.reg.id,prefix+sequence++);assert.equal(again.id,request.id);assert.equal(again.acceptedAt.getTime(),acceptedAt.getTime());assert.deepEqual(again.payload.decision,request.payload.decision);assert.equal((await db.v11Membership.findUniqueOrThrow({where:{registrationId:r.reg.id}})).active,true);assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0,'Formal removal remains explicitly OP04, not silently applied');
});
test('BR24 BR25 native paid waitlist active exit and T24 expiry reserve F D in full independent of voluntary time tiers',async()=>{
 for(const mode of ['EXIT','T24']){const f=await fixture();for(let i=0;i<4;i++)await pay(await registration(f,'FORMAL'));const r=await registration(f,'WAITLIST');await pay(r);if(mode==='EXIT')await domain.acceptCancellation(atClock(db,new Date(f.activity.startsAt.getTime()-25*H)),r.actor,r.reg.id,prefix+sequence++);else await domain.recoveryHandlers(db,channel).V11_T24(await leaseJob('V11_T24',f.activity.id));assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:r.reg.id}})).eligibilityState,'ENDED');assert.equal(await db.v11Membership.count({where:{registrationId:r.reg.id}}),0);const refund=await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:r.reg.id}});assert.equal(refund.serviceFeeCents,100);assert.equal(refund.depositCents,200);assert.equal(refund.totalCents,300);assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),1);}
});
test('BR61 native current INVALIDATED cancellation uses current unformed F D tier despite historical formation',async()=>{
 const f=await paidFixture(4);const removed=f.members[0],r=f.members[1];const at=new Date(f.activity.startsAt.getTime()-25*H);await db.$transaction(async tx=>domain.terminateAndRefund(tx,await domain.registrationLock(tx,removed.reg.id),prefix+sequence++,'CORE_CHANGE_REJECTED',at));const table=(await domain.registrationDetail(db,r.actor,r.reg.id));assert.equal(table.tableState,'INVALIDATED');assert.equal(table.address,null);assert.ok(table.restaurantName);const request=await domain.acceptCancellation(atClock(db,new Date(f.activity.startsAt.getTime()-24*H)),r.actor,r.reg.id,prefix+sequence++);assert.equal(request.payload.tableState,'INVALIDATED');assert.deepEqual([request.payload.decision.effect.refundF,request.payload.decision.effect.refundD],[100,200]);assert.equal(request.payload.decision.effect.depositDisposition,'REFUND');
});
