import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}
const {aftersalesRoute}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/aftersales.js`));
for(const obligation of ['HELD_D','REFUND_UNKNOWN','DISPUTE_AND_SETTLEMENT'])test(`BR56 PRE036: native closure retains inactive registration ${obligation} obligations and preserves original money facts`,async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');const paid=await pay(r);await db.v11Registration.update({where:{id:r.reg.id},data:{active:false,eligibilityState:'ENDED'}});const binding=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:r.reg.id}});const component=await db.v11FundComponent.findUniqueOrThrow({where:{receiptId_kind:{receiptId:binding.receiptId,kind:'D'}}});if(obligation==='REFUND_UNKNOWN'){const instruction=await db.$transaction(async tx=>domain.reserveRefund(tx,await domain.registrationLock(tx,r.reg.id),binding.receiptId,{F:0,D:200},prefix+sequence++));await db.v11RefundInstruction.update({where:{id:instruction.id},data:{state:'UNKNOWN'}});}if(obligation==='DISPUTE_AND_SETTLEMENT'){const request=await db.$transaction(tx=>domain.requestRecord(tx,{businessKey:prefix+sequence++,kind:'DISPUTE',userId:r.reg.userId,registrationId:r.reg.id,payload:{scope:'SIMULATION_ONLY',latestDecision:'BREACH',finalReviewUsed:true},state:'FINAL_REVIEW_PENDING'}));await db.v11SettlementObligation.create({data:{registrationId:r.reg.id,componentId:component.id,businessKey:prefix+sequence++,amountCents:200,state:'BLOCKED_POLICY',sourceRef:request.id}});}
 const ops={id:prefix+sequence++,personId:prefix+sequence++,role:'OPS',userId:null,restaurantId:null,version:0};const right=await aftersalesRoute(db,r.actor,'createRight',{body:{kind:'CLOSURE',businessKey:prefix+sequence++}});const result=await aftersalesRoute(db,ops,'processRight',{id:right.request.id});assert.equal(result.request.state,'OBLIGATIONS_PENDING');const row=await db.v11Request.findUniqueOrThrow({where:{id:right.request.id}});assert.equal(row.payload.obligations.activeRegistrations,0);if(obligation==='HELD_D')assert.equal(row.payload.obligations.heldDepositCents,200);if(obligation==='REFUND_UNKNOWN'){assert.equal(row.payload.obligations.unresolvedRefunds,1);assert.equal(row.payload.obligations.heldDepositCents,200)};if(obligation==='DISPUTE_AND_SETTLEMENT'){assert.equal(row.payload.obligations.unresolvedDisputes,1);assert.equal(row.payload.obligations.unresolvedSettlements,1);}assert.ok(row.blockerIds.includes('OP-15'));assert.ok(await db.user.findUnique({where:{id:r.reg.userId}}));assert.ok(await db.channelReceipt.findUnique({where:{id:binding.receiptId}}));assert.equal(await db.v11FundComponent.count({where:{receiptId:binding.receiptId}}),2);assert.equal((await db.v11PaymentIntent.findUniqueOrThrow({where:{id:paid.intent.id}})).state,'CONFIRMED');
});
test('BR56 closure: completed channel D refund and retained F are not misreported as unfinished deposit but OP15 deletion stays blocked',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');const paid=await pay(r);await db.v11Registration.update({where:{id:r.reg.id},data:{active:false,eligibilityState:'ENDED'}});const binding=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:r.reg.id}});const instruction=await db.$transaction(async tx=>domain.reserveRefund(tx,await domain.registrationLock(tx,r.reg.id),binding.receiptId,{F:0,D:200},prefix+sequence++));const fact=await channel.refund(instruction.merchantRefundNo,paid.fact.channelNo,200);await domain.persistMockEvent(db,{kind:'REFUND',sourceId:instruction.id,channelNo:fact.channelNo,amountCents:200,originalTradeNo:paid.fact.channelNo});const ops={id:prefix+sequence++,personId:prefix+sequence++,role:'OPS',userId:null,restaurantId:null,version:0};const right=await aftersalesRoute(db,r.actor,'createRight',{body:{kind:'CLOSURE',businessKey:prefix+sequence++}});const result=await aftersalesRoute(db,ops,'processRight',{id:right.request.id});assert.equal(result.request.state,'BLOCKED_POLICY');const row=await db.v11Request.findUniqueOrThrow({where:{id:right.request.id}});assert.equal(row.payload.obligations.heldDepositCents,0);assert.equal(row.payload.obligations.unresolvedRefunds,0);assert.ok(row.blockerIds.includes('OP-15'));assert.ok(await db.user.findUnique({where:{id:r.reg.userId}}));assert.equal((await db.v11FundComponent.findUniqueOrThrow({where:{receiptId_kind:{receiptId:binding.receiptId,kind:'F'}}})).originalCents,100);
});
