import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
function gate(){let resolve;const promise=new Promise(r=>{resolve=r});return{promise,resolve};}
// Barrier signals the second client reaching the real PostgreSQL activity row lock,
// while the first transaction retains that lock. No sleeps or client time decide order.
async function orderedRace(activityId,first,second){const db2=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});const started=gate();let secondPromise,finished=false;try{await verifyOwnedDatabase(db2,process.env);const waiting=new Proxy(db2,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field==='$queryRaw')return(...args)=>{if(Array.isArray(args[0])&&args[0].join(' ').includes('FROM "Activity"'))started.resolve();return inner.$queryRaw(...args)};const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});const a=await db.$transaction(async tx=>{await domain.activityLock(tx,activityId);secondPromise=second(waiting).then(v=>{finished=true;return v});await started.promise;assert.equal(finished,false,'Second effect waits for the real held row lock');const owned=new Proxy(db,{get(target,key){if(key==='$transaction')return callback=>callback(tx);const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});const result=await first(owned);assert.equal(finished,false,'Second effect cannot pass before first commits');return result});const b=await secondPromise;return{a,b};}finally{if(secondPromise)await secondPromise.catch(()=>{});await db2.$disconnect();}}
async function expire(dbClient,f,at){return dbClient.$transaction(async tx=>{await domain.activityLock(tx,f.activity.id);return domain.expireHolds(tx,f.activity.id,at)});}
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}
const {aftersalesRoute,aftersalesHandlers}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/aftersales.js`));
function atClock(dbClient,at){return new Proxy(dbClient,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field==='$queryRaw')return(...args)=>Array.isArray(args[0])&&args[0].join(' ').trim()==='SELECT clock_timestamp() AS at'?Promise.resolve([{at}]):inner.$queryRaw(...args);const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});}
async function firstBreach(){const f=await fixture();const r=await registration(f,'FORMAL');await pay(r);const now=await db.$transaction(domain.dbNow);await db.activity.update({where:{id:f.activity.id},data:{startsAt:new Date(now.getTime()-3*3600_000),endsAt:new Date(now.getTime()-3600_000)}});const rest=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'RESTAURANT',restaurantId:f.activity.restaurantId,passwordHash:'synthetic-unused-direct-test'}});const ops=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'OPS',passwordHash:'synthetic-unused-direct-test'}});await aftersalesRoute(db,rest,'fulfillment',{body:{registrationId:r.reg.id,result:'ABNORMAL'}});let request=await db.v11Request.findUniqueOrThrow({where:{businessKey:'dispute:'+r.reg.id}});const notice=await db.v11DeliveryProof.findFirstOrThrow({where:{requestId:request.id,kind:'ABNORMAL_NOTICE'}});await aftersalesRoute(db,r.actor,'receiveNotice',{id:notice.id});await aftersalesRoute(db,r.actor,'explanation',{id:request.id,body:{businessKey:prefix+sequence++,statement:'合成说明'}});await aftersalesRoute(db,ops,'decision',{id:request.id,body:{decision:'BREACH',reason:'合成首次处理'}});const result=await db.v11DeliveryProof.findFirstOrThrow({where:{requestId:request.id,kind:'FIRST_RESULT'}});await aftersalesRoute(db,r.actor,'receiveNotice',{id:result.id});request=await db.v11Request.findUniqueOrThrow({where:{id:request.id}});const deadline=new Date(Date.parse(request.payload.resultDeliveredAt)+48*3600_000);const job=await leaseJob('V11_DISPUTE_EXPIRE',request.id);return{f,r,request,deadline,job};}
for(const order of ['REVIEW_FIRST','EXPIRY_FIRST'])test(`PRE031: native ${order} row-lock barrier serializes final review against 48-hour settlement without actual transfer`,async()=>{
 const f=await firstBreach();const key=prefix+sequence++;const expiryAt=new Date(f.deadline.getTime()+1);const review=dbClient=>aftersalesRoute(atClock(dbClient,order==='REVIEW_FIRST'?f.deadline:expiryAt),f.r.actor,'review',{id:f.request.id,body:{businessKey:key,statement:'合成最终复核'}});const expiry=dbClient=>aftersalesHandlers(atClock(dbClient,expiryAt)).V11_DISPUTE_EXPIRE(f.job);await orderedRace(f.f.activity.id,order==='REVIEW_FIRST'?review:expiry,order==='REVIEW_FIRST'?expiry:review);const request=await db.v11Request.findUniqueOrThrow({where:{id:f.request.id}});const application=await db.v11Request.findUniqueOrThrow({where:{businessKey:'review:'+key}});const obligations=await db.v11SettlementObligation.findMany({where:{sourceRef:f.request.id}});if(order==='REVIEW_FIRST'){assert.equal(request.state,'FINAL_REVIEW_PENDING');assert.equal(request.payload.finalReviewUsed,true);assert.equal(application.acceptedAt.getTime(),f.deadline.getTime());assert.equal(application.state,'ACCEPTED');assert.equal(obligations.length,0,'An accepted in-window review prevents settlement flow');}else{assert.equal(request.state,'SETTLEMENT_BLOCKED_POLICY');assert.equal(request.payload.finalReviewUsed,false);assert.equal(application.state,'LATE_APPLICATION_REQUIRES_REVIEW','A later application is retained for review, not dropped');assert.equal(obligations.length,1);assert.equal(obligations[0].amountCents,200);assert.equal(obligations[0].state,'BLOCKED_POLICY');assert.ok(request.blockerIds.includes('OP-14'));}assert.equal(await db.v11RefundInstruction.count({where:{registrationId:f.r.reg.id}}),0);assert.equal(await db.v11Disposition.count({where:{component:{receipt:{v11ReceiptBinding_receiptId:{is:{registrationId:f.r.reg.id}}}}}}),0);const binding=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:f.r.reg.id},include:{receipt:true}});assert.equal(await channelDb.mockChannelTransaction.count({where:{kind:'REFUND',originalTradeNo:binding.receipt.channelTradeNo}}),0);assert.equal(await db.v11Decision.count({where:{requestId:f.request.id}}),1);
});
