import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {coreChangeFixture} from './formal-core-change-test-fixture.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
const canonical=value=>JSON.stringify(normal(value));function normal(v){if(Array.isArray(v))return v.map(normal);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,normal(v[k])]));return v;}
test('signed object-bound core change preserves original rights, own choices and original-channel F+D obligation',{timeout:90000},async()=>{
 const x=await coreChangeFixture();try{
  const {users,original,candidate,newSupply,url,body,approval,signoff,sign}=x;
  const blocked=await x.app.inject({method:'POST',url,headers:x.opsHeaders,payload:body});assert.equal(blocked.statusCode,503);
  x.f.grant.actions.push('CORE_CHANGE_PROPOSE');const unbound=await x.app.inject({method:'POST',url,headers:x.opsHeaders,payload:body});assert.equal(unbound.statusCode,503);
  sign();const specialist=x.f.grant.evidence.find(e=>e.responsibility==='CORE_CHANGE_PROFESSIONAL_SIGNOFF');x.f.grant.evidence=x.f.grant.evidence.filter(e=>e!==specialist);const missingSignoff=await x.app.inject({method:'POST',url,headers:x.opsHeaders,payload:body});assert.equal(missingSignoff.statusCode,503);x.f.grant.evidence.push(specialist);
  const digestBefore=approval.originalSnapshotDigest;approval.originalSnapshotDigest='a'.repeat(64);sign();const wrongOriginal=await x.app.inject({method:'POST',url,headers:x.opsHeaders,payload:body});assert.equal(wrongOriginal.statusCode,503);approval.originalSnapshotDigest=digestBefore;sign();
  const arbitrary=await x.app.inject({method:'POST',url,headers:x.opsHeaders,payload:{...body,startsAt:'2020-01-01T00:00:00Z'}});assert.equal(arbitrary.statusCode,400);
  const accepted=await x.request('POST',url,x.opsHeaders,body),repeat=await x.request('POST',url,x.opsHeaders,body);assert.equal(accepted.changeId,repeat.changeId);
  const swapped=await x.app.inject({method:'POST',url,headers:x.opsHeaders,payload:{...body,businessKey:x.prefix+'_wrong'}});assert.equal(swapped.statusCode,503);
  const disclosed=await x.request('GET','/api/v11/formal/registrations/'+users[0].registration.id+'/core-changes',users[0].headers);assert.equal(disclosed.changes[0].original.restaurantName,'合成正式餐厅');assert.equal(disclosed.changes[0].proposed.restaurantName,'合成候选江边餐厅');assert.equal(disclosed.changes[0].proposed.businessArea,'合成江边商圈');assert.equal(disclosed.changes[0].canAccept,true);const ownDetail=await x.request('GET','/api/v11/formal/registrations/'+users[0].registration.id,users[0].headers);assert.equal(ownDetail.registration.restaurantName,'合成正式餐厅');assert.equal(ownDetail.registration.address,null);assert.equal(JSON.stringify(disclosed).includes('address'),false);assert.equal(JSON.stringify(disclosed).includes('contact'),false);
  await x.db.restaurant.update({where:{id:x.restaurant.id},data:{name:'合成目录后来改名',businessArea:'合成目录后来改商圈'}});const frozen=await x.request('GET','/api/v11/formal/registrations/'+users[0].registration.id+'/core-changes',users[0].headers);assert.equal(frozen.changes[0].proposed.restaurantName,'合成候选江边餐厅');
  const choiceUrl='/api/v11/formal/core-changes/'+accepted.changeId+'/choices';
  const cross=await x.app.inject({method:'POST',url:choiceUrl,headers:users[1].headers,payload:{registrationId:users[0].registration.id,choice:'REJECT'}});assert.equal(cross.statusCode,404);
  const agree=await x.request('POST',choiceUrl,users[0].headers,{registrationId:users[0].registration.id,choice:'ACCEPT'});assert.equal(agree.applied,false);assert.equal(agree.membershipEnded,false);assert.equal((await x.db.v11Registration.findUniqueOrThrow({where:{id:users[0].registration.id}})).active,true);
  const rejectBody={registrationId:users[1].registration.id,choice:'REJECT'},both=await Promise.all([x.request('POST',choiceUrl,users[1].headers,rejectBody),x.request('POST',choiceUrl,users[1].headers,rejectBody)]);assert.equal(both[0].choiceId,both[1].choiceId);assert.equal(both[0].acceptedAt,both[1].acceptedAt);
  const reg=await x.db.v11Registration.findUniqueOrThrow({where:{id:users[1].registration.id}}),member=await x.db.v11Membership.findUniqueOrThrow({where:{registrationId:reg.id}});assert.equal(reg.active,false);assert.equal(member.active,false);assert.equal((await x.db.activity.findUniqueOrThrow({where:{id:x.activity.id}})).startsAt.toISOString(),x.activity.startsAt.toISOString());assert.notEqual((await x.db.activity.findUniqueOrThrow({where:{id:x.activity.id}})).status,'CANCELED');assert.equal((await x.db.v11SupplyRevision.findUniqueOrThrow({where:{id:original.id}})).digest,original.digest);
  const due=await x.db.v11Request.findFirstOrThrow({where:{registrationId:reg.id,kind:'FORMAL_MANDATORY_REFUND'}});assert.equal(due.payload.F,100);assert.equal(due.payload.D,200);assert.equal(due.payload.reason,'CORE_CHANGE_REJECTED');assert.equal(await x.db.v11RefundInstruction.count({where:{registrationId:reg.id}}),0);
  const rights=await x.db.auditLog.findFirstOrThrow({where:{action:'refund.v11-core-change-rights',targetId:due.id}});assert.equal(rights.metadata.tableState,'FORMED');assert.equal(rights.metadata.memberExitAt,member.leftAt.toISOString());
  const decided=await x.request('POST','/api/v11/ops/formal/refund-requests/'+due.id+'/decide',x.opsHeaders,{});assert.equal(decided.state,'WAITING_BATCH');const instruction=await x.db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:reg.id}});assert.equal(instruction.serviceFeeCents,100);assert.equal(instruction.depositCents,200);
  const conflict=await x.app.inject({method:'POST',url:choiceUrl,headers:users[1].headers,payload:{...rejectBody,choice:'ACCEPT'}});assert.equal(conflict.statusCode,409);
  const caseRow=await x.db.financialCase.findFirstOrThrow({where:{category:'V11_FORMAL_CORE_CHANGE_RESPONSE',sourceRef:agree.choiceId}});assert.equal(caseRow.owner,x.ops.id);
  const list=await x.request('GET','/api/v11/formal/registrations/'+reg.id+'/core-changes',users[1].headers);assert.equal(list.changes[0].choice,'REJECT');assert.equal(list.changes[0].original.restaurantName,null);assert.equal(list.changes[0].proposed.restaurantName,null);assert.equal(list.changes[0].deadline,null);assert.equal(list.changes[0].silenceAccepted,false);
  // A second untouched user's proof alteration must refuse the independent refund decision.
  await x.request('POST',choiceUrl,users[2].headers,{registrationId:users[2].registration.id,choice:'REJECT'});const bad=await x.db.v11Request.findFirstOrThrow({where:{registrationId:users[2].registration.id,kind:'FORMAL_MANDATORY_REFUND'}}),badAudit=await x.db.auditLog.findFirstOrThrow({where:{action:'refund.v11-core-change-rights',targetId:bad.id}});await x.db.auditLog.update({where:{id:badAudit.id},data:{metadata:{...badAudit.metadata,F:999}}});const rejected=await x.app.inject({method:'POST',url:'/api/v11/ops/formal/refund-requests/'+bad.id+'/decide',headers:x.opsHeaders,payload:{}});assert.equal(rejected.statusCode,409);assert.equal(await x.db.v11RefundInstruction.count({where:{registrationId:users[2].registration.id}}),0);
  const current=await x.db.v11CoreChange.findUniqueOrThrow({where:{id:accepted.changeId}});await x.db.v11CoreChange.update({where:{id:current.id},data:{proposedSnapshot:{...current.proposedSnapshot,restaurantName:'合成被篡改的餐厅'}}});const altered=await x.app.inject({method:'GET',url:'/api/v11/formal/registrations/'+users[0].registration.id+'/core-changes',headers:users[0].headers});assert.equal(altered.statusCode,409);assert.equal(altered.json().error.code,'CORE_CHANGE_FORMAL_PROVENANCE_REQUIRED');
 }finally{await x.close();}
});

test('unformed own member cannot accept an undisclosed restaurant change; terminal names remain hidden',{timeout:60000},async()=>{
 const x=await coreChangeFixture({memberCount:1});try{x.sign();const change=await x.request('POST',x.url,x.opsHeaders,x.body),u=x.users[0];const list=await x.request('GET','/api/v11/formal/registrations/'+u.registration.id+'/core-changes',u.headers);assert.equal(list.changes[0].original.restaurantName,null);assert.equal(list.changes[0].proposed.restaurantName,null);assert.equal(list.changes[0].proposed.businessArea,'合成江边商圈');assert.equal(list.changes[0].canAccept,false);const r=await x.app.inject({method:'POST',url:'/api/v11/formal/core-changes/'+change.changeId+'/choices',headers:u.headers,payload:{registrationId:u.registration.id,choice:'ACCEPT'}});assert.equal(r.statusCode,409);assert.equal(r.json().error.code,'CORE_CHANGE_RESTAURANT_DISCLOSURE_REQUIRED');assert.equal(await x.db.v11ChangeChoice.count({where:{changeId:change.changeId}}),0);assert.equal((await x.db.v11Registration.findUniqueOrThrow({where:{id:u.registration.id}})).active,true);
 }finally{await x.close();}
});

test('normal fulfillment intersection preserves retained F and D processing, persists review without accepting fullFD rejection',{timeout:60000},async()=>{
 const x=await coreChangeFixture({normalFulfillment:true});try{
  x.sign();const change=await x.request('POST',x.url,x.opsHeaders,x.body),u=x.users[0];
  const normal=await x.request('POST','/api/v11/restaurant/formal/registrations/'+u.registration.id+'/fulfillment',x.restHeaders,{result:'NORMAL'});await x.request('POST','/api/v11/ops/formal/refund-requests/'+normal.requestId+'/decide',x.opsHeaders,{});
  const before=await x.db.v11Disposition.findMany({where:{sourceRef:normal.requestId},orderBy:{id:'asc'}}),instructions=await x.db.v11RefundInstruction.findMany({where:{registrationId:u.registration.id},orderBy:{id:'asc'}});assert.ok(before.some(d=>d.kind==='RETAINED'&&d.amountCents===100));
  const body={registrationId:u.registration.id,choice:'REJECT'},url='/api/v11/formal/core-changes/'+change.changeId+'/choices',responses=await Promise.all([x.request('POST',url,u.headers,body),x.request('POST',url,u.headers,body)]);assert.equal(responses[0].pendingReview,true);assert.equal(responses[0].membershipEnded,false);assert.equal(responses[0].requestId,responses[1].requestId);assert.equal(responses[0].acceptedAt,responses[1].acceptedAt);
  assert.equal(await x.db.v11ChangeChoice.count({where:{changeId:change.changeId,registrationId:u.registration.id}}),0);assert.equal((await x.db.v11Registration.findUniqueOrThrow({where:{id:u.registration.id}})).active,true);assert.equal((await x.db.v11Membership.findUniqueOrThrow({where:{registrationId:u.registration.id}})).active,true);assert.equal(await x.db.v11Request.count({where:{registrationId:u.registration.id,kind:'FORMAL_MANDATORY_REFUND'}}),1);
  assert.deepEqual(await x.db.v11Disposition.findMany({where:{sourceRef:normal.requestId},orderBy:{id:'asc'}}),before);assert.deepEqual(await x.db.v11RefundInstruction.findMany({where:{registrationId:u.registration.id},orderBy:{id:'asc'}}),instructions);
  const review=await x.db.v11Request.findUniqueOrThrow({where:{id:responses[0].requestId}});assert.equal(review.kind,'CORE_CHANGE_REJECTION_REVIEW');assert.equal(review.payload.originalChangeAcceptedAt,(await x.db.v11CoreChange.findUniqueOrThrow({where:{id:change.changeId}})).acceptedAt.toISOString());assert.equal((await x.db.financialCase.findFirstOrThrow({where:{category:'V11_CORE_CHANGE_REJECTION_REVIEW',sourceRef:review.id}})).owner,x.ops.id);
  const listed=await x.request('GET','/api/v11/formal/registrations/'+u.registration.id+'/core-changes',u.headers);assert.equal(listed.changes[0].choice,null);assert.equal(listed.changes[0].pendingReview,true);assert.equal(listed.changes[0].reviewRequestId,review.id);let ops=await x.request('GET','/api/v11/ops/formal/core-changes',x.opsHeaders);while(!ops.changes.some(r=>r.id===change.changeId)&&ops.nextCursor)ops=await x.request('GET','/api/v11/ops/formal/core-changes?cursor='+ops.nextCursor,x.opsHeaders);const pending=ops.changes.find(r=>r.id===change.changeId).pendingReviews[0];assert.equal(pending.requestId,review.id);assert.equal(pending.caseOwner,x.ops.id);assert.equal(pending.acceptedAt,review.acceptedAt.toISOString());assert.equal(pending.originalChangeAcceptedAt,review.payload.originalChangeAcceptedAt);
 }finally{await x.close();}
});

test('owned pre-review branch reconstruction reproduces fullFD retained-F conflict; current refund gate preserves history',{timeout:60000},async()=>{
 const x=await coreChangeFixture({normalFulfillment:true});try{
  const {readFile}=await import('node:fs/promises'),url=new URL('../../services/api/dist/prelaunch/formal-core-change-service.js',import.meta.url),current=await readFile(url,'utf8');
  const start=current.indexOf("const attendance = choice === 'REJECT'"),end=current.indexOf('const selected =',start);assert.ok(start>=0&&end>start);
  // Explicit synthetic reconstruction of the reviewed pre-guard branch only.
  // This does not replace the current service or weaken its production test path.
  const {createRequire}=await import('node:module'),{pathToFileURL}=await import('node:url'),moduleRequire=createRequire(url);
  const historical=(current.slice(0,start)+current.slice(end)).replace(/from (['"])([^'"]+)\1/g,(_all,_quote,path)=>'from '+JSON.stringify(path.startsWith('node:')?path:path==='@timeleft-shanghai/shared'?new URL('../../packages/shared/dist/index.js',import.meta.url).href:path.startsWith('.')?new URL(path,url).href:pathToFileURL(moduleRequire.resolve(path)).href));
  const old=await import('data:text/javascript;base64,'+Buffer.from(historical).toString('base64'));
  x.sign();const change=await x.request('POST',x.url,x.opsHeaders,x.body),u=x.users[0];const normal=await x.request('POST','/api/v11/restaurant/formal/registrations/'+u.registration.id+'/fulfillment',x.restHeaders,{result:'NORMAL'});await x.request('POST','/api/v11/ops/formal/refund-requests/'+normal.requestId+'/decide',x.opsHeaders,{});
  const actor=await x.db.v11Actor.findFirstOrThrow({where:{userId:u.user.id,role:'USER'}}),accepted=await old.formalCoreChangeService(x.db,async()=>x.f.authority(),x.ops.id).respond(actor,change.changeId,u.registration.id,'REJECT');assert.equal(accepted.membershipEnded,true);
  const due=await x.db.v11Request.findFirstOrThrow({where:{registrationId:u.registration.id,kind:'FORMAL_MANDATORY_REFUND',payload:{path:['reason'],equals:'CORE_CHANGE_REJECTED'}}});
  const {reserveWechatRefundBudget,registrationLock}=await import('../../services/api/dist/prelaunch/domain.js');
  await assert.rejects(x.db.$transaction(async tx=>{const reg=await registrationLock(tx,u.registration.id),binding=await tx.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:reg.id,classification:'PRIMARY'},include:{intent:true}});return reserveWechatRefundBudget(tx,reg,binding.receiptId,{F:100,D:200},x.prefix+'_repro_conflict',binding.intent,new Date());}),e=>e.code==='COMPONENT_BUDGET_RESERVED');
  const before=await x.db.v11Disposition.findMany({where:{sourceRef:normal.requestId},orderBy:{id:'asc'}}),count=await x.db.v11RefundInstruction.count({where:{registrationId:u.registration.id}}),guard=await x.app.inject({method:'POST',url:'/api/v11/ops/formal/refund-requests/'+due.id+'/decide',headers:x.opsHeaders,payload:{}});assert.equal(guard.statusCode,409);assert.equal(guard.json().error.code,'FORMAL_CORE_CHANGE_AFTER_NORMAL_REVIEW_REQUIRED');assert.equal(await x.db.v11RefundInstruction.count({where:{registrationId:u.registration.id}}),count);assert.deepEqual(await x.db.v11Disposition.findMany({where:{sourceRef:normal.requestId},orderBy:{id:'asc'}}),before);
 }finally{await x.close();}
});
