import test from 'node:test';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {formalBusinessTestFixture} from './formal-business-test-fixture.mjs';import {root} from '../../scripts/prelaunch-owned-env.mjs';
const {acceptOwnRefundRequest}=await import(pathToFileURL((process.env.PRELAUNCH_SOURCE_ROOT??root)+'/services/api/dist/prelaunch/refund-request-intake.js'));
const url=u=>'/api/v11/formal/registrations/'+u.registration.id+'/refund-requests';
test('formal special root, supplement and appeal preserve original parent time and do not cancel, adjudicate or consume a review allowance',async()=>{
 const x=await formalBusinessTestFixture();try{const u=await x.user();await x.succeed(u);const submit=(category,key,parent)=>x.request('POST',url(u),u.headers,{businessKey:x.prefix+'_'+key,requestCategory:category,...(parent?{parentRequestId:parent}:{})});
  const original=await submit('SPECIAL_REFUND','special');assert.equal(original.linkageState,'ROOT');assert.equal(original.originalRequestId,original.requestId);assert.equal(original.originalAcceptedAt,original.acceptedAt);const saved=await x.db.v11Request.findUniqueOrThrow({where:{id:original.requestId}});
  const evidence=await submit('EVIDENCE','evidence',original.requestId),appeal=await submit('APPEAL','appeal',evidence.requestId);
  for(const r of [evidence,appeal]){assert.equal(r.linkageState,'LINKED');assert.equal(r.originalRequestId,original.requestId);assert.equal(r.originalAcceptedAt,original.acceptedAt);assert.ok(Date.parse(r.acceptedAt)>=Date.parse(original.acceptedAt));assert.equal(r.cancellationAccepted,false);assert.equal(r.refundApproved,false);assert.equal((await x.db.financialCase.findFirstOrThrow({where:{sourceRef:r.requestId,category:'V11_FORMAL_INQUIRY_REVIEW'}})).owner,x.ops.id);}
  const repeat=await submit('APPEAL','appeal',evidence.requestId);assert.equal(repeat.requestId,appeal.requestId);assert.equal(repeat.acceptedAt,appeal.acceptedAt);
  const after=await x.db.v11Request.findUniqueOrThrow({where:{id:original.requestId}});assert.equal(after.acceptedAt.toISOString(),saved.acceptedAt.toISOString());assert.deepEqual(after.payload,saved.payload);
  const member=await x.db.v11Membership.findUniqueOrThrow({where:{registrationId:u.registration.id}});assert.equal(member.active,true);assert.equal(await x.db.v11Decision.count({where:{requestId:{in:[original.requestId,evidence.requestId,appeal.requestId]}}}),0);assert.equal(await x.db.v11RefundInstruction.count({where:{registrationId:u.registration.id}}),0);
  const detail=await x.request('GET','/api/v11/formal/registrations/'+u.registration.id,u.headers);assert.equal(detail.registration.requests.find(r=>r.id===appeal.requestId).originalAcceptedAt,original.acceptedAt);
  let cursor=null,listed;do{const ops=await x.request('GET','/api/v11/ops/formal/refund-requests'+(cursor?'?cursor='+encodeURIComponent(cursor):''),x.opsHeaders);listed=ops.requests.find(r=>r.id===evidence.requestId);cursor=ops.nextCursor;}while(cursor&&!listed);assert.equal(listed?.parentRequestId,original.requestId);
  const blocked=await x.app.inject({method:'POST',url:'/api/v11/ops/formal/refund-requests/'+original.requestId+'/decide',headers:x.opsHeaders,payload:{}});assert.equal(blocked.statusCode,409);
 }finally{await x.close();}
});
test('unlinked legacy categories retain owner work; parent/category/ownership and client time or attachment injection fail closed',async()=>{
 const x=await formalBusinessTestFixture();try{const a=await x.user(),b=await x.user();await x.succeed(a);const submit=(u,category,key,parent)=>x.request('POST',url(u),u.headers,{businessKey:x.prefix+'_'+key,requestCategory:category,...(parent?{parentRequestId:parent}:{})});
  const unlinked=await submit(a,'EVIDENCE','unlinked');assert.equal(unlinked.state,'UNLINKED_AWAITING_REVIEW');assert.equal(unlinked.originalRequestId,null);assert.equal(unlinked.originalAcceptedAt,null);assert.equal((await x.db.financialCase.findFirstOrThrow({where:{sourceRef:unlinked.requestId}})).owner,x.ops.id);
  const rootA=await submit(a,'SPECIAL_REFUND','root'),rootB=await submit(b,'SPECIAL_REFUND','other');
  const sameUserOtherReg=await x.db.v11Registration.create({data:{...(await x.db.v11Registration.findUniqueOrThrow({where:{id:a.registration.id}})),id:x.prefix+'_other_registration',active:false,eligibilityState:'ENDED'}});const otherParent=await x.db.v11Request.create({data:{businessKey:x.prefix+'_different_reg_parent',kind:'FORMAL_REFUND_INQUIRY',source:'FORMAL_USER_INTAKE',registrationId:sameUserOtherReg.id,userId:a.user.id,acceptedAt:new Date(),blockerIds:[],payload:{requestCategory:'CONSULTATION'}}});
  for(const body of [{businessKey:x.prefix+'_foreign',requestCategory:'EVIDENCE',parentRequestId:rootB.requestId},{businessKey:x.prefix+'_different_reg',requestCategory:'EVIDENCE',parentRequestId:otherParent.id},{businessKey:x.prefix+'_unlinked_parent',requestCategory:'APPEAL',parentRequestId:unlinked.requestId},{businessKey:x.prefix+'_unlinked',requestCategory:'EVIDENCE',parentRequestId:rootA.requestId},{businessKey:x.prefix+'_root',requestCategory:'APPEAL'},{businessKey:x.prefix+'_manual_time',requestCategory:'SPECIAL_REFUND',originalAcceptedAt:'2020-01-01T00:00:00Z'},{businessKey:x.prefix+'_attachment',requestCategory:'EVIDENCE',attachment:'not accepted'}]){const r=await x.app.inject({method:'POST',url:url(a),headers:a.headers,payload:body});assert.ok([400,404,409].includes(r.statusCode),r.body);}
  assert.equal((await x.db.v11Membership.findUniqueOrThrow({where:{registrationId:a.registration.id}})).active,true);
  const actor=await x.db.v11Actor.findFirstOrThrow({where:{userId:a.user.id}}),before=await x.db.v11Request.count({where:{registrationId:a.registration.id}});
  await assert.rejects(acceptOwnRefundRequest(x.db,actor,a.registration.id,x.prefix+'_review_rollback',true,undefined,'SPECIAL_REFUND',async()=>{throw Error('injected owner queue failure');}),/owner queue failure/);assert.equal(await x.db.v11Request.count({where:{registrationId:a.registration.id}}),before);
 }finally{await x.close();}
});

test('formal core rejection review is an owned parent, while simulation and foreign parents remain denied',async()=>{const x=await formalBusinessTestFixture();try{const a=await x.user(),b=await x.user();const at=new Date();const parent=await x.db.v11Request.create({data:{businessKey:x.prefix+'_core_review',kind:'CORE_CHANGE_REJECTION_REVIEW',source:'FORMAL_USER_INTAKE',registrationId:a.registration.id,userId:a.user.id,acceptedAt:at,state:'AWAITING_FULFILLMENT_RIGHTS_REVIEW',blockerIds:['OP-09','RV-02'],payload:{scope:'FORMAL_CORE_CHANGE_FULFILLMENT_REVIEW'}}});const result=await x.request('POST',url(a),a.headers,{businessKey:x.prefix+'_supplement',requestCategory:'EVIDENCE',parentRequestId:parent.id});assert.equal(result.originalRequestId,parent.id);assert.equal(result.originalAcceptedAt,at.toISOString());assert.equal(result.cancellationAccepted,false);const detail=await x.request('GET','/api/v11/formal/registrations/'+a.registration.id,a.headers);assert.ok(detail.registration.requests.some(r=>r.id===parent.id&&r.kind==='CORE_CHANGE_REJECTION_REVIEW'));for(const [user,key]of [[b,'foreign'],[a,'simulation']]){let selectedParent=parent.id;if(key==='simulation'){const fake=await x.db.v11Request.create({data:{businessKey:x.prefix+'_simulation_parent',kind:'CORE_CHANGE_REJECTION_REVIEW',source:'SIMULATION',registrationId:a.registration.id,userId:a.user.id,acceptedAt:at,blockerIds:[],payload:{}}});selectedParent=fake.id;}const r=await x.app.inject({method:'POST',url:url(user),headers:user.headers,payload:{businessKey:x.prefix+'_'+key,requestCategory:'APPEAL',parentRequestId:selectedParent}});assert.equal(r.statusCode,404);}assert.equal(await x.db.v11Decision.count({where:{requestId:parent.id}}),0);}finally{await x.close();}});
