import test from 'node:test';import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';import {once} from 'node:events';import {dirname,resolve} from 'node:path';import {mkdirSync,writeFileSync} from 'node:fs';
import {root,verifyOwnedEnvironment,childEnvironment,registerOwnedApi,unregisterOwnedApi,redact} from '../../scripts/prelaunch-owned-env.mjs';
for(const normalIntersection of [false,true])test('formal responsibility cancellation actual main workspace HTTP/DOM normalIntersection='+normalIntersection,{timeout:120000},async()=>{
 const scratch=dirname(process.env.PRELAUNCH_ENV_FILE??''),{runtime}=await verifyOwnedEnvironment(scratch);
 const env={...childEnvironment(runtime),RESPONSIBILITY_NORMAL_INTERSECTION:String(normalIntersection),PRELAUNCH_SOURCE_ROOT:process.env.PRELAUNCH_SOURCE_ROOT??root};
 const server=spawn(process.execPath,[resolve(root,'tests/ui/formal-responsibility-http-server.mjs')],{cwd:root,env,stdio:['ignore','pipe','pipe','ipc']});let diagnostic='';server.stdout.on('data',()=>{});server.stderr.on('data',d=>diagnostic+=d);
 try{
  const ready=await new Promise((done,reject)=>{const timer=setTimeout(()=>reject(Error('Responsibility child ready timeout: '+redact(diagnostic,runtime))),30000);server.once('error',reject);server.once('exit',()=>reject(Error('Responsibility child exited before ready')));server.on('message',m=>{if(m?.type==='PRELAUNCH_READY'){clearTimeout(timer);done(m);}});});
  const origin=registerOwnedApi(scratch,server,ready),dir=resolve(root,'docs/prelaunch/run-to-production-20261002/responsibility-cancellation');mkdirSync(dir,{recursive:true});
  const command=['exec','vitest','run','--config','tests/ui/vitest.formal-responsibility-dom.config.mts','--configLoader','native','--no-cache'];let output='';
  const code=await new Promise((done,reject)=>{const child=spawn('pnpm',command,{cwd:root,env:{...env,RESPONSIBILITY_ORIGIN:origin,RESPONSIBILITY_ACTIVITY_ID:ready.activityId,RESPONSIBILITY_PASSWORD:ready.password,RESPONSIBILITY_OPS_USERNAME:ready.opsUsername,RESPONSIBILITY_RESTAURANT_USERNAME:ready.restaurantUsername},stdio:['ignore','pipe','pipe']});const timer=setTimeout(()=>child.kill('SIGKILL'),70000);child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);child.once('error',reject);child.once('exit',c=>{clearTimeout(timer);done(c);});});
  writeFileSync(resolve(dir,normalIntersection?'http-dom-normal-review.log':'http-dom.log'),redact(output+diagnostic,runtime).replaceAll(ready.password,'[SYNTHETIC_PASSWORD]'));assert.equal(code,0,'Responsibility HTTP DOM failed: '+resolve(dir,normalIntersection?'http-dom-normal-review.log':'http-dom.log'));
  const counts=await new Promise(done=>{server.on('message',m=>{if(m?.type==='COUNTS')done(m);});server.send({type:'COUNTS'});});
  if(normalIntersection){assert.notEqual(counts.activityState,'CANCELED');assert.equal(counts.activeMembers,4);assert.equal(counts.mandatoryDuties,1);assert.equal(counts.rightsSnapshots,0);assert.equal(counts.refundInstructions,1);assert.equal(counts.reviews,1);assert.equal(counts.beforeDigest,counts.afterDigest);}else{assert.equal(counts.activityState,'CANCELED');assert.equal(counts.activeMembers,0);assert.equal(counts.mandatoryDuties,4);assert.equal(counts.rightsSnapshots,4);assert.equal(counts.refundInstructions,0);}
  writeFileSync(resolve(dir,normalIntersection?'HTTP_DOM_NORMAL_REVIEW_RUN.json':'HTTP_DOM_RUN.json'),JSON.stringify({command:['pnpm',...command],exit_code:code,counts,scope:'ACTUAL_CONTROLLED_MAIN_COMPONENTS_AND_LOOPBACK_HTTP_WITH_SYNTHETIC_CHANNEL',realPlatformVerified:false,newMoneySubmitted:false},null,2)+'\n');
 }finally{if(server.exitCode===null&&server.signalCode===null){const stopped=once(server,'exit');server.kill('SIGTERM');await stopped;}unregisterOwnedApi(scratch,server.pid);}
});
