import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes,scryptSync,createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {dirname,resolve} from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {readFileSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {root as taskRoot,verifyOwnedEnvironment,childEnvironment,registerOwnedApi,unregisterOwnedApi,redact} from '../../scripts/prelaunch-owned-env.mjs';
import {captureCandidate} from '../../scripts/prelaunch-candidate-hash.mjs';
test('PRE040/041 joint proof: owned real HTTP plus React DOM remount/cache clear and notice-query failure', {timeout:120000}, async()=>{
 const repo=process.env.PRELAUNCH_SOURCE_ROOT;if(!repo)throw Error('Explicit owned source root required');const scratch=dirname(process.env.PRELAUNCH_ENV_FILE??'');const main=await verifyOwnedEnvironment(scratch),other=await verifyOwnedEnvironment(scratch,'channel');const candidate=captureCandidate(taskRoot);
 const require=createRequire(`${repo}/services/api/package.json`);const {PrismaPg}=require('@prisma/adapter-pg');const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
 const db=new PrismaClient({adapter:new PrismaPg({connectionString:main.runtime.database_url})});const prefix='ui_http_'+randomUUID().replaceAll('-','');const password=randomBytes(24).toString('hex'),salt=randomBytes(16);let server;
 try{
  const now=await db.$transaction(domain.dbNow);const restaurant=await db.restaurant.create({data:{name:'合成联合证据餐厅',district:'上海测试区',businessArea:'TEST_ONLY',address:'合成联合证据地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1000,cuisineTags:[],capacity:4}});
  const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成恢复旅程',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600000),endsAt:new Date(now.getTime()+74*3600000),registrationEndsAt:new Date(now.getTime()+64*3600000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
  const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix,bundleDigest:prefix,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:[]}});
  const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',estimatedMealMinCents:1000,estimatedMealMaxCents:2000,fixedFees:[]},digest:prefix,status:'SIMULATION_APPROVED'}});
  const user=await db.user.create({data:{wechatOpenid:prefix,phone:'synthetic-local'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});
  const actor=await db.v11Actor.create({data:{id:prefix+'_actor',personId:prefix+'_person',role:'USER',userId:user.id,passwordHash:`scrypt:${salt.toString('hex')}:${scryptSync(password,salt,64).toString('hex')}`}});
  const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:policy.id,...syntheticConsentHashes(),acceptedAt:now}});
  const registration=await domain.createRegistration(db,{...actor,role:'USER'},{activityId:activity.id,supplyId:supply.id,policyId:policy.id,consentId:consent.id,membership:'FORMAL',businessKey:prefix+'_registration'});assert.ok('eligibilityState'in registration);
  const notice=await db.v11DeliveryProof.create({data:{registrationId:registration.id,noticeKey:prefix+'_notice',kind:'TEST_RESTORE_NOTICE',state:'SENT',proofType:'SIMULATED'}});
  const env={...childEnvironment(main.runtime),PRELAUNCH_SOURCE_ROOT:repo,PRELAUNCH_HTTP_DOM_USER_ID:user.id};server=spawn(process.execPath,[resolve(repo,'tests/ui/http-dom-server.mjs')],{cwd:repo,env,stdio:['ignore','pipe','pipe','ipc']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});
  const ready=await new Promise((done,reject)=>{const timer=setTimeout(()=>reject(Error('Owned joint API timeout')),20000);server.once('error',reject);server.once('exit',()=>{clearTimeout(timer);reject(Error('Owned joint API exited before ready'));});server.on('message',m=>{if(m?.type==='PRELAUNCH_READY'){clearTimeout(timer);done(m);}});});const origin=registerOwnedApi(scratch,server,ready);
  const loginResponse=await fetch(origin+'/api/prelaunch/v11/auth/login',{method:'POST',headers:{'content-type':'application/json','x-fanju-contract':'prelaunch-v11-1'},body:JSON.stringify({actorId:actor.id,password})});assert.equal(loginResponse.status,200);const loggedIn=await loginResponse.json();const payResponse=await fetch(origin+`/api/prelaunch/v11/registrations/${registration.id}/pay`,{method:'POST',headers:{'content-type':'application/json','x-fanju-contract':'prelaunch-v11-1',authorization:'Bearer '+loggedIn.token},body:'{}'});assert.equal(payResponse.status,202); // Simulated prepayment accepted, no UI/native success and no worker payment dispatched.

  const dir=resolve(scratch,'http-dom-evidence',prefix);mkdirSync(dir,{recursive:true});const report=resolve(dir,'vitest.json');const log=resolve(dir,'vitest.log');let stdout='',stderr='';const started_at=new Date().toISOString();const command=['pnpm','exec','vitest','run','--config',resolve(repo,'tests/ui/vitest.http-dom.config.mts'),'--configLoader','native','--no-cache','--reporter=json',`--outputFile=${report}`];
  const status=await new Promise((done,reject)=>{const child=spawn(command[0],command.slice(1),{cwd:repo,env:{...env,PRELAUNCH_HTTP_DOM_ORIGIN:origin,PRELAUNCH_HTTP_DOM_ACTOR_ID:actor.id,PRELAUNCH_HTTP_DOM_PASSWORD:password,PRELAUNCH_HTTP_DOM_REGISTRATION_ID:registration.id},stdio:['ignore','pipe','pipe']});const timer=setTimeout(()=>child.kill('SIGKILL'),60000);child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);child.once('error',reject);child.once('exit',code=>{clearTimeout(timer);done(code);});});const clean=value=>redact(value,main.runtime).replaceAll(password,'[SYNTHETIC_CREDENTIAL_REDACTED]');stdout=clean(stdout);stderr=clean(stderr);writeFileSync(log,stdout+'\n'+stderr);
  const archive=resolve(taskRoot,'docs/prelaunch/evidence',`http-dom-${prefix}`);mkdirSync(archive,{recursive:true});const artifacts=[['vitest.stdout.log',stdout],['vitest.stderr.log',stderr]];if(existsSync(report))artifacts.push(['vitest.json',clean(readFileSync(report,'utf8'))]);
  const artifactPaths=[],artifactHashes={};for(const [name,contents]of artifacts){const target=resolve(archive,name);writeFileSync(target,contents);const relative=target.slice(taskRoot.length+1);artifactPaths.push(relative);artifactHashes[relative]=createHash('sha256').update(contents).digest('hex');}
  const native=existsSync(report)?JSON.parse(readFileSync(report,'utf8')):{success:false,numPassedTests:0,numFailedTests:1,numPendingTests:0,numTodoTests:0},after=captureCandidate(taskRoot).candidate_id;const record={id:prefix+'-owned-http-react-dom',category:'FINAL_CANDIDATE',candidate_id:candidate.candidate_id,source_snapshot_after:after,runner:'native',toolchain:{node:process.version,packageManager:JSON.parse(readFileSync(resolve(taskRoot,'package.json'),'utf8')).packageManager},command:JSON.stringify(command),cwd:repo,started_at,finished_at:new Date().toISOString(),exit_code:status,status:status===0&&native.success&&after===candidate.candidate_id?'PASS':'FAIL',source_drift_during_run:after!==candidate.candidate_id,passed:native.numPassedTests,failed:native.numFailedTests,skipped:native.numPendingTests,todo:native.numTodoTests,artifact_paths:artifactPaths,artifact_sha256:artifactHashes,stdout_sha256:artifactHashes[artifactPaths[0]],stderr_sha256:artifactHashes[artifactPaths[1]],counting_scope:'NESTED_DOM_PROOF_NOT_ADDITIVE_TO_PARENT_NODE_WRAPPER',counts_toward_final_total:false,scope:'Owned real HTTP with React DOM/native surface adapters; no native device or actual payment popup'};writeFileSync(resolve(archive,'RUNS.json'),JSON.stringify({candidate_id:candidate.candidate_id,runs:[record]},null,2)+'\n');
  assert.equal(after,candidate.candidate_id,'Source candidate drift during HTTP DOM proof');
  assert.equal(status,0,`Owned HTTP DOM suite failed; sanitized native log: ${log}`);const result=JSON.parse(readFileSync(report,'utf8'));assert.equal(result.success,true);assert.equal(result.numPassedTests,2);assert.equal(result.numPendingTests,0);
  assert.equal(await db.v11Registration.count({where:{userId:user.id,activityId:activity.id}}),1);assert.equal((await db.v11DeliveryProof.findUniqueOrThrow({where:{id:notice.id}})).receivedAt,null);assert.equal(await db.v11PaymentIntent.count({where:{registrationId:registration.id}}),1);assert.equal(await db.v11ReceiptBinding.count({where:{registrationId:registration.id}}),0);
  console.log(JSON.stringify({evidenceClass:'OWNED_HTTP_REACT_DOM',nativeTests:result.numPassedTests,scope:'Synthetic persisted order recovery and notice-list read failure; native device and payment popup not exercised',report,log}));
 }finally{if(server&&server.exitCode===null&&server.signalCode===null){const stopped=once(server,'exit');server.kill('SIGTERM');await stopped;}if(server)unregisterOwnedApi(scratch,server.pid);await db.$disconnect();}
});
