import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}

function atClock(dbClient,at){return new Proxy(dbClient,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field==='$queryRaw')return(...args)=>Array.isArray(args[0])&&args[0].join(' ').trim()==='SELECT clock_timestamp() AS at'?Promise.resolve([{at}]):inner.$queryRaw(...args);const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});}

const H=3600_000;
async function grow(f){await db.restaurant.update({where:{id:f.activity.restaurantId},data:{capacity:6}});f.supply=await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{targetSize:6,maxSize:6,capacity:6}});return f;}
test('BR17 BR21 native T24 uses minimum not target and failed table refunds all remaining F D without later revival',async()=>{
 for(const count of [5,3]){const f=await grow(await fixture());const rows=[];for(let i=0;i<count;i++){const r=await registration(f,'FORMAL');rows.push(r);await pay(r);}await domain.recoveryHandlers(db,channel).V11_T24(await leaseJob('V11_T24',f.activity.id));const table=await db.v11Table.findFirstOrThrow({where:{activityId:f.activity.id}});assert.equal(table.state,count===5?'FORMED':'FAILED');const snapshot=await db.v11TableEvent.findUniqueOrThrow({where:{businessKey:'t24:'+table.id}});assert.equal(snapshot.snapshot.count,count);assert.equal(snapshot.snapshot.formed,count===5);if(count===5){assert.equal(await db.v11RefundInstruction.count({where:{registration:{activityId:f.activity.id}}}),0);assert.equal(await db.v11Membership.count({where:{tableId:table.id,active:true}}),5);}else{for(const r of rows){const refund=await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:r.reg.id}});assert.deepEqual([refund.serviceFeeCents,refund.depositCents],[100,200]);assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:r.reg.id}})).active,false);}const next=await actor(f),at=new Date(f.activity.startsAt.getTime()-20*H);const request=await domain.createRegistration(atClock(db,at),next.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:next.consent.id,membership:'FORMAL',businessKey:prefix+sequence++});assert.equal(request.state,'BLOCKED_POLICY');assert.ok(request.blockerIds.includes('OP-05'));assert.equal(request.registrationId,null);assert.equal((await db.v11Table.findUniqueOrThrow({where:{id:table.id}})).state,'FAILED');assert.equal(await db.v11Membership.count({where:{tableId:table.id,active:true}}),0);}}
});
test('BR26 BR27 native T20 directly fills formed vacancy without reviving ended T24 waitlist or exceeding maximum',async()=>{
 const f=await grow(await fixture());const formal=[];for(let i=0;i<6;i++){const r=await registration(f,'FORMAL');formal.push(r);await pay(r);}const waiting=await registration(f,'WAITLIST');await pay(waiting);await domain.recoveryHandlers(db,channel).V11_T24(await leaseJob('V11_T24',f.activity.id));assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:waiting.reg.id}})).eligibilityState,'ENDED');const at=new Date(f.activity.startsAt.getTime()-20*H);await db.$transaction(async tx=>domain.terminateAndRefund(tx,await domain.registrationLock(tx,formal[5].reg.id),prefix+sequence++,'CORE_CHANGE_REJECTED',at));const newcomer=await actor(f);const reg=await domain.createRegistration(atClock(db,at),newcomer.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:newcomer.consent.id,membership:'FORMAL',businessKey:prefix+sequence++});assert.equal(reg.category,'LATE_FORMED');const intent=await domain.startPayment(atClock(db,at),newcomer.actor,reg.id);const fact=await channel.pay(intent.merchantOrderNo,300);await domain.persistMockEvent(atClock(db,at),{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:300});assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:reg.id}})).eligibilityState,'FORMAL');assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:waiting.reg.id}})).eligibilityState,'ENDED');assert.equal(await db.v11Membership.count({where:{active:true,registration:{activityId:f.activity.id}}}),6);const over=await actor(f);await assert.rejects(domain.createRegistration(atClock(db,at),over.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:over.consent.id,membership:'FORMAL',businessKey:prefix+sequence++}),e=>e.code==='FORMAL_CAPACITY_FULL');
});
test('PRE024 native exact T24 registration and complete payment preserve OP05 classification blocker without inventing qualification',async()=>{
 const f=await fixture(),exact=new Date(f.activity.startsAt.getTime()-24*H);const first=await actor(f);const request=await domain.createRegistration(atClock(db,exact),first.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:first.consent.id,membership:'FORMAL',businessKey:prefix+sequence++});assert.equal(request.state,'BLOCKED_POLICY');assert.ok(request.blockerIds.includes('OP-05'));assert.equal(request.registrationId,null);const user=await actor(f);const accepted=new Date(exact.getTime()-60_000);const reg=await domain.createRegistration(atClock(db,accepted),user.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:user.consent.id,membership:'FORMAL',businessKey:prefix+sequence++});const intent=await domain.startPayment(atClock(db,accepted),user.actor,reg.id);const fact=await channel.pay(intent.merchantOrderNo,300);await domain.persistMockEvent(atClock(db,exact),{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:300});assert.equal(await db.v11ReceiptBinding.count({where:{registrationId:reg.id}}),1);assert.equal(await db.v11Membership.count({where:{registrationId:reg.id}}),0);const blocker=await db.v11Request.findFirstOrThrow({where:{registrationId:reg.id,kind:'PAYMENT_QUALIFICATION'}});assert.ok(blocker.blockerIds.includes('OP-05'));assert.equal(await db.v11RefundInstruction.count({where:{registrationId:reg.id}}),0);
});
test('BR28 PRE015 native exact T8 closes new admissions while cross-cutoff payment blocks classification and expired late receipt refunds F D',async()=>{
 for(const delay of [5,10]){const f=await grow(await fixture());for(let i=0;i<4;i++)await pay(await registration(f,'FORMAL'));await domain.recoveryHandlers(db,channel).V11_T24(await leaseJob('V11_T24',f.activity.id));const exact=new Date(f.activity.startsAt.getTime()-8*H);const accepted=new Date(exact.getTime()-delay*60_000);const user=await actor(f);const reg=await domain.createRegistration(atClock(db,accepted),user.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:user.consent.id,membership:'FORMAL',businessKey:prefix+sequence++});const intent=await domain.startPayment(atClock(db,accepted),user.actor,reg.id);const fact=await channel.pay(intent.merchantOrderNo,300);await domain.persistMockEvent(atClock(db,exact),{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:300});assert.equal(await db.v11ReceiptBinding.count({where:{registrationId:reg.id}}),1);assert.equal(await db.v11Membership.count({where:{registrationId:reg.id}}),0);if(delay===10){assert.equal((await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:reg.id}})).totalCents,300);}else{assert.ok((await db.v11Request.findFirstOrThrow({where:{registrationId:reg.id,kind:'PAYMENT_QUALIFICATION'}})).blockerIds.includes('OP-05'));assert.equal(await db.v11RefundInstruction.count({where:{registrationId:reg.id}}),0);}const next=await actor(f);for(const membership of ['FORMAL','WAITLIST'])await assert.rejects(domain.createRegistration(atClock(db,exact),next.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:next.consent.id,membership,businessKey:prefix+sequence++}),e=>e.code==='REGISTRATION_CLOSED');assert.equal(await db.v11Membership.count({where:{active:true,registration:{activityId:f.activity.id}}}),4);}
});
test('BR60 native formed T24 then lawful T15 invalidation T8 preserves OP07 restaurant decision instead of auto-refunding others',async()=>{
 const f=await fixture(),members=[];for(let i=0;i<4;i++){const r=await registration(f,'FORMAL');members.push(r);await pay(r);}await domain.recoveryHandlers(db,channel).V11_T24(await leaseJob('V11_T24',f.activity.id));const table=await db.v11Table.findFirstOrThrow({where:{activityId:f.activity.id}});await db.$transaction(async tx=>domain.terminateAndRefund(tx,await domain.registrationLock(tx,members[0].reg.id),prefix+sequence++,'CORE_CHANGE_REJECTED',new Date(f.activity.startsAt.getTime()-15*H)));assert.equal((await db.v11Table.findUniqueOrThrow({where:{id:table.id}})).state,'INVALIDATED');await domain.recoveryHandlers(db,channel).V11_T8(await leaseJob('V11_T8',f.activity.id));const blocker=await db.v11Request.findFirstOrThrow({where:{kind:'LOW_PERSON_DECISION',payload:{path:['tableId'],equals:table.id}}});assert.ok(blocker.blockerIds.includes('OP-07'));assert.ok(blocker.blockerIds.includes('RV-03'));assert.equal((await db.v11Table.findUniqueOrThrow({where:{id:table.id}})).state,'INVALIDATED');for(const r of members.slice(1)){assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0);assert.equal((await db.v11Membership.findUniqueOrThrow({where:{registrationId:r.reg.id}})).active,true);}
});
