import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, scryptSync } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test('owned DB: released pending hold promotes earliest persistent ordinal, exit remains ended',async()=>{
 const f=await fixture();for(let i=0;i<3;i++)await pay(await registration(f,'FORMAL'));
 const held=await registration(f,'FORMAL');const first=await registration(f,'WAITLIST');await pay(first);const second=await registration(f,'WAITLIST');await pay(second);
 await db.v11SeatHold.update({where:{registrationId:held.reg.id},data:{expiresAt:new Date(Date.now()-1000)}});
 await db.$transaction(async tx=>{await domain.activityLock(tx,f.activity.id);await domain.expireHolds(tx,f.activity.id,await domain.dbNow(tx));});
 assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:first.reg.id}})).eligibilityState,'FORMAL');assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:second.reg.id}})).eligibilityState,'WAITLIST');
 await domain.acceptCancellation(db,second.actor,second.reg.id,prefix+sequence++);await db.$transaction(async tx=>domain.promoteWaitlist(tx,f.activity.id,await domain.dbNow(tx)));
 assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:second.reg.id}})).eligibilityState,'ENDED');assert.equal(await db.v11Membership.count({where:{active:true,registration:{activityId:f.activity.id}}}),4);
});
test('owned DB: unknown table state fails closed; cutoff prevents new promotion',async()=>{
 const f=await fixture();const waiting=await registration(f,'FORMAL');const now=await db.$transaction(domain.dbNow);await db.activity.update({where:{id:f.activity.id},data:{startsAt:new Date(now.getTime()+24*3600_000)}});
 await db.$transaction(async tx=>domain.promoteWaitlist(tx,f.activity.id,await domain.dbNow(tx)));assert.equal(await db.v11Membership.count({where:{registration:{activityId:f.activity.id}}}),0);
 const table=await db.v11Table.create({data:{activityId:f.activity.id,supplyId:f.supply.id,ordinal:1,state:'CORRUPTED_UNKNOWN'}});await assert.rejects(db.$transaction(async tx=>domain.refreshTable(tx,table.id,await domain.dbNow(tx))),e=>e.code==='UNKNOWN_TABLE_STATE');assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:waiting.reg.id}})).eligibilityState,'PENDING_PAYMENT');
});
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}
async function runT24(f){const lease=await leaseJob('V11_T24',f.activity.id);assert.equal(lease.refId,f.activity.id);await domain.recoveryHandlers(db,channel).V11_T24(lease);}
test('R2-01: T24 processing then pending waitlist success keeps receipt, ends eligibility and reserves full refund',async()=>{
 const f=await fixture();for(let i=0;i<3;i++)await pay(await registration(f,'FORMAL'));await registration(f,'FORMAL');const pending=await registration(f,'WAITLIST');const intent=await domain.startPayment(db,pending.actor,pending.reg.id);const now=await db.$transaction(domain.dbNow);await db.activity.update({where:{id:f.activity.id},data:{startsAt:new Date(now.getTime()+24*3600_000-1)}});await runT24(f);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});
 const reg=await db.v11Registration.findUniqueOrThrow({where:{id:pending.reg.id}});assert.equal(reg.eligibilityState,'ENDED');assert.equal(reg.active,false);assert.equal(await db.v11Membership.count({where:{registrationId:reg.id}}),0);const refund=await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:reg.id}});assert.equal(refund.serviceFeeCents,100);assert.equal(refund.depositCents,200);
});
test('R2-02: delayed T24 reconstructs leftAt history without replacing current INVALIDATED state',async()=>{
 const f=await fixture();const members=[];for(let i=0;i<4;i++)members.push(await registration(f,'FORMAL'));for(const r of members)await pay(r);const now=await db.$transaction(domain.dbNow);const cutoff=new Date(now.getTime()-2*3600_000);await db.activity.update({where:{id:f.activity.id},data:{startsAt:new Date(cutoff.getTime()+24*3600_000)}});const table=await db.v11Table.findFirstOrThrow({where:{activityId:f.activity.id}});await db.v11Membership.updateMany({where:{tableId:table.id},data:{joinedAt:new Date(cutoff.getTime()-3600_000)}});await db.v11Membership.update({where:{registrationId:members[0].reg.id},data:{active:false,leftAt:new Date(cutoff.getTime()+3600_000)}});await db.v11Table.update({where:{id:table.id},data:{state:'INVALIDATED'}});await runT24(f);const current=await db.v11Table.findUniqueOrThrow({where:{id:table.id}});assert.equal(current.t24FormedAt.toISOString(),cutoff.toISOString());assert.equal(current.state,'INVALIDATED');const snapshot=await db.v11TableEvent.findUniqueOrThrow({where:{businessKey:`t24:${table.id}`}});assert.equal(snapshot.snapshot.count,4);
});
test('R2-03: expired generation cannot pass locked lease fencing or write a business effect',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');const lease=await leaseJob('V11_EXPIRE_HOLD',r.reg.id);await db.durableJob.update({where:{id:lease.id},data:{leaseUntil:new Date((await db.$transaction(domain.dbNow)).getTime()-1)}});const newer=await ownClaim(await db.durableJob.findUniqueOrThrow({where:{id:lease.id}}));assert.ok(newer);assert.equal(newer.id,lease.id);assert.ok(newer.generation>lease.generation);await assert.rejects(domain.recoveryHandlers(db,channel).V11_EXPIRE_HOLD(lease),e=>e.code==='STALE_WORKER_LEASE');assert.equal((await db.v11SeatHold.findUniqueOrThrow({where:{registrationId:r.reg.id}})).state,'HELD');
});
test('R2-04: cancel commit before old PAY job dispatch creates only CLOSED merchant fact, no collection',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');const intent=await domain.startPayment(db,r.actor,r.reg.id);await domain.acceptCancellation(db,r.actor,r.reg.id,prefix+sequence++);const job=await db.durableJob.findUniqueOrThrow({where:{businessKey:`v11:pay:${intent.id}`}});const own=await ownClaim(job);await domain.recoveryHandlers(db,channel).V11_PAY(own);const fact=await channel.query('PAYMENT',intent.merchantOrderNo);assert.equal(fact.status,'CLOSED');assert.equal(await db.channelReceipt.count({where:{merchantOrderNo:intent.merchantOrderNo}}),0);
});
test('R2-05: successful event acceptance commits qualification at verifiedAt before ACK and replay is idempotent',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);const event=await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});const reg=await db.v11Registration.findUniqueOrThrow({where:{id:r.reg.id}});assert.equal(event.state,'APPLIED');assert.equal(reg.eligibilityState,'FORMAL');assert.equal(reg.paidEffectiveAt.toISOString(),event.verifiedAt.toISOString());await domain.applyMockEvent(db,event.id);assert.equal(await db.v11Membership.count({where:{registrationId:r.reg.id}}),1);assert.equal(await db.channelReceipt.count({where:{merchantOrderNo:intent.merchantOrderNo}}),1);
});
test('R2-06: formal re-entry preserves and blocks a prior UNKNOWN payment after seat release',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');const intent=await domain.startPayment(db,r.actor,r.reg.id);await db.v11PaymentIntent.update({where:{id:intent.id},data:{state:'UNKNOWN'}});await db.v11Registration.update({where:{id:r.reg.id},data:{active:false,eligibilityState:'ENDED'}});await db.v11SeatHold.update({where:{registrationId:r.reg.id},data:{state:'RELEASED'}});const result=await domain.createRegistration(db,r.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:r.reg.consentId,membership:'FORMAL',businessKey:prefix+sequence++});assert.equal(result.state,'BLOCKED_POLICY');assert.ok(result.blockerIds.includes('OP-08'));assert.equal(await db.v11Registration.count({where:{userId:r.actor.userId,activityId:f.activity.id}}),1);assert.equal((await db.v11PaymentIntent.findUniqueOrThrow({where:{id:intent.id}})).state,'UNKNOWN');
});
test('R2-07: cancellation with another businessKey returns original acceptedAt and table decision',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');await pay(r);const first=await domain.acceptCancellation(db,r.actor,r.reg.id,prefix+sequence++);const now=await db.$transaction(domain.dbNow);await db.activity.update({where:{id:f.activity.id},data:{startsAt:new Date(now.getTime()+20*3600_000)}});const second=await domain.acceptCancellation(db,r.actor,r.reg.id,prefix+sequence++);assert.equal(second.id,first.id);assert.equal(second.acceptedAt.toISOString(),first.acceptedAt.toISOString());assert.deepEqual(second.payload,first.payload);assert.equal(await db.v11Request.count({where:{registrationId:r.reg.id,kind:'CANCELLATION'}}),1);
});
test('R2-08: corrupted table state cannot create refund entitlement or erase membership',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');await pay(r);const member=await db.v11Membership.findUniqueOrThrow({where:{registrationId:r.reg.id}});await db.v11Table.update({where:{id:member.tableId},data:{state:'UNRECOGNIZED'}});await assert.rejects(domain.acceptCancellation(db,r.actor,r.reg.id,prefix+sequence++),e=>e.code==='UNKNOWN_TABLE_STATE');assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0);assert.equal((await db.v11Membership.findUniqueOrThrow({where:{id:member.id}})).active,true);
});
test('R2-09: frozen source valid but stored snapshot corrupted is refused without rewriting history',async()=>{
 const {importFrozenPolicy}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/policy.js`));const policy=await importFrozenPolicy(db,repo);const original=policy.docsJson;await db.v11PolicySnapshot.update({where:{id:policy.id},data:{docsJson:{scope:'FROZEN_DRAFT',documents:[]}}});try{await assert.rejects(importFrozenPolicy(db,repo),e=>e.code==='STORED_POLICY_INTEGRITY_INVALID');assert.deepEqual((await db.v11PolicySnapshot.findUniqueOrThrow({where:{id:policy.id}})).docsJson,{scope:'FROZEN_DRAFT',documents:[]});}finally{await db.v11PolicySnapshot.update({where:{id:policy.id},data:{docsJson:original}});}
});
test('component summary and financial case: D refund then F complement conserve budgets; unknown case cannot close',async()=>{
 const {fundingBuckets,claimFinancialCase,resolveFinancialCase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/finance.js`));
 const before=await fundingBuckets(db);const f=await fixture();const r=await registration(f,'FORMAL');const paid=await pay(r);const primary=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:r.reg.id}});const after=await fundingBuckets(db);assert.equal(after.components.F.original-before.components.F.original,100);assert.equal(after.components.D.original-before.components.D.original,200);
 const instruction=await db.$transaction(async tx=>{const reg=await domain.registrationLock(tx,r.reg.id);return domain.reserveRefund(tx,reg,primary.receiptId,{F:0,D:200},prefix+sequence++);});assert.ok(instruction);const reserved=await fundingBuckets(db);assert.equal(reserved.components.D.refundReserved-after.components.D.refundReserved,200);
 const fact=await channel.refund(instruction.merchantRefundNo,paid.fact.channelNo,200);await domain.persistMockEvent(db,{kind:'REFUND',sourceId:instruction.id,channelNo:fact.channelNo,amountCents:fact.amountCents,originalTradeNo:paid.fact.channelNo});const finished=await fundingBuckets(db);assert.equal(finished.components.D.refunded-after.components.D.refunded,200);
 const complement=await db.$transaction(async tx=>{const reg=await domain.registrationLock(tx,r.reg.id);return domain.reserveRefund(tx,reg,primary.receiptId,{F:100,D:200},prefix+sequence++);});assert.ok(complement);assert.equal(complement.serviceFeeCents,100);assert.equal(complement.depositCents,0);
 const actor={id:prefix+sequence++,personId:prefix+sequence++,role:'OPS',userId:null,restaurantId:null,version:0};const known=await db.financialCase.create({data:{caseKey:prefix+sequence++,category:'V11_REFUND_CONFLICT',sourceRef:instruction.id,owner:'local-simulation-ops',deadline:new Date(Date.now()+1000)}});await claimFinancialCase(db,actor,known.id);const resolved=await resolveFinancialCase(db,channelDb,actor,known.id,'合成渠道已确认且预算守恒');assert.equal(resolved.state,'RESOLVED');
 const unknown=await db.financialCase.create({data:{caseKey:prefix+sequence++,category:'UNKNOWN_NEW_CATEGORY',sourceRef:prefix,owner:actor.id,deadline:new Date(Date.now()+1000)}});await assert.rejects(resolveFinancialCase(db,channelDb,actor,unknown.id,'不可凭文字关闭'),e=>e.code==='CASE_REQUIRES_SPECIALIST_REVIEW');assert.equal((await db.financialCase.findUniqueOrThrow({where:{id:unknown.id}})).state,'OPEN');
});
test('native API: immutable supply revision, scoped history, queue and financial-case role checks',async()=>{
 const {buildPrelaunchApp}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/routes.js`));const {scryptSync,randomBytes}=await import('node:crypto');const password=`synthetic-${randomUUID()}`;const salt=randomBytes(16);const passwordHash=`scrypt:${salt.toString('hex')}:${scryptSync(password,salt,64).toString('hex')}`;
 const ops=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'OPS',passwordHash}});const outsider=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'RESTAURANT',passwordHash}});const f=await fixture();const app=await buildPrelaunchApp(db,process.env,repo,channelDb);
 try{const login=await app.inject({method:'POST',url:'/api/prelaunch/v11/auth/login',headers:{'x-fanju-contract':'prelaunch-v11-1'},payload:{actorId:ops.id,password}});assert.equal(login.statusCode,200);const headers={authorization:`Bearer ${login.json().token}`,'x-fanju-contract':'prelaunch-v11-1'};const bad=await app.inject({method:'GET',url:'/api/prelaunch/v11/ops/supplies/'+f.supply.id,headers:{...headers,'x-fanju-contract':'legacy'}});assert.equal(bad.statusCode,409);
 const detail=await app.inject({method:'GET',url:'/api/prelaunch/v11/ops/supplies/'+f.supply.id,headers});assert.equal(detail.statusCode,200);assert.equal(detail.json().supply.id,f.supply.id);assert.equal(detail.json().immutableRevision,true);
 const change={min:4,target:4,max:4,maxTables:1,capacity:4,F:101,D:200,WAITLIST_MAX:4,strategy:'FILL_TO_MAX',estimatedMealMinCents:1000,estimatedMealMaxCents:2000,fixedFees:[]};const edited=await app.inject({method:'POST',url:'/api/prelaunch/v11/ops/supplies/'+f.supply.id+'/revision',headers,payload:change});assert.equal(edited.statusCode,200);assert.equal(edited.json().supply.status,'DRAFT');assert.equal(edited.json().existingOrdersChanged,false);assert.equal((await db.v11SupplyRevision.findUniqueOrThrow({where:{id:f.supply.id}})).serviceFeeCents,100);
 const history=await app.inject({method:'GET',url:'/api/prelaunch/v11/ops/supplies/'+f.supply.id+'/history?limit=1',headers});assert.equal(history.statusCode,200);assert.equal(history.json().history.length,1);assert.ok(history.json().nextCursor);
 const outsiderLogin=await app.inject({method:'POST',url:'/api/prelaunch/v11/auth/login',headers:{'x-fanju-contract':'prelaunch-v11-1'},payload:{actorId:outsider.id,password}});const outsiderHeaders={authorization:`Bearer ${outsiderLogin.json().token}`};const denied=await app.inject({method:'GET',url:'/api/prelaunch/v11/restaurant/supplies/'+f.supply.id,headers:outsiderHeaders});assert.equal(denied.statusCode,404);const queueDenied=await app.inject({method:'GET',url:'/api/prelaunch/v11/ops/activities/'+f.activity.id+'/waitlist',headers:outsiderHeaders});assert.equal(queueDenied.statusCode,403);
 const summary=await app.inject({method:'GET',url:'/api/prelaunch/v11/ops/funding-summary',headers});assert.equal(summary.statusCode,200);assert.equal(summary.json().accountingRecognition,false);assert.ok(summary.json().components.F);assert.ok(summary.json().components.D);
 }finally{await app.close();}
});

test('PRE038: missing or wrong write contract refuses before business effects; GET and preflight remain available',async()=>{
 const f=await fixture();const {buildPrelaunchApp}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/routes.js`));
 const actor=await db.v11Actor.create({data:{id:prefix+'contract_ops_'+sequence++,role:'OPS',personId:prefix+'contract_person_'+sequence++,enabled:true,passwordHash:`scrypt:${Buffer.alloc(16,5).toString('hex')}:${scryptSync('controlled-test-password',Buffer.alloc(16,5),64).toString('hex')}`}});
 const app=await buildPrelaunchApp(db,{...process.env,PRELAUNCH_CORS_ORIGINS:'http://127.0.0.1:47123'},repo,channelDb);
 try{
  const loginBody={actorId:actor.id,password:'controlled-test-password'};
  const missingLogin=await app.inject({method:'POST',url:'/api/prelaunch/v11/auth/login',payload:loginBody});assert.equal(missingLogin.statusCode,409);assert.equal(missingLogin.json().error.code,'INCOMPATIBLE_VERSION');assert.equal(missingLogin.json().token,undefined);
  const login=await app.inject({method:'POST',url:'/api/prelaunch/v11/auth/login',headers:{'x-fanju-contract':'prelaunch-v11-1'},payload:loginBody});assert.equal(login.statusCode,200);
  const bearer={authorization:`Bearer ${login.json().token}`};const body={min:4,target:4,max:4,maxTables:1,capacity:4,F:101,D:200,WAITLIST_MAX:4,strategy:'FILL_TO_MAX',estimatedMealMinCents:1000,estimatedMealMaxCents:2000,fixedFees:[]};
  const before=await db.v11SupplyRevision.count({where:{activityId:f.activity.id}});const auditBefore=await db.auditLog.count({where:{metadata:{path:["actorId"],equals:actor.id}}});
  for(const header of [undefined,'legacy-v1']){const response=await app.inject({method:'POST',url:`/api/prelaunch/v11/ops/supplies/${f.supply.id}/revision`,headers:{...bearer,...(header?{'x-fanju-contract':header}:{})},payload:body});assert.equal(response.statusCode,409);assert.equal(response.json().error.code,'INCOMPATIBLE_VERSION');}
  assert.equal(await db.v11SupplyRevision.count({where:{activityId:f.activity.id}}),before);assert.equal(await db.auditLog.count({where:{metadata:{path:["actorId"],equals:actor.id}}}),auditBefore);
  const read=await app.inject({method:'GET',url:`/api/prelaunch/v11/ops/supplies/${f.supply.id}`,headers:bearer});assert.equal(read.statusCode,200);
  const options=await app.inject({method:'OPTIONS',url:'/api/prelaunch/v11/profile',headers:{origin:'http://127.0.0.1:47123','access-control-request-method':'PUT','access-control-request-headers':'x-fanju-contract,authorization,content-type'}});assert.equal(options.statusCode,204);assert.ok(options.headers['access-control-allow-methods'].includes('PUT'));
 }finally{await app.close();}
});
