import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}
const {aftersalesRoute}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/aftersales.js`));
async function restActor(f){return db.v11Actor.create({data:{personId:prefix+sequence++,role:'RESTAURANT',restaurantId:f.activity.restaurantId,passwordHash:'synthetic-unused-direct-test'}});}
test('PRE028 BR37: native scan alone records arrival without normal fulfillment D refund or breach',async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');await pay(r);const rest=await restActor(f);const code=await aftersalesRoute(db,rest,'checkinCode',{id:f.activity.id});const first=await aftersalesRoute(db,r.actor,'checkin',{body:{registrationId:r.reg.id,qrToken:code.qrToken}});const again=await aftersalesRoute(db,r.actor,'checkin',{body:{registrationId:r.reg.id,qrToken:code.qrToken}});assert.equal(new Date(first.attendance.checkinAt).getTime(),new Date(again.attendance.checkinAt).getTime());const attendance=await db.v11Attendance.findUniqueOrThrow({where:{registrationId:r.reg.id}});assert.ok(attendance.checkinAt);assert.equal(attendance.restaurantResult,null);assert.equal(attendance.confirmedAt,null);assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0);assert.equal(await db.v11Request.count({where:{registrationId:r.reg.id,kind:'DISPUTE'}}),0);const binding=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:r.reg.id},include:{receipt:true}});assert.equal(await channelDb.mockChannelTransaction.count({where:{kind:'REFUND',originalTradeNo:binding.receipt.channelTradeNo}}),0);
});
test('PRE029 RB05: native restaurant A cannot confirm restaurant B fulfillment or create attendance and money commands',async()=>{
 const a=await fixture(),b=await fixture();const ra=await restActor(a);const r=await registration(b,'FORMAL');await pay(r);const now=await db.$transaction(domain.dbNow);await db.activity.update({where:{id:b.activity.id},data:{endsAt:new Date(now.getTime()-1)}});for(const result of ['NORMAL','ABNORMAL'])await assert.rejects(aftersalesRoute(db,ra,'fulfillment',{body:{registrationId:r.reg.id,result}}),e=>e.statusCode===404);assert.equal(await db.v11Attendance.count({where:{registrationId:r.reg.id}}),0);assert.equal(await db.v11Request.count({where:{registrationId:r.reg.id,kind:'DISPUTE'}}),0);assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0);
});
test('DR07: native D below D_MIN and above D_MAX both reject approval without payment or mutating signed supply',async()=>{
 const {buildPrelaunchApp}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/routes.js`));const {scryptSync,randomBytes}=await import('node:crypto');const password=`synthetic-${randomUUID()}`,salt=randomBytes(16);const passwordHash=`scrypt:${salt.toString('hex')}:${scryptSync(password,salt,64).toString('hex')}`;const f=await fixture();const rest=await restActor(f);await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{status:'SIMULATION_SIGNED',personId:rest.personId,signedAt:await db.$transaction(domain.dbNow)}});const ops=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'OPS',passwordHash}});const app=await buildPrelaunchApp(db,process.env,repo,channelDb);try{const login=await app.inject({method:'POST',url:'/api/prelaunch/v11/auth/login',headers:{'x-fanju-contract':'prelaunch-v11-1'},payload:{actorId:ops.id,password}});assert.equal(login.statusCode,200);const headers={authorization:`Bearer ${login.json().token}`,'x-fanju-contract':'prelaunch-v11-1'};for(const bounds of [{D_MIN:201,D_MAX:500},{D_MIN:0,D_MAX:199}]){const response=await app.inject({method:'POST',url:'/api/prelaunch/v11/ops/supplies/'+f.supply.id+'/approve',headers,payload:{...bounds,simulationBatchHour:10}});assert.equal(response.statusCode,409);assert.equal(response.json().error.code,'SUPPLY_APPROVAL_REQUIRED');assert.equal((await db.v11SupplyRevision.findUniqueOrThrow({where:{id:f.supply.id}})).status,'SIMULATION_SIGNED');const who=await actor(f);await assert.rejects(domain.createRegistration(db,who.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:who.consent.id,membership:'FORMAL',businessKey:prefix+sequence++}),e=>e.code==='SUPPLY_NOT_APPROVED');}assert.equal(await db.v11Registration.count({where:{supplyId:f.supply.id}}),0);assert.equal(await db.v11PaymentIntent.count({where:{registration:{supplyId:f.supply.id}}}),0);}finally{await app.close();}
});
test('PRE023 BR18: native two tables formed and failed expose only own effective formed address and reject another users detail',async()=>{
 const f=await fixture();await db.restaurant.update({where:{id:f.activity.restaurantId},data:{capacity:8}});f.supply=await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{maxTables:2,capacity:8,strategy:'FILL_TO_TARGET'}});const members=[];for(let i=0;i<5;i++){const r=await registration(f,'FORMAL');members.push(r);await pay(r);}const job=await leaseJob('V11_T24',f.activity.id);await domain.recoveryHandlers(db,channel).V11_T24(job);const formed=await domain.registrationDetail(db,members[0].actor,members[0].reg.id);const failed=await domain.registrationDetail(db,members[4].actor,members[4].reg.id);assert.equal(formed.tableState,'FORMED');assert.ok(formed.restaurantName);assert.ok(formed.address);assert.equal(failed.tableState,'FAILED');assert.equal(failed.address,null);assert.equal(failed.state,'ENDED');assert.equal((await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:members[4].reg.id}})).totalCents,300);assert.equal(await db.v11RefundInstruction.count({where:{registrationId:members[0].reg.id}}),0);await assert.rejects(domain.registrationDetail(db,members[0].actor,members[4].reg.id),e=>e.statusCode===404&&e.code==='RESOURCE_NOT_FOUND');assert.equal(await db.v11Table.count({where:{activityId:f.activity.id}}),2);
});
test('PRE041: native failed notify retries only its outbox and preserves committed payment without inventing receivedAt',async()=>{
 const {retryJob,finishJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));const f=await fixture();const r=await registration(f,'FORMAL');const paid=await pay(r);const notice=await db.$transaction(tx=>domain.notify(tx,r.reg.id,'SYNTHETIC_PAYMENT_NOTICE',prefix+sequence++));const sibling=await db.$transaction(tx=>domain.notify(tx,r.reg.id,'SYNTHETIC_OTHER_NOTICE',prefix+sequence++));const siblingLease=await leaseJob('V11_NOTIFY',sibling.id);await domain.recoveryHandlers(db,channel).V11_NOTIFY(siblingLease);await finishJob(db,siblingLease);const lease=await leaseJob('V11_NOTIFY',notice.id);const faulty=new Proxy(db,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field==='v11DeliveryProof')return new Proxy(inner[field],{get(delegate,method){if(method==='updateMany')return async()=>{throw Error('synthetic-notification-failure')};const v=Reflect.get(delegate,method);return typeof v==='function'?v.bind(delegate):v}});const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});await assert.rejects(domain.recoveryHandlers(faulty,channel).V11_NOTIFY(lease),/synthetic-notification-failure/);await retryJob(db,lease,prefix,'SYNTHETIC_NOTIFY_FAILURE');const retry=await ownClaim(lease);await domain.recoveryHandlers(db,channel).V11_NOTIFY(retry);await finishJob(db,retry);for(const id of [notice.id,sibling.id]){const row=await db.v11DeliveryProof.findUniqueOrThrow({where:{id}});assert.equal(row.state,'SENT');assert.equal(row.receivedAt,null);}assert.equal((await db.v11PaymentIntent.findUniqueOrThrow({where:{id:paid.intent.id}})).state,'CONFIRMED');assert.equal(await db.v11ReceiptBinding.count({where:{intentId:paid.intent.id}}),1);assert.equal(await db.v11Membership.count({where:{registrationId:r.reg.id,active:true}}),1);assert.equal(await channelDb.mockChannelTransaction.count({where:{businessKey:'PAYMENT:'+paid.intent.merchantOrderNo}}),1);assert.equal((await db.durableJob.findUniqueOrThrow({where:{id:siblingLease.id}})).attempts,1);assert.equal((await db.durableJob.findUniqueOrThrow({where:{id:retry.id}})).attempts,2);
});
