import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
function gate(){let resolve;const promise=new Promise(r=>{resolve=r});return{promise,resolve};}
// Barrier signals the second client reaching the real PostgreSQL activity row lock,
// while the first transaction retains that lock. No sleeps or client time decide order.
async function orderedRace(activityId,first,second){const db2=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});const started=gate();let secondPromise,finished=false;try{await verifyOwnedDatabase(db2,process.env);const waiting=new Proxy(db2,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field==='$queryRaw')return(...args)=>{if(Array.isArray(args[0])&&args[0].join(' ').includes('FROM "Activity"'))started.resolve();return inner.$queryRaw(...args)};const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});const a=await db.$transaction(async tx=>{await domain.activityLock(tx,activityId);secondPromise=second(waiting).then(v=>{finished=true;return v});await started.promise;assert.equal(finished,false,'Second effect waits for the real held row lock');const owned=new Proxy(db,{get(target,key){if(key==='$transaction')return callback=>callback(tx);const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});const result=await first(owned);assert.equal(finished,false,'Second effect cannot pass before first commits');return result});const b=await secondPromise;return{a,b};}finally{if(secondPromise)await secondPromise.catch(()=>{});await db2.$disconnect();}}
async function expire(dbClient,f,at){return dbClient.$transaction(async tx=>{await domain.activityLock(tx,f.activity.id);return domain.expireHolds(tx,f.activity.id,at)});}
for(const order of ['EXIT_FIRST','PROMOTE_FIRST'])test(`PRE019: native ${order} row-lock barrier gives one waitlist outcome and preserves the correct cancellation category`,async()=>{
 const f=await fixture();for(let i=0;i<3;i++)await pay(await registration(f,'FORMAL'));const held=await registration(f,'FORMAL');const waiting=await registration(f,'WAITLIST');await pay(waiting);const hold=await db.v11SeatHold.findUniqueOrThrow({where:{registrationId:held.reg.id}});const key=prefix+sequence++;const exit=dbClient=>domain.acceptCancellation(dbClient,waiting.actor,waiting.reg.id,key);const promote=dbClient=>expire(dbClient,f,hold.expiresAt);const result=await orderedRace(f.activity.id,order==='EXIT_FIRST'?exit:promote,order==='EXIT_FIRST'?promote:exit);const current=await db.v11Registration.findUniqueOrThrow({where:{id:waiting.reg.id}});const request=order==='EXIT_FIRST'?result.a:result.b;
 if(order==='EXIT_FIRST'){assert.equal(current.eligibilityState,'ENDED');assert.equal(current.active,false);assert.equal(await db.v11Membership.count({where:{registrationId:waiting.reg.id}}),0);const refund=await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:waiting.reg.id}});assert.equal(refund.serviceFeeCents,100);assert.equal(refund.depositCents,200);assert.equal(request.payload.decision.effect.refundF,100);assert.equal(request.payload.decision.effect.refundD,200);}else{assert.equal(current.eligibilityState,'FORMAL');assert.equal(current.category,'ORDINARY');assert.equal((await db.v11Membership.findUniqueOrThrow({where:{registrationId:waiting.reg.id}})).active,true);assert.equal(request.payload.category,'ORDINARY');assert.ok(request.blockerIds.includes('OP-04'));assert.equal(await db.v11RefundInstruction.count({where:{registrationId:waiting.reg.id}}),0,'Unresolved formal self-removal does not reuse waitlist full-refund rights');}assert.equal(await db.v11Membership.count({where:{active:true,registration:{activityId:f.activity.id}}}),order==='EXIT_FIRST'?3:4);assert.equal(await db.v11ReceiptBinding.count({where:{registrationId:waiting.reg.id}}),1);
});
for(const order of ['EXPIRY_FIRST','SUCCESS_FIRST'])test(`PRE014: native ${order} row-lock barrier preserves exact ten-minute hold and one receipt without overselling`,async()=>{
 const f=await fixture();const r=await registration(f,'FORMAL');const hold=await db.v11SeatHold.findUniqueOrThrow({where:{registrationId:r.reg.id}});assert.equal(hold.expiresAt.getTime()-r.reg.acceptedAt.getTime(),600000);const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);const input={kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents};const success=dbClient=>domain.persistMockEvent(dbClient,input);const expiry=dbClient=>expire(dbClient,f,hold.expiresAt);await orderedRace(f.activity.id,order==='EXPIRY_FIRST'?expiry:success,order==='EXPIRY_FIRST'?success:expiry);const current=await db.v11Registration.findUniqueOrThrow({where:{id:r.reg.id}});assert.equal(await db.v11ReceiptBinding.count({where:{registrationId:r.reg.id}}),1);assert.equal(await db.channelReceipt.count({where:{channelTradeNo:fact.channelNo,amountCents:300}}),1);assert.equal((await db.v11PaymentIntent.findUniqueOrThrow({where:{id:intent.id}})).state,'CONFIRMED');if(order==='EXPIRY_FIRST'){assert.equal(current.eligibilityState,'EXPIRED');assert.equal(current.active,false);assert.equal(await db.v11Membership.count({where:{registrationId:r.reg.id}}),0);const refund=await db.v11RefundInstruction.findFirstOrThrow({where:{registrationId:r.reg.id}});assert.equal(refund.totalCents,300);assert.equal(refund.originalTradeNo,fact.channelNo);}else{assert.equal(current.eligibilityState,'FORMAL');assert.equal(current.active,true);assert.equal(await db.v11Membership.count({where:{registrationId:r.reg.id,active:true}}),1);assert.equal(await db.v11RefundInstruction.count({where:{registrationId:r.reg.id}}),0);}const again=await domain.persistMockEvent(db,input);assert.equal(again.state,'APPLIED');assert.equal(await db.v11ReceiptBinding.count({where:{registrationId:r.reg.id}}),1);
});
test('PRE018: twenty waitlist admissions across two Prisma clients conserve cap and isolate unresolved in-flight ordering with OP08',async()=>{
 const db2=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});try{await verifyOwnedDatabase(db2,process.env);const f=await fixture();f.supply=await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{waitlistMax:2}});for(let i=0;i<4;i++)await pay(await registration(f,'FORMAL'));const applicants=await Promise.all(Array.from({length:20},()=>actor(f)));const results=await Promise.all(applicants.map((a,i)=>domain.createRegistration(i%2?db2:db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership:'WAITLIST',businessKey:`${prefix}:limit:${i}`})));const allowed=results.filter(x=>'eligibilityState'in x);const blocked=results.filter(x=>!('eligibilityState'in x));assert.equal(allowed.length,1);assert.equal(blocked.length,19);for(const request of blocked){assert.equal(request.kind,'REGISTRATION');assert.equal(request.state,'BLOCKED_POLICY');assert.ok(request.blockerIds.includes('OP-08'));assert.equal(request.registrationId,null);}assert.equal(await db.v11Registration.count({where:{activityId:f.activity.id,category:'WAITLIST',active:true}}),1);assert.equal(await db.v11PaymentIntent.count({where:{registration:{activityId:f.activity.id,category:'WAITLIST'}}}),0,'Blocked admission never creates payment');const winner=allowed[0];const who=applicants.find(x=>x.actor.userId===winner.userId);await pay({reg:winner,actor:who.actor});const last=await registration(f,'WAITLIST');await pay(last);assert.equal(await db.v11Registration.count({where:{activityId:f.activity.id,eligibilityState:'WAITLIST',active:true}}),2);const beyond=await actor(f);const over=await domain.createRegistration(db,beyond.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:beyond.consent.id,membership:'WAITLIST',businessKey:prefix+sequence++});assert.equal(over.state,'BLOCKED_POLICY');assert.equal(over.registrationId,null);assert.equal(await db.v11Registration.count({where:{activityId:f.activity.id,category:'WAITLIST',active:true}}),2);assert.equal(await db.v11PaymentIntent.count({where:{registration:{activityId:f.activity.id,category:'WAITLIST'}}}),2);
 }finally{await db2.$disconnect();}
});
