import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {enqueue,claimJob}=await import(pathToFileURL(`${repo}/services/api/dist/jobs/queue.js`));
async function ownClaim(job){const rows=await db.$queryRaw`UPDATE "DurableJob" SET "state"='RUNNING',"leaseOwner"=${prefix},"leaseUntil"=clock_timestamp()+interval '30 seconds',"generation"="generation"+1,"attempts"="attempts"+1,"updatedAt"=clock_timestamp() WHERE id=${job.id} AND ("state" IN ('READY','RETRY') OR ("state"='RUNNING' AND "leaseUntil"<=clock_timestamp())) RETURNING *`;assert.equal(rows.length,1);return rows[0];}
async function leaseJob(kind,refId){const job=await db.$transaction(tx=>enqueue(tx,kind,`${prefix}:job:${sequence++}`,refId));return ownClaim(job);}
test('BR13 DR02 native unpaid failed UNKNOWN held and incomplete amount do not count toward minimum until a full trustworthy receipt succeeds',async()=>{
 const f=await fixture();await db.restaurant.update({where:{id:f.activity.restaurantId},data:{capacity:8}});f.supply=await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{targetSize:8,maxSize:8,capacity:8}});for(let i=0;i<3;i++)await pay(await registration(f,'FORMAL'));const table=await db.v11Table.findFirstOrThrow({where:{activityId:f.activity.id}});assert.equal(table.state,'WAITING');const candidates=[];for(const state of ['UNPAID','FAILED','UNKNOWN','HELD']){const r=await registration(f,'FORMAL');candidates.push(r);if(state!=='UNPAID'){const intent=await domain.startPayment(db,r.actor,r.reg.id);if(state!=='HELD')await db.v11PaymentIntent.update({where:{id:intent.id},data:{state}});}assert.equal(await db.v11Membership.count({where:{tableId:table.id,active:true}}),3);assert.equal((await db.v11Table.findUniqueOrThrow({where:{id:table.id}})).state,'WAITING');assert.equal(await db.v11Membership.count({where:{registrationId:r.reg.id}}),0);}
 const held=candidates[3];const intent=await db.v11PaymentIntent.findFirstOrThrow({where:{registrationId:held.reg.id}});const partial=await channel.pay(intent.merchantOrderNo,200);const event=await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:partial.channelNo,amountCents:200});assert.equal(event.state,'MANUAL');assert.equal((await db.v11ReceiptBinding.findFirstOrThrow({where:{intentId:intent.id}})).classification,'AMOUNT_CONFLICT');assert.equal(await db.v11Membership.count({where:{tableId:table.id,active:true}}),3);assert.equal((await db.v11Table.findUniqueOrThrow({where:{id:table.id}})).state,'WAITING');const complete=await registration(f,'FORMAL');await pay(complete);assert.equal(await db.v11Membership.count({where:{tableId:table.id,active:true}}),4);assert.equal((await db.v11Table.findUniqueOrThrow({where:{id:table.id}})).state,'FORMED');assert.equal(await db.channelReceipt.count({where:{channelTradeNo:partial.channelNo,amountCents:200}}),1);assert.equal((await db.receivedEvent.findUniqueOrThrow({where:{id:event.id}})).state,'MANUAL');
});
test('BR58 native multiple distinct trustworthy receipts each retain original F D budgets and refund exactly once on lawful termination',async()=>{
 const f=await fixture(),r=await registration(f,'FORMAL');const primary=await pay(r);await db.v11PaymentIntent.update({where:{id:primary.intent.id},data:{active:false}});const extra=await db.v11PaymentIntent.create({data:{registrationId:r.reg.id,merchantOrderNo:prefix+sequence++,totalCents:300}});const extraFact=await channel.pay(extra.merchantOrderNo,300);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:extra.id,channelNo:extraFact.channelNo,amountCents:300});const bindings=await db.v11ReceiptBinding.findMany({where:{registrationId:r.reg.id},include:{receipt:true}});assert.equal(bindings.length,2);assert.equal(new Set(bindings.map(b=>b.receipt.channelTradeNo)).size,2);assert.equal(bindings.filter(b=>b.classification==='EXTRA').length,1);await db.$transaction(async tx=>domain.terminateAndRefund(tx,await domain.registrationLock(tx,r.reg.id),prefix+sequence++,'CORE_CHANGE_REJECTED',await domain.dbNow(tx)));await db.$transaction(async tx=>domain.terminateAndRefund(tx,await domain.registrationLock(tx,r.reg.id),prefix+sequence++,'CORE_CHANGE_REJECTED',await domain.dbNow(tx)));const instructions=await db.v11RefundInstruction.findMany({where:{registrationId:r.reg.id}});assert.equal(instructions.length,2);for(const binding of bindings){const rows=instructions.filter(i=>i.receiptId===binding.receipt.id);assert.equal(rows.length,1);assert.deepEqual([rows[0].serviceFeeCents,rows[0].depositCents],[100,200]);assert.equal(rows[0].originalTradeNo,binding.receipt.channelTradeNo);const dispositions=await db.v11Disposition.findMany({where:{component:{receiptId:binding.receipt.id}}});assert.equal(dispositions.reduce((sum,x)=>sum+x.amountCents,0),300);const lease=await leaseJob('V11_REFUND',rows[0].id);await domain.recoveryHandlers(db,channel).V11_REFUND(lease);await domain.recoveryHandlers(db,channel).V11_REFUND(lease);assert.equal(await channelDb.mockChannelTransaction.count({where:{kind:'REFUND',originalTradeNo:binding.receipt.channelTradeNo,amountCents:300}}),1);}assert.equal(instructions.reduce((sum,row)=>sum+row.totalCents,0),600);assert.equal(await db.channelReceipt.count({where:{id:{in:bindings.map(b=>b.receiptId)}}}),2);assert.equal(await db.v11Membership.count({where:{registrationId:r.reg.id,active:true}}),0);
});
