import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
test('R2 new binding: DB constraints reject foreign writes and injected unavailable binding preserves MANUAL events without fallback',async()=>{
 const injectForeignRead=(model,id)=>new Proxy(db,{get(target,key){if(key==='$transaction')return callback=>target.$transaction(tx=>callback(new Proxy(tx,{get(inner,field){if(field===model)return new Proxy(inner[field],{get(delegate,method){if(method==='findUnique')return async args=>{const row=await delegate.findUnique(args);return row?.id===id?{...row,providerConfigId:'foreign-synthetic-unavailable'}:row};const v=Reflect.get(delegate,method);return typeof v==='function'?v.bind(delegate):v}});const v=Reflect.get(inner,field);return typeof v==='function'?v.bind(inner):v}})));const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v}});
 const f=await fixture();const r=await registration(f,'FORMAL');const intent=await domain.startPayment(db,r.actor,r.reg.id);await assert.rejects(db.v11PaymentIntent.update({where:{id:intent.id},data:{providerConfigId:'foreign-synthetic-unavailable'}}),e=>e.message.includes('V11PaymentIntent_channel_binding_check'));assert.equal((await db.v11PaymentIntent.findUniqueOrThrow({where:{id:intent.id}})).providerConfigId,'mock-v1');const event=await domain.persistMockEvent(injectForeignRead('v11PaymentIntent',intent.id),{kind:'PAYMENT',sourceId:intent.id,channelNo:prefix+sequence++,amountCents:300});assert.equal(event.state,'MANUAL');assert.ok(await db.financialCase.findFirst({where:{category:'V11_PAYMENT_BINDING_CONFLICT',sourceRef:intent.id}}));assert.equal(await db.v11ReceiptBinding.count({where:{intentId:intent.id}}),0);assert.notEqual((await db.v11PaymentIntent.findUniqueOrThrow({where:{id:intent.id}})).state,'CONFIRMED');
 const f2=await fixture();const r2=await registration(f2,'FORMAL');const paid=await pay(r2);const bind=await db.v11ReceiptBinding.findFirstOrThrow({where:{registrationId:r2.reg.id}});const instruction=await db.$transaction(async tx=>domain.reserveRefund(tx,await domain.registrationLock(tx,r2.reg.id),bind.receiptId,{F:100,D:200},prefix+sequence++));await assert.rejects(db.v11RefundInstruction.update({where:{id:instruction.id},data:{providerConfigId:'foreign-synthetic-unavailable'}}),e=>e.message.includes('V11RefundInstruction_channel_binding_check'));assert.equal((await db.v11RefundInstruction.findUniqueOrThrow({where:{id:instruction.id}})).providerConfigId,'mock-v1');const refund=await domain.persistMockEvent(injectForeignRead('v11RefundInstruction',instruction.id),{kind:'REFUND',sourceId:instruction.id,channelNo:prefix+sequence++,amountCents:300,originalTradeNo:paid.fact.channelNo});assert.equal(refund.state,'MANUAL');assert.ok(await db.financialCase.findFirst({where:{category:'V11_REFUND_BINDING_CONFLICT',sourceRef:instruction.id}}));assert.notEqual((await db.v11RefundInstruction.findUniqueOrThrow({where:{id:instruction.id}})).state,'CONFIRMED');assert.equal(await db.v11Disposition.count({where:{sourceRef:instruction.id,state:'COMPLETED'}}),0);
});
test('R2 new notice: concurrent receives preserve one receivedAt and sequential retries return the same clock',async()=>{
 const {aftersalesRoute}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/aftersales.js`));const f=await fixture();const r=await registration(f,'FORMAL');const notice=await db.v11DeliveryProof.create({data:{registrationId:r.reg.id,noticeKey:prefix+sequence++,kind:'CORE_CHANGE_PROPOSED',state:'SENT',proofType:'SIMULATED'}});const responses=await Promise.all(Array.from({length:20},()=>aftersalesRoute(db,r.actor,'receiveNotice',{id:notice.id})));const times=responses.map(x=>new Date(x.notice.receivedAt).toISOString());assert.equal(new Set(times).size,1);const again=await aftersalesRoute(db,r.actor,'receiveNotice',{id:notice.id});assert.equal(new Date(again.notice.receivedAt).toISOString(),times[0]);assert.equal((await db.v11DeliveryProof.findUniqueOrThrow({where:{id:notice.id}})).receivedAt.toISOString(),times[0]);
});
test('R2 new change: canonical identical retry preserves one change and conflicting compensation rejects',async()=>{
 const {aftersalesRoute}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/aftersales.js`));const f=await fixture();const ops={id:prefix+sequence++,personId:prefix+sequence++,role:'OPS',userId:null,restaurantId:null,version:0};const body={activityId:f.activity.id,supplyId:f.supply.id,kind:'RESTAURANT',businessKey:prefix+sequence++,proposedSnapshot:{restaurantId:f.activity.restaurantId,details:{b:2,a:1}},extraCompensationCents:100};const first=await aftersalesRoute(db,ops,'createChange',{body});const second=await aftersalesRoute(db,ops,'createChange',{body:{...body,proposedSnapshot:{details:{a:1,b:2},restaurantId:f.activity.restaurantId}}});assert.equal(first.change.id,second.change.id);assert.equal(first.change.acceptedAt.getTime(),second.change.acceptedAt.getTime());await assert.rejects(aftersalesRoute(db,ops,'createChange',{body:{...body,extraCompensationCents:101}}),e=>e.code==='IDEMPOTENCY_CONFLICT');assert.equal(await db.v11CoreChange.count({where:{businessKey:body.businessKey}}),1);
});
test('R2 new reconciliation: APPLIED event with missing receipt binding opens case and never counts false recovery',async()=>{
 const {reconcileMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/reconciliation.js`));const ops={id:prefix+sequence++,personId:prefix+sequence++,role:'OPS',userId:null,restaurantId:null,version:0};await reconcileMockChannel(db,channelDb,ops);const f=await fixture();const r=await registration(f,'FORMAL');const paid=await pay(r);const bind=await db.v11ReceiptBinding.findFirstOrThrow({where:{intentId:paid.intent.id}});const ev=await db.receivedEvent.findUniqueOrThrow({where:{source_merchantScope_eventKey:{source:'prelaunch-mock-v11',merchantScope:'mock-local',eventKey:`PAYMENT:${paid.fact.channelNo}`}}});assert.equal(ev.state,'APPLIED');await db.v11ReceiptBinding.delete({where:{id:bind.id}});const report=await reconcileMockChannel(db,channelDb,ops);assert.equal(report.recovered,0);assert.equal(await db.v11ReceiptBinding.count({where:{receiptId:bind.receiptId}}),0);assert.ok(await db.financialCase.findFirst({where:{category:'V11_CHANNEL_PAYMENT_RECOVERY_INCOMPLETE',sourceRef:paid.intent.id}}));assert.ok(await db.channelReceipt.findUnique({where:{id:bind.receiptId}}));assert.equal((await db.receivedEvent.findUniqueOrThrow({where:{id:ev.id}})).state,'APPLIED');
});
test('R2 parser: native malformed JSON oversized body and unsupported media return sanitized 400 413 415',async()=>{
 const {buildPrelaunchApp}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/routes.js`));const app=await buildPrelaunchApp(db,process.env,repo,channelDb);try{for(const [headers,payload,expected,code] of [[{'content-type':'application/json'},'{bad',400,'INVALID_INPUT'],[{'content-type':'application/json'},JSON.stringify({synthetic:'x'.repeat(2*1024*1024)}),413,'PAYLOAD_TOO_LARGE'],[{'content-type':'application/xml'},'<synthetic/>',415,'UNSUPPORTED_MEDIA_TYPE']]){const response=await app.inject({method:'POST',url:'/api/prelaunch/v11/auth/login',headers:{...headers,'x-fanju-contract':'prelaunch-v11-1'},payload});assert.equal(response.statusCode,expected);assert.equal(response.json().error.code,code);assert.ok(!response.body.includes('synthetic'));}}finally{await app.close();}
});
