import {syntheticConsentDocuments,syntheticConsentHashes} from './fixtures/synthetic-consent.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;
if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);
const {PrismaPg}=require('@prisma/adapter-pg');
const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));
const domain=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/domain.js`));
const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));
const {PersistentMockChannel}=await import(pathToFileURL(`${repo}/services/api/dist/funding/mock-channel.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});
await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const channel=new PersistentMockChannel(channelDb);
const prefix=`money-${randomUUID()}`;
let sequence=0;
async function fixture(){
 const restaurant=await db.restaurant.create({data:{name:'合成测试餐厅',district:'上海测试区域',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1,cuisineTags:[],capacity:4}});
 const now=await db.$transaction(domain.dbNow);
 const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成兴趣体验',theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区域',businessArea:'TEST_ONLY',startsAt:new Date(now.getTime()+72*3600_000),endsAt:new Date(now.getTime()+74*3600_000),registrationEndsAt:new Date(now.getTime()+64*3600_000),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix, bundleDigest:prefix+sequence++,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:syntheticConsentDocuments()},blockersJson:['OP-05']}});
 const supply=await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',explicitSyntheticAmounts:true},digest:prefix+sequence++,status:'SIMULATION_APPROVED'}});
 return {activity,supply,policy};
}
async function actor(f){const user=await db.user.create({data:{wechatOpenid:prefix+sequence++,phone:'synthetic-authorized'}});await db.v11Profile.create({data:{userId:user.id,gender:'MALE',adultConfirmed:true,adaptationConfirmed:true}});const consent=await db.v11BundleConsent.create({data:{userId:user.id,policyId:f.policy.id,...syntheticConsentHashes(),acceptedAt:await db.$transaction(domain.dbNow)}});return{actor:{id:prefix+sequence++,personId:prefix+sequence++,role:'USER',userId:user.id,restaurantId:null,version:0},consent};}
async function registration(f,membership){const a=await actor(f);const reg=await domain.createRegistration(db,a.actor,{activityId:f.activity.id,supplyId:f.supply.id,policyId:f.policy.id,consentId:a.consent.id,membership,businessKey:prefix+sequence++});assert.ok('eligibilityState'in reg);return{reg,actor:a.actor};}
async function pay(r){const intent=await domain.startPayment(db,r.actor,r.reg.id);const fact=await channel.pay(intent.merchantOrderNo,intent.totalCents);await domain.persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});return{intent,fact};}
test.after(async()=>{await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
test('VEN04 VEN05: native supply bounds restaurant signature approval and immutable revision gates',async()=>{
 const {buildPrelaunchApp}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/routes.js`));const {scryptSync,randomBytes}=await import('node:crypto');const password=`synthetic-${randomUUID()}`;const salt=randomBytes(16);const passwordHash=`scrypt:${salt.toString('hex')}:${scryptSync(password,salt,64).toString('hex')}`;const f=await fixture();await db.restaurant.update({where:{id:f.activity.restaurantId},data:{capacity:12}});const ops=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'OPS',passwordHash}});const rest=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'RESTAURANT',restaurantId:f.activity.restaurantId,passwordHash}});const other=await db.v11Actor.create({data:{personId:prefix+sequence++,role:'RESTAURANT',passwordHash}});const app=await buildPrelaunchApp(db,process.env,repo,channelDb);
 try{const headers=async a=>{const r=await app.inject({method:'POST',url:'/api/prelaunch/v11/auth/login',headers:{'x-fanju-contract':'prelaunch-v11-1'},payload:{actorId:a.id,password}});assert.equal(r.statusCode,200);return{'x-fanju-contract':'prelaunch-v11-1',authorization:`Bearer ${r.json().token}`}};const op=await headers(ops),rh=await headers(rest),oh=await headers(other);const req=(url,payload,h=op)=>app.inject({method:'POST',url:'/api/prelaunch/v11'+url,payload,headers:h});const body={activityId:f.activity.id,policyId:f.policy.id,min:4,target:4,max:6,maxTables:2,capacity:12,F:100,D:200,WAITLIST_MAX:2,strategy:'FILL_TO_TARGET',estimatedMealMinCents:1000,estimatedMealMaxCents:2000,fixedFees:[]};
 for(const change of [{min:3},{min:5,target:4},{target:7,max:6},{max:9},{maxTables:0},{maxTables:1,capacity:12},{capacity:3},{strategy:'BALANCED'}]){const bad=await req('/ops/supplies',{...body,...change});assert.equal(bad.statusCode,400,JSON.stringify(change));}
 const made=await req('/ops/supplies',body);assert.equal(made.statusCode,200);const id=made.json().id;const stored=await db.v11SupplyRevision.findUniqueOrThrow({where:{id}});assert.deepEqual([stored.minSize,stored.targetSize,stored.maxSize,stored.maxTables],[4,4,6,2]);assert.equal(stored.signedAt,null);const approval={D_MIN:0,D_MAX:500,simulationBatchHour:10};assert.equal((await req('/ops/supplies/'+id+'/approve',approval)).statusCode,409);const user=await actor(f);await assert.rejects(domain.createRegistration(db,user.actor,{activityId:f.activity.id,supplyId:id,policyId:f.policy.id,consentId:user.consent.id,membership:'FORMAL',businessKey:prefix+sequence++}),e=>e.code==='SUPPLY_NOT_APPROVED');assert.equal(await db.v11PaymentIntent.count({where:{registration:{supplyId:id}}}),0);
 assert.equal((await req('/restaurant/supplies/'+id+'/confirm',{},oh)).statusCode,404);assert.equal((await req('/restaurant/supplies/'+id+'/confirm',{},rh)).statusCode,200);assert.equal((await req('/ops/supplies/'+id+'/approve',approval,rh)).statusCode,403);assert.equal((await req('/ops/supplies/'+id+'/approve',approval)).statusCode,200);const signed=await db.v11SupplyRevision.findUniqueOrThrow({where:{id}});assert.equal(signed.personId,rest.personId);assert.ok(signed.signedAt);
 const {activityId,policyId,...revisionBody}=body;const next=await req('/ops/supplies/'+id+'/revision',{...revisionBody,F:101});assert.equal(next.statusCode,200);const nextId=next.json().supply.id;const draft=await db.v11SupplyRevision.findUniqueOrThrow({where:{id:nextId}});assert.equal(draft.status,'DRAFT');assert.equal(draft.personId,null);assert.equal(draft.signedAt,null);assert.equal((await req('/ops/supplies/'+nextId+'/approve',approval)).statusCode,409);await assert.rejects(domain.createRegistration(db,user.actor,{activityId:f.activity.id,supplyId:nextId,policyId:f.policy.id,consentId:user.consent.id,membership:'FORMAL',businessKey:prefix+sequence++}),e=>e.code==='SUPPLY_NOT_APPROVED');assert.equal((await db.v11SupplyRevision.findUniqueOrThrow({where:{id}})).serviceFeeCents,100);assert.equal((await db.v11SupplyRevision.findUniqueOrThrow({where:{id}})).signedAt.getTime(),signed.signedAt.getTime());
 }finally{await app.close();}
});
for(const strategy of ['FILL_TO_TARGET','FILL_TO_MAX'])test(`VEN06: native ${strategy} streams two bounded tables never splits formed members and promotes queue head`,async()=>{
 const f=await fixture();await db.restaurant.update({where:{id:f.activity.restaurantId},data:{capacity:12}});await db.activity.update({where:{id:f.activity.id},data:{capacity:12}});f.supply=await db.v11SupplyRevision.update({where:{id:f.supply.id},data:{minSize:4,targetSize:4,maxSize:6,maxTables:2,capacity:12,waitlistMax:2,strategy}});const regs=[];for(let i=0;i<4;i++){const r=await registration(f,'FORMAL');regs.push(r);await pay(r);}const formed=await db.v11Table.findFirstOrThrow({where:{activityId:f.activity.id,ordinal:1}});assert.equal(formed.state,'FORMED');const original=await db.v11Membership.findMany({where:{tableId:formed.id,active:true}});for(let i=4;i<12;i++){const r=await registration(f,'FORMAL');regs.push(r);await pay(r);if(i===4)assert.equal((await db.v11Membership.findUniqueOrThrow({where:{registrationId:r.reg.id}})).tableId===formed.id,strategy==='FILL_TO_MAX');for(const member of original)assert.equal((await db.v11Membership.findUniqueOrThrow({where:{id:member.id}})).tableId,formed.id);}
 const tables=await db.v11Table.findMany({where:{activityId:f.activity.id},orderBy:{ordinal:'asc'}});assert.equal(tables.length,2);for(const table of tables)assert.equal(await db.v11Membership.count({where:{tableId:table.id,active:true}}),6);await assert.rejects(registration(f,'FORMAL'),e=>e.code==='FORMAL_CAPACITY_FULL');const queueFixture=await fixture();await db.restaurant.update({where:{id:queueFixture.activity.restaurantId},data:{capacity:12}});queueFixture.supply=await db.v11SupplyRevision.update({where:{id:queueFixture.supply.id},data:{minSize:4,targetSize:4,maxSize:6,maxTables:2,capacity:12,waitlistMax:2,strategy}});for(let i=0;i<11;i++)await pay(await registration(queueFixture,'FORMAL'));const held=await registration(queueFixture,'FORMAL');const first=await registration(queueFixture,'WAITLIST');await pay(first);const second=await registration(queueFixture,'WAITLIST');await pay(second);await db.v11Profile.update({where:{userId:second.actor.userId},data:{gender:'FEMALE'}});await domain.acceptCancellation(db,held.actor,held.reg.id,prefix+sequence++);assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:first.reg.id}})).eligibilityState,'FORMAL');assert.equal((await db.v11Registration.findUniqueOrThrow({where:{id:second.reg.id}})).eligibilityState,'WAITLIST');assert.equal(await db.v11Table.count({where:{activityId:queueFixture.activity.id}}),2);assert.equal(await db.v11Membership.count({where:{active:true,registration:{activityId:queueFixture.activity.id}}}),12);for(const member of original)assert.equal((await db.v11Membership.findUniqueOrThrow({where:{id:member.id}})).tableId,formed.id);
});
