import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID,scryptSync} from 'node:crypto';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const repo=process.env.PRELAUNCH_SOURCE_ROOT;if(!repo)throw Error('Explicit owned source root required');
const require=createRequire(`${repo}/services/api/package.json`);const {PrismaPg}=require('@prisma/adapter-pg');const {PrismaClient}=await import(pathToFileURL(`${repo}/services/api/dist/generated/prisma/client.js`));const {verifyOwnedDatabase}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/ownership.js`));const {buildPrelaunchApp}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/routes.js`));
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})}),channelDb=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.PRELAUNCH_CHANNEL_DATABASE_URL})});await verifyOwnedDatabase(db,process.env);await verifyOwnedDatabase(channelDb,{...process.env,PRELAUNCH_DATABASE_NAME:process.env.PRELAUNCH_CHANNEL_DATABASE_NAME});
const base='/api/prelaunch/v11',origin='http://127.0.0.1:47124';
let app;test.before(async()=>{app=await buildPrelaunchApp(db,{...process.env,PRELAUNCH_CORS_ORIGINS:origin},repo,channelDb);});test.after(async()=>{await app?.close();await Promise.all([db.$disconnect(),channelDb.$disconnect()]);});
const {activityTimeSlot,matchesTimePreference,summarizeTimePreferences}=await import(pathToFileURL(`${repo}/services/api/dist/prelaunch/time-preferences.js`));
test('USR06/07 Shanghai boundaries and anonymous distinct-per-profile multi-select statistics',()=>{
 assert.equal(activityTimeSlot(new Date('2026-10-05T03:00:00Z')),'WEEKDAY_LUNCH');
 assert.equal(activityTimeSlot(new Date('2026-10-05T06:59:59Z')),'WEEKDAY_LUNCH');
 assert.equal(activityTimeSlot(new Date('2026-10-05T07:00:00Z')),null);
 assert.equal(activityTimeSlot(new Date('2026-10-03T09:00:00Z')),'WEEKEND_DINNER');
 assert.equal(activityTimeSlot(new Date('2026-10-03T14:00:00Z')),null);
 assert.equal(matchesTimePreference(new Date('2026-10-05T03:00:00Z'),[]),false);
 assert.equal(matchesTimePreference(new Date('2026-10-05T03:00:00Z'),['WEEKDAY_LUNCH']),true);
 assert.equal(matchesTimePreference(new Date('2026-10-05T03:00:00Z'),['WEEKEND_LUNCH']),false);
 const aggregate=summarizeTimePreferences([{availableTimes:['WEEKDAY_LUNCH','WEEKDAY_LUNCH','WEEKEND_DINNER']},{availableTimes:[]},{availableTimes:['legacy_free_text']}]);
 assert.equal(aggregate.profileCount,3);assert.equal(aggregate.emptyPreferenceCount,1);assert.equal(aggregate.unrecognizedPreferenceProfileCount,1);assert.deepEqual(aggregate.slots.map(s=>s.count),[1,0,0,1]);assert.ok(!JSON.stringify(aggregate).includes('legacy_free_text'));
});
test('USR06 local API: only own saved preference is read; demand restricted to OPS/REVIEWER and returns only counts',async()=>{
 const prefix='time_ui_'+randomUUID().replaceAll('-',''),password=randomBytes(24).toString('hex'),salt=randomBytes(16),hash=`scrypt:${salt.toString('hex')}:${scryptSync(password,salt,64).toString('hex')}`;
 const user=await db.user.create({data:{wechatOpenid:prefix,phone:'synthetic-local'}});const actors={};for(const role of ['USER','OPS','REVIEWER','RESTAURANT'])actors[role]=await db.v11Actor.create({data:{id:prefix+'_'+role,personId:prefix+'_'+role,role,passwordHash:hash,...(role==='USER'?{userId:user.id}:{})}});
 const headers={};for(const role of Object.keys(actors)){const login=await app.inject({method:'POST',url:base+'/auth/login',headers:{'x-fanju-contract':'prelaunch-v11-1'},payload:{actorId:actors[role].id,password}});assert.equal(login.statusCode,200);headers[role]={'x-fanju-contract':'prelaunch-v11-1',authorization:'Bearer '+login.json().token};}
 const restaurant=await db.restaurant.create({data:{name:'合成偏好证明餐厅',district:'上海测试区',businessArea:'TEST_ONLY',address:'合成地址',contactName:'TEST_ONLY',contactPhone:'synthetic-local',budgetCents:1000,cuisineTags:[],capacity:4}});
 const policy=await db.v11PolicySnapshot.create({data:{bundleVersion:'SIMULATION_ONLY:'+prefix,bundleDigest:prefix,baselineHash:'synthetic-only',status:'LOCAL_DRAFT',docsJson:{scope:'TEST_ONLY',documents:[]},blockersJson:[]}});
 const activityIds=[];for(const [label,startsAt]of [['match','2030-10-07T03:00:00Z'],['other','2030-10-07T09:00:00Z']]){const activity=await db.activity.create({data:{restaurantId:restaurant.id,title:'合成时段证明'+label,theme:'TEST_ONLY',description:'TEST_ONLY',district:'上海测试区',businessArea:'TEST_ONLY',startsAt:new Date(startsAt),endsAt:new Date(new Date(startsAt).getTime()+3600000),registrationEndsAt:new Date('2030-10-01T00:00:00Z'),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:4,status:'PUBLISHED'}});activityIds.push(activity.id);await db.v11SupplyRevision.create({data:{activityId:activity.id,restaurantId:restaurant.id,policyId:policy.id,revision:1,minSize:4,targetSize:4,maxSize:4,maxTables:1,capacity:4,serviceFeeCents:100,depositCents:200,waitlistMax:4,strategy:'FILL_TO_MAX',snapshot:{scope:'TEST_ONLY',estimatedMealMinCents:1000,estimatedMealMaxCents:2000,fixedFees:[]},digest:prefix+label,status:'SIMULATION_APPROVED'}});}
 async function allActivities(auth){const rows=[];let cursor;do{const response=await app.inject({method:'GET',url:base+'/activities?limit=50'+(cursor?'&cursor='+encodeURIComponent(cursor):''),...(auth?{headers:auth}:{})});assert.equal(response.statusCode,200);rows.push(...response.json().activities);cursor=response.json().nextCursor;}while(cursor);return rows;}
 const before=await app.inject({method:'GET',url:base+'/ops/time-demand',headers:headers.OPS});assert.equal(before.statusCode,200);
 const saved=await app.inject({method:'PUT',url:base+'/profile',headers:headers.USER,payload:{gender:'MALE',adultDeclaration:true,serviceCompatible:true,timePreferences:['WEEKDAY_LUNCH','WEEKEND_DINNER']}});assert.equal(saved.statusCode,200);
 const after=await app.inject({method:'GET',url:base+'/ops/time-demand',headers:headers.OPS});assert.equal(after.statusCode,200);const demand=after.json().demand,prior=before.json().demand;assert.equal(demand.profileCount,prior.profileCount+1);for(const code of ['WEEKDAY_LUNCH','WEEKEND_DINNER'])assert.equal(demand.slots.find(s=>s.code===code).count,prior.slots.find(s=>s.code===code).count+1);
 assert.deepEqual(Object.keys(demand).sort(),['scope','timezone','profileCount','emptyPreferenceCount','unrecognizedPreferenceProfileCount','slots'].sort());assert.ok(!after.body.includes(user.id));assert.ok(!after.body.includes(prefix));assert.ok(!after.body.includes('gender'));assert.ok(!after.body.includes('phone'));
 assert.equal((await app.inject({method:'GET',url:base+'/ops/time-demand',headers:headers.REVIEWER})).statusCode,200);for(const role of ['USER','RESTAURANT'])assert.equal((await app.inject({method:'GET',url:base+'/ops/time-demand',headers:headers[role]})).statusCode,403);assert.equal((await app.inject({method:'GET',url:base+'/ops/time-demand'})).statusCode,401);
 // Same activity set and ID pagination; only an own-profile boolean is added, no admission filtering.
 const anonymous=await app.inject({method:'GET',url:base+'/activities?limit=50'}),personal=await app.inject({method:'GET',url:base+'/activities?limit=50',headers:headers.USER});assert.equal(anonymous.statusCode,200);assert.equal(personal.statusCode,200);assert.deepEqual(personal.json().activities.map(a=>a.id),anonymous.json().activities.map(a=>a.id));for(const activity of personal.json().activities)assert.equal(activity.preferenceMatched,matchesTimePreference(new Date(activity.startsAt),['WEEKDAY_LUNCH','WEEKEND_DINNER']));assert.ok(anonymous.json().activities.every(a=>!a.preferenceMatched));
 const all=await allActivities(headers.USER),own=activityIds.map(id=>all.find(a=>a.id===id));assert.ok(own.every(Boolean));assert.equal(own[0].preferenceMatched,true);assert.equal(own[1].preferenceMatched,false);assert.deepEqual((await allActivities()).map(a=>a.id),all.map(a=>a.id));
 const clear=await app.inject({method:'PUT',url:base+'/profile',headers:headers.USER,payload:{gender:'MALE',adultDeclaration:true,serviceCompatible:true,timePreferences:[]}});assert.equal(clear.statusCode,200);const empty=await app.inject({method:'GET',url:base+'/activities?limit=50',headers:headers.USER});assert.deepEqual(empty.json().activities.map(a=>a.id),anonymous.json().activities.map(a=>a.id));assert.ok(empty.json().activities.every(a=>!a.preferenceMatched));
});
