import { describe, it, expect, vi } from 'vitest';
import { scryptSync } from 'node:crypto';
import Fastify from 'fastify';
import type { PrismaClient } from '../generated/prisma/client.js';
import { registerAuth, signSession, requireUser, requireOps } from '../auth.js';
import { errorResponse } from './contracts.js';
import { createProductionControlledIdentity, parseControlledIdentityBindings } from './controlled-identity.js';
const password='synthetic-password';const salt='a'.repeat(32);
const base={accountId:'account',username:'controlled',accountVersion:'v1',enabled:true,passwordHash:'scrypt:'+salt+':'+scryptSync(password,salt,64).toString('hex'),actorId:'actor',personId:'person',actorVersion:2,role:'OPS',restaurantId:null};
async function fixture(role='OPS',config:unknown=undefined) {
 const actor={id:'actor',personId:'person',version:2,role,userId:null,restaurantId:role==='RESTAURANT'?'restaurant':null,passwordHash:'unused-synthetic',enabled:true};
 const db={adminUser:{findUnique:vi.fn()},user:{findUnique:vi.fn()},auditLog:{create:vi.fn().mockResolvedValue({})},v11Actor:{findUnique:vi.fn().mockResolvedValue(actor)}};
 const app=Fastify();await registerAuth(app,db as unknown as PrismaClient,{APP_ENV:'test',SESSION_SECRET:'synthetic-only-signing-secret-32-characters',OPS_ACCOUNTS_JSON:JSON.stringify([{username:'legacy-admin',role:'OPS',version:'1',enabled:true,passwordHash:base.passwordHash}])});
 const identity=createProductionControlledIdentity(db as unknown as PrismaClient,JSON.stringify(config??[{...base,role,restaurantId:actor.restaurantId}]));
 app.setErrorHandler((e,_q,r)=>{if('statusCode'in e&&e.statusCode===401)return r.code(401).send({error:'UNAUTHORIZED'});if('statusCode'in e&&e.statusCode===403)return r.code(403).send({error:'FORBIDDEN'});const x=errorResponse(e);r.code(x.statusCode).send(x.body);});
 app.get('/identity',identity.authenticate);app.post('/login',identity.login);app.get('/legacy-user',requireUser);app.get('/legacy-ops',requireOps);
 const token=async()=>{const r=await app.inject({method:'POST',url:'/login',payload:{username:'controlled',password}});expect(r.statusCode).toBe(200);return r.json().token as string;};
 return{app,db,actor,token};
}
describe('controlled formal role bindings with separate token audience',()=>{
 it.each(['OPS','REVIEWER','RESTAURANT'])('maps configured %s and ignores client privilege hints',async role=>{const f=await fixture(role);try{const r=await f.app.inject({url:'/identity?role=SUPER_ADMIN&restaurantId=other',headers:{authorization:'Bearer '+await f.token()}});expect(r.statusCode).toBe(200);expect(r.json()).toMatchObject({id:'actor',role,personId:'person'});expect(r.json()).not.toHaveProperty('passwordHash');if(role==='RESTAURANT')expect(r.json().restaurantId).toBe('restaurant');}finally{await f.app.close();}});
 it.each(['REVIEWER','RESTAURANT'])('never gives %s access to legacy user or OPS APIs',async role=>{const f=await fixture(role);try{const headers={authorization:'Bearer '+await f.token()};expect((await f.app.inject({url:'/legacy-user',headers})).statusCode).toBe(401);expect((await f.app.inject({url:'/legacy-ops',headers})).statusCode).toBe(401);expect(f.db.adminUser.findUnique).not.toHaveBeenCalled();expect(f.db.user.findUnique).not.toHaveBeenCalled();}finally{await f.app.close();}});
 it('rejects legacy OPS and USER tokens before actor lookup',async()=>{const f=await fixture();try{for(const role of ['OPS','USER'] as const){const token=signSession(f.app,{sub:'legacy',role});expect((await f.app.inject({url:'/identity',headers:{authorization:'Bearer '+token}})).statusCode).toBe(401);}expect(f.db.v11Actor.findUnique).not.toHaveBeenCalled();}finally{await f.app.close();}});
 it('rejects unconfigured, disabled and wrong-password login without granting or auditing',async()=>{for(const config of [[],[{...base,enabled:false}]]){const f=await fixture('OPS',config);try{expect((await f.app.inject({method:'POST',url:'/login',payload:{username:'controlled',password}})).statusCode).toBe(401);expect(f.db.v11Actor.findUnique).not.toHaveBeenCalled();expect(f.db.auditLog.create).not.toHaveBeenCalled();}finally{await f.app.close();}}const f=await fixture();try{expect((await f.app.inject({method:'POST',url:'/login',payload:{username:'controlled',password:'wrong'}})).statusCode).toBe(401);}finally{await f.app.close();}});
 it('rejects client login role grants and bounds failed attempts',async()=>{const f=await fixture();try{expect((await f.app.inject({method:'POST',url:'/login',payload:{username:'controlled',password,role:'REVIEWER'}})).statusCode).toBe(400);for(let i=0;i<9;i++)expect((await f.app.inject({method:'POST',url:'/login',payload:{username:'controlled',password:'wrong'}})).statusCode).toBe(401);expect((await f.app.inject({method:'POST',url:'/login',payload:{username:'controlled',password:'wrong'}})).statusCode).toBe(429);}finally{await f.app.close();}});
 it.each(['role','personId','version','restaurantId','userId','enabled'])('revokes a changed actor %s',async field=>{const f=await fixture();try{const token=await f.token();Object.assign(f.actor,{[field]:field==='version'?3:field==='enabled'?false:'different'});expect([401,403]).toContain((await f.app.inject({url:'/identity',headers:{authorization:'Bearer '+token}})).statusCode);}finally{await f.app.close();}});
 it('rejects expired, wrong-version and forged controlled tokens',async()=>{const f=await fixture();try{const now=Math.floor(Date.now()/1000);for(const changes of [{exp:now-1},{accountVersion:'v2'},{actorVersion:3},{role:'REVIEWER'}]){const token=f.app.jwt.sign({sub:'account',role:'OPS',aud:'fanju-v11-controlled',iss:'fanju:test',sessionVersion:'1',accountVersion:'v1',actorVersion:2,iat:now-100,exp:now+100,...changes});expect((await f.app.inject({url:'/identity',headers:{authorization:'Bearer '+token}})).statusCode).toBe(401);}expect((await f.app.inject({url:'/identity',headers:{authorization:'Bearer forged'}})).statusCode).toBe(401);expect(f.db.v11Actor.findUnique).not.toHaveBeenCalled();}finally{await f.app.close();}});
 it.each(['malformed','duplicate-account','duplicate-actor','duplicate-username','missing-restaurant','foreign-restaurant','unknown-field','user-role'])('rejects invalid config %s with generic error',kind=>{const value=kind==='malformed'?'private-invalid-config':JSON.stringify(kind==='duplicate-account'?[base,{...base,actorId:'actor2',username:'other'}]:kind==='duplicate-actor'?[base,{...base,accountId:'account2',username:'other'}]:kind==='duplicate-username'?[base,{...base,accountId:'account2',actorId:'actor2'}]:[{...base,...(kind==='missing-restaurant'?{role:'RESTAURANT'}:kind==='foreign-restaurant'?{restaurantId:'rest'}:kind==='unknown-field'?{password:'do-not-echo'}:{role:'USER'})}]);expect(()=>parseControlledIdentityBindings(value)).toThrow('Invalid controlled V1.1 identity configuration');});
});
