import type { PrismaClient } from '../generated/prisma/client.js';
import { object, audit, dbNow } from './domain.js';
import { reject, requireRole, type LocalPrincipal } from './contracts.js';
import { PersistentMockChannel } from '../funding/mock-channel.js';
export async function fundingBuckets(db:PrismaClient){
 return db.$transaction(async tx=>{
 const components=await tx.v11FundComponent.findMany({include:{v11Disposition_componentId:true}});
 const totals={F:{original:0,refunded:0,refundReserved:0,restaurantPaid:0,restaurantReserved:0,platformRetained:0,undisposed:0},D:{original:0,refunded:0,refundReserved:0,restaurantPaid:0,restaurantReserved:0,platformRetained:0,undisposed:0}};
 for(const component of components){if(component.kind!=='F'&&component.kind!=='D')reject(409,'UNKNOWN_COMPONENT_KIND');const b=totals[component.kind];let used=0;b.original+=component.originalCents;for(const row of component.v11Disposition_componentId){if(row.state==='RELEASED')continue;if(!Number.isSafeInteger(row.amountCents)||row.amountCents<0)reject(409,'INVALID_COMPONENT_DISPOSITION');used+=row.amountCents;const done=row.state==='COMPLETED';if(row.kind==='REFUND')b[done?'refunded':'refundReserved']+=row.amountCents;else if(row.kind==='RESTAURANT')b[done?'restaurantPaid':'restaurantReserved']+=row.amountCents;else if(row.kind==='PLATFORM')b.platformRetained+=row.amountCents;else reject(409,'UNKNOWN_COMPONENT_DISPOSITION');}if(used>component.originalCents)reject(409,'COMPONENT_BUDGET_EXCEEDED');b.undisposed+=component.originalCents-used;}
 return {scope:'SIMULATION_ONLY',currency:'CNY',components:totals,accountingRecognition:false};
 },{isolationLevel:'RepeatableRead'});
}
export async function claimFinancialCase(db:PrismaClient,actor:LocalPrincipal,id:string){requireRole(actor,'OPS');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "FinancialCase" WHERE id=${id} FOR UPDATE`;const row=await tx.financialCase.findUniqueOrThrow({where:{id}});if(row.state==='RESOLVED')reject(409,'CASE_ALREADY_RESOLVED');if(row.owner!==actor.id&&!['local-simulation-ops','local-review-required'].includes(row.owner))reject(409,'CASE_ALREADY_CLAIMED');const updated=await tx.financialCase.update({where:{id},data:{owner:actor.id}});await audit(tx,'financial-case.claimed','FinancialCase',id,actor);return{id:updated.id,state:updated.state,owner:updated.owner};});}
export async function resolveFinancialCase(db:PrismaClient,channelDb:PrismaClient,actor:LocalPrincipal,id:string,reason:string){
 requireRole(actor,'OPS');const initial=await db.financialCase.findUniqueOrThrow({where:{id}});if(initial.owner!==actor.id)reject(403,'CASE_OWNER_REQUIRED');
 // A note cannot resolve an unrecognised or mismatched financial fact.
 const channel=new PersistentMockChannel(channelDb);let evidence:Record<string,unknown>|null=null;
 if(['V11_UNALLOCATED_RECEIPT','V11_RECEIPT_CONFLICT'].includes(initial.category)){
  const receipt=await db.channelReceipt.findUnique({where:{id:initial.sourceRef}});if(receipt?.channel!=='mock'||receipt.merchantScope!=='mock-local')reject(409,'ORIGINAL_CHANNEL_UNAVAILABLE');const fact=await channel.query('PAYMENT',receipt.merchantOrderNo);if(fact?.status!=='SUCCEEDED'||fact.channelNo!==receipt.channelTradeNo||fact.amountCents!==receipt.amountCents)reject(409,'CASE_FACT_UNRESOLVED');const binding=await db.v11ReceiptBinding.findUnique({where:{receiptId:receipt.id}});const components=await db.v11FundComponent.findMany({where:{receiptId:receipt.id}});if(!binding||components.length!==2||components.reduce((s,r)=>s+r.originalCents,0)!==receipt.amountCents)reject(409,'CASE_ALLOCATION_UNRESOLVED');evidence={type:'RECEIPT',receiptId:receipt.id};
 }else if(initial.category==='V11_REFUND_CONFLICT'){
  const instruction=await db.v11RefundInstruction.findUnique({where:{id:initial.sourceRef}});if(!instruction||instruction.state!=='CONFIRMED')reject(409,'CASE_REFUND_UNRESOLVED');channel.assertBinding(instruction);const fact=await channel.query('REFUND',instruction.merchantRefundNo);if(fact?.status!=='SUCCEEDED'||fact.amountCents!==instruction.totalCents||fact.originalTradeNo!==instruction.originalTradeNo||fact.channelNo!==instruction.channelRefundNo)reject(409,'CASE_FACT_UNRESOLVED');evidence={type:'REFUND',instructionId:instruction.id};
 }else if(['V11_ORPHAN_PAYMENT_EVENT','V11_ORPHAN_REFUND_EVENT','V11_EVENT_CONFLICT'].includes(initial.category)){
  const event=await db.receivedEvent.findUnique({where:{id:initial.sourceRef}});if(event?.source!=='prelaunch-mock-v11'||event.state!=='APPLIED')reject(409,'CASE_EVENT_UNRESOLVED');const payload=object(event.normalizedPayload);if(payload.kind==='PAYMENT'){const intent=await db.v11PaymentIntent.findUnique({where:{id:String(payload.sourceId)}});if(!intent||intent.state!=='CONFIRMED')reject(409,'CASE_EVENT_UNRESOLVED');const fact=await channel.query('PAYMENT',intent.merchantOrderNo);if(fact?.status!=='SUCCEEDED'||fact.channelNo!==payload.channelNo||fact.amountCents!==payload.amountCents)reject(409,'CASE_FACT_UNRESOLVED');}else if(payload.kind==='REFUND'){const refund=await db.v11RefundInstruction.findUnique({where:{id:String(payload.sourceId)}});if(!refund||refund.state!=='CONFIRMED')reject(409,'CASE_EVENT_UNRESOLVED');const fact=await channel.query('REFUND',refund.merchantRefundNo);if(fact?.status!=='SUCCEEDED'||fact.channelNo!==payload.channelNo||fact.amountCents!==payload.amountCents)reject(409,'CASE_FACT_UNRESOLVED');}else reject(409,'CASE_EVENT_UNRESOLVED');evidence={type:'EVENT',eventId:event.id};
 }else if(initial.category==='JOB_REQUIRES_REVIEW'){
  const job=await db.durableJob.findUnique({where:{id:initial.sourceRef}});if(!job||job.state!=='DONE')reject(409,'CASE_JOB_UNRESOLVED');evidence={type:'JOB',jobId:job.id};
 }else reject(409,'CASE_REQUIRES_SPECIALIST_REVIEW');
 await fundingBuckets(db);
 return db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "FinancialCase" WHERE id=${id} FOR UPDATE`;const current=await tx.financialCase.findUniqueOrThrow({where:{id}});if(current.owner!==actor.id)reject(403,'CASE_OWNER_REQUIRED');if(current.state==='RESOLVED')return{id,currentState:current.state};const row=await tx.financialCase.update({where:{id},data:{state:'RESOLVED',resolution:JSON.stringify({scope:'SIMULATION_ONLY',reason,evidence}),reviewedBy:actor.id,reviewedAt:await dbNow(tx)}});await audit(tx,'financial-case.resolved','FinancialCase',id,actor);return{id:row.id,state:row.state,evidence,scope:'SIMULATION_ONLY'};});
}
