import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {PrismaClient} from '../generated/prisma/client.js';
import {z} from 'zod';
import {createProductionUserPrincipal} from './production-identity.js';
import {requireRole,reject,type LocalPrincipal} from './contracts.js';
import type {RuntimeAuthoritySource} from './formal-runtime-policy.js';
import {formalCoreChangeService,formalCoreChangeDigest,formalCoreChangeNameVisible,formalCoreChangePublicSnapshot} from './formal-core-change-service.js';
import {object} from './domain.js';
const id=z.string().min(1).max(160).regex(/^[A-Za-z0-9_.:-]+$/);
export async function registerFormalCoreChangeRoutes(app:FastifyInstance,db:PrismaClient,source:RuntimeAuthoritySource,controlled:{authenticate:(request:FastifyRequest)=>Promise<LocalPrincipal>},owner:string){
 const service=formalCoreChangeService(db,source,owner),user=createProductionUserPrincipal(db);
 app.post('/api/v11/ops/formal/activities/:id/core-changes',async req=>{const actor=await controlled.authenticate(req),p=z.object({id}).strict().parse(req.params);z.object({}).strict().parse(req.query);return service.propose(actor,p.id,z.object({businessKey:id,proposedSupplyId:id}).strict().parse(req.body));});
 app.post('/api/v11/formal/core-changes/:id/choices',async req=>{const actor=await user(req),p=z.object({id}).strict().parse(req.params);z.object({}).strict().parse(req.query);const b=z.object({registrationId:id,choice:z.enum(['ACCEPT','REJECT'])}).strict().parse(req.body);return service.respond(actor,p.id,b.registrationId,b.choice);});
 app.get('/api/v11/formal/registrations/:id/core-changes',async req=>{
  const actor=await user(req),p=z.object({id}).strict().parse(req.params);z.object({}).strict().parse(req.query);
  const reg=await db.v11Registration.findFirst({where:{id:p.id,userId:actor.userId!,policy:{status:'FORMAL_RUNTIME'}}});if(!reg)reject(404,'RESOURCE_NOT_FOUND');
  const rows=await db.v11CoreChange.findMany({where:{activityId:reg.activityId,supplyId:reg.supplyId,kind:'FORMAL_CORE_CHANGE',state:'FORMAL_PROPOSED',acceptedAt:{gte:reg.acceptedAt}},orderBy:{acceptedAt:'desc'},take:20});
  const proofs=await db.auditLog.findMany({where:{action:'change.v11-formal-proposed',targetType:'V11CoreChange',targetId:{in:rows.map(r=>r.id)}}});
  if(rows.some(r=>!proofs.some(p=>p.targetId===r.id&&object(p.metadata).changeDigest===formalCoreChangeDigest(r))))reject(409,'CORE_CHANGE_FORMAL_PROVENANCE_REQUIRED');
  const choices=await db.v11ChangeChoice.findMany({where:{registrationId:reg.id,changeId:{in:rows.map(r=>r.id)}}});
  const member=await db.v11Membership.findUnique({where:{registrationId:reg.id},include:{table:true}}),showName=formalCoreChangeNameVisible(reg,member);
  const reviews=await db.v11Request.findMany({where:{registrationId:reg.id,kind:'CORE_CHANGE_REJECTION_REVIEW',source:'FORMAL_USER_INTAKE'},orderBy:{acceptedAt:'asc'}});
  return {changes:rows.map(r=>({id:r.id,original:formalCoreChangePublicSnapshot(r.originalSnapshot,showName),proposed:formalCoreChangePublicSnapshot(r.proposedSnapshot,showName),canAccept:reg.active&&(!object(r.originalSnapshot).restaurantId||object(r.originalSnapshot).restaurantId===object(r.proposedSnapshot).restaurantId||showName),restaurantChanged:object(r.originalSnapshot).restaurantId!==object(r.proposedSnapshot).restaurantId,acceptedAt:r.acceptedAt,changeDigest:formalCoreChangeDigest(r),choice:choices.find(c=>c.changeId===r.id)?.choice??null,responseAt:choices.find(c=>c.changeId===r.id)?.acceptedAt??null,applied:false,deadline:null,silenceAccepted:false,pendingReview:reviews.some(v=>object(v.payload).changeId===r.id),reviewRequestId:reviews.find(v=>object(v.payload).changeId===r.id)?.id??null,reviewAcceptedAt:reviews.find(v=>object(v.payload).changeId===r.id)?.acceptedAt??null,originalChangeAcceptedAt:r.acceptedAt}))};
 });
 app.get('/api/v11/ops/formal/core-changes',async req=>{const actor=await controlled.authenticate(req);requireRole(actor,'OPS','REVIEWER');const q=z.object({cursor:id.optional()}).strict().parse(req.query);const rows=await db.v11CoreChange.findMany({where:{kind:'FORMAL_CORE_CHANGE',...(q.cursor?{id:{gt:q.cursor}}:{})},orderBy:{id:'asc'},take:21});const choices=await db.v11ChangeChoice.findMany({where:{changeId:{in:rows.slice(0,20).map(r=>r.id)}}});const reviews=await db.v11Request.findMany({where:{kind:'CORE_CHANGE_REJECTION_REVIEW',source:'FORMAL_USER_INTAKE',OR:rows.slice(0,20).map(r=>({payload:{path:['changeId'],equals:r.id}}))},orderBy:{acceptedAt:'asc'}});const cases=await db.financialCase.findMany({where:{category:{in:['V11_FORMAL_CORE_CHANGE_RESPONSE','V11_CORE_CHANGE_REJECTION_REVIEW']},sourceRef:{in:[...choices.map(c=>c.id),...reviews.map(r=>r.id)]}}});return {changes:rows.slice(0,20).map(r=>({id:r.id,activityId:r.activityId,state:r.state,acceptedAt:r.acceptedAt,original:r.originalSnapshot,proposed:r.proposedSnapshot,applied:false,pendingReviews:reviews.filter(v=>object(v.payload).changeId===r.id).map(v=>({requestId:v.id,registrationId:v.registrationId,state:v.state,acceptedAt:v.acceptedAt,originalChangeAcceptedAt:object(v.payload).originalChangeAcceptedAt,caseOwner:cases.find(c=>c.sourceRef===v.id)?.owner??null,membershipEnded:false})),responses:choices.filter(c=>c.changeId===r.id).map(c=>({choiceId:c.id,registrationId:c.registrationId,choice:c.choice,acceptedAt:c.acceptedAt,caseOwner:cases.find(x=>x.sourceRef===c.id)?.owner??null}))})),nextCursor:rows.length>20?rows[19]!.id:null};});
}
