import { buildApp } from '../app.js';
import Fastify from 'fastify';
import {describe,it,expect,vi} from 'vitest';
import type {PrismaClient} from '../generated/prisma/client.js';
import {registerProductionIdentityRoutes} from './production-identity-routes.js';
import {registerAuth,signSession} from '../auth.js';
import {errorResponse} from './contracts.js';
const real={auth:{mode:'wechat'},phone:{mode:'wechat'}};
describe('formal identity route assembly gates',()=>{
 it.each(['yes','true'])('financial records reject malformed or identity-less activation: %s',flag=>{const app=Fastify();try{expect(()=>registerProductionIdentityRoutes(app,{} as PrismaClient,{FEATURE_V11_FINANCIAL_RECORDS:flag},real,false)).toThrow(flag==='yes'?'must be true or false':'require formal identity');expect(app.hasRoute({method:'GET',url:'/api/v11/registrations/:id/funds'})).toBe(false);}finally{void app.close();}});
 it('keeps formal identity absent in the existing application by default',async()=>{const app=await buildApp({prisma:{} as PrismaClient,providerEnv:{APP_ENV:'ci',NODE_ENV:'test',SESSION_SECRET:'synthetic-only-session-key-32-characters'}});try{expect((await app.inject({url:'/api/v11/identity'})).statusCode).toBe(404);}finally{await app.close();}});
 it('rejects enabling formal identity with mock providers in the existing application',async()=>{await expect(buildApp({prisma:{} as PrismaClient,providerEnv:{APP_ENV:'ci',NODE_ENV:'test',SESSION_SECRET:'synthetic-only-session-key-32-characters',FEATURE_V11_IDENTITY:'true'}})).rejects.toThrow('require real identity');});
 it.each([undefined,'false'])('keeps new identity routes absent with flag %s',async flag=>{const app=Fastify();try{registerProductionIdentityRoutes(app,{} as PrismaClient,{FEATURE_V11_IDENTITY:flag},real,false);expect((await app.inject({url:'/api/v11/identity'})).statusCode).toBe(404);expect((await app.inject({method:'POST',url:'/api/v11/identity/initialize',payload:{}})).statusCode).toBe(404);}finally{await app.close();}});
 it('rejects malformed flag at startup',async()=>{const app=Fastify();try{expect(()=>registerProductionIdentityRoutes(app,{} as PrismaClient,{FEATURE_V11_IDENTITY:'yes'},real,false)).toThrow('must be true or false');}finally{await app.close();}});
 it.each(['demo','auth-mock','phone-mock'])('refuses enabled %s assembly',async kind=>{const app=Fastify();try{expect(()=>registerProductionIdentityRoutes(app,{} as PrismaClient,{FEATURE_V11_IDENTITY:'true'},{auth:{mode:kind==='auth-mock'?'mock':'wechat'},phone:{mode:kind==='phone-mock'?'mock':'wechat'}},kind==='demo')).toThrow('require real identity');expect(app.hasRoute({method:'GET',url:'/api/v11/identity'})).toBe(false);}finally{await app.close();}});
 it('exposes only projected verified principal and rejects client onboarding grant fields',async()=>{const actor={id:'actor',role:'USER',personId:'person',version:1,userId:'user',restaurantId:null,enabled:true,passwordHash:'unused'};const db={user:{findUnique:vi.fn().mockResolvedValue({id:'user',status:'NORMAL'})},v11Actor:{findMany:vi.fn().mockResolvedValue([actor]),findUnique:vi.fn().mockResolvedValue(actor)},$transaction:vi.fn()};const app=Fastify();try{await registerAuth(app,db as unknown as PrismaClient,{APP_ENV:'test',SESSION_SECRET:'synthetic-only-session-key-32-characters'});registerProductionIdentityRoutes(app,db as unknown as PrismaClient,{FEATURE_V11_IDENTITY:'true'},real,false);app.setErrorHandler((e,_q,r)=>{if('issues'in e)return r.code(400).send({error:'INVALID_INPUT'});const x=errorResponse(e);r.code(x.statusCode).send(x.body);});const headers={authorization:'Bearer '+signSession(app,{sub:'user',role:'USER'})};const r=await app.inject({url:'/api/v11/identity',headers});expect(r.statusCode).toBe(200);expect(r.json()).toMatchObject({version:'v11-identity-1',principal:{userId:'user',role:'USER'}});expect(r.json().principal).not.toHaveProperty('passwordHash');expect((await app.inject({method:'POST',url:'/api/v11/identity/initialize',headers,payload:{role:'OPS'}})).statusCode).toBe(400);expect(db.$transaction).not.toHaveBeenCalled();expect((await app.inject({url:'/api/v11/ops/identity',headers})).statusCode).toBe(401);}finally{await app.close();}});
});
