import { assertVisibleCopyAllowed } from '@timeleft-shanghai/shared';
import Fastify, { type FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import { createSimulationIdentity } from './principal.js';
import { z } from 'zod';
import type { PrismaClient } from '../generated/prisma/client.js';
import { API_VERSION, parse, reject, errorResponse, requireRole, profileInput, identifier, businessKey, pageQuery, cents, simulationNextDay } from './contracts.js';
import { verifyOwnedDatabase } from './ownership.js';
import { publicPolicy, importFrozenPolicy } from './policy.js';
import { matchesConsentDocuments } from './consent-evidence.js';
import { activityLock, audit, createRegistration, startPayment, acceptCancellation, registrationDetail, requestRecord, publicRequest, persistMockEvent, assertSimulationPolicy, dbNow, json, object, sha256 } from './domain.js';
import { PersistentMockChannel } from '../funding/mock-channel.js';
import { enqueue } from '../jobs/queue.js';
import { fundingBuckets, claimFinancialCase, resolveFinancialCase } from './finance.js';
import { reconcileMockChannel } from './reconciliation.js';
import { aftersalesRoute } from './aftersales.js';
import { matchesTimePreference, summarizeTimePreferences } from './time-preferences.js';
const empty = z.object({}).strict();
const loginSchema = z.object({ actorId: identifier, password: z.string().min(1).max(200) }).strict();
const regSchema = z.object({ activityId: identifier, supplyId: identifier, policyId: identifier, consentId: identifier, membership: z.enum(['FORMAL','WAITLIST']), businessKey }).strict();
const text = z.string().min(1).max(200);
function safeCopy(value: string) { try { assertVisibleCopyAllowed(value); } catch { reject(400,'COPY_FORBIDDEN'); } return value; }
export async function buildPrelaunchApp(db: PrismaClient, env: Record<string,string|undefined>, root: string, channelDb: PrismaClient) {
 await verifyOwnedDatabase(db,env);
 if(!env.PRELAUNCH_CHANNEL_DATABASE_NAME||!env.PRELAUNCH_CHANNEL_DATABASE_URL)reject(503,'OWNED_CHANNEL_DATABASE_REQUIRED');
 await verifyOwnedDatabase(channelDb,{...env,PRELAUNCH_DATABASE_NAME:env.PRELAUNCH_CHANNEL_DATABASE_NAME});
 const channel=new PersistentMockChannel(channelDb);
 const app=Fastify({ logger:false, bodyLimit:64*1024 });
 const identity=createSimulationIdentity(env.PRELAUNCH_SESSION_SECRET!, id=>db.v11Actor.findUnique({where:{id}}));
 const origins=(env.PRELAUNCH_CORS_ORIGINS??'').split(',').filter(Boolean);
 if(origins.some(o=>!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(o))) reject(503,'INVALID_LOCAL_CORS_ORIGIN');
 await app.register(cors,{ origin:origins, methods:['GET','POST','PUT','DELETE'],allowedHeaders:['Content-Type','Authorization','x-fanju-contract'],credentials:false });
 const attempts=new Map<string,{count:number,until:number}>();
 app.addHook('onRequest',async(req,reply)=>{const mutation=['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.url.split('?')[0]!.startsWith('/api/prelaunch/v11/'); if(req.method!=='OPTIONS'&&(mutation||req.headers['x-fanju-contract']!==undefined)&&req.headers['x-fanju-contract']!==API_VERSION)reject(409,'INCOMPATIBLE_VERSION'); const now=Date.now();const k=req.ip;const a=attempts.get(k); if(a&&a.until>now&&a.count>=300) return reply.code(429).send({version:API_VERSION,error:{code:'RATE_LIMITED',blockerIds:[]}}); attempts.set(k,{count:a&&a.until>now?a.count+1:1,until:a&&a.until>now?a.until:now+60_000}); if(attempts.size>2048) for(const [key,value]of attempts)if(value.until<=now)attempts.delete(key); });
 app.setErrorHandler((error,_req,reply)=>{const e=errorResponse(error);reply.code(e.statusCode).send(e.body);});
 const paging=(req:FastifyRequest)=>{const q=parse(pageQuery,req.query);return{take:q.limit+1,orderBy:{id:"asc" as const},...(q.cursor?{cursor:{id:q.cursor},skip:1}:{})};};
 const paged=(rows: {id:string}[], req:FastifyRequest)=>{const q=parse(pageQuery,req.query);return{rows:rows.slice(0,q.limit),nextCursor:rows.length>q.limit?rows[q.limit-1]!.id:null};};
 const result=(value:unknown)=>({version:API_VERSION,...object(value)});
 const principal=(req:FastifyRequest)=>identity.authenticate(req.headers.authorization);
 const base='/api/prelaunch/v11';
 app.get('/health/live',async()=>({status:'live',scope:'SIMULATION_ONLY'}));
 app.get('/health/ready',async(_q,r)=>{try{await verifyOwnedDatabase(db,env);return{status:'ready',scope:'SIMULATION_ONLY'};}catch{return r.code(503).send({status:'not_ready'});}});
 app.post(base+'/auth/login',async(req)=>{const v=parse(loginSchema,req.body);return result(await identity.login(v.actorId,v.password));});
 app.get(base+'/policy/current',async(req)=>{const q=parse(z.object({scope:z.enum(['FROZEN_DRAFT','SIMULATION_ONLY']).default('FROZEN_DRAFT')}).strict(),req.query);const frozen=await importFrozenPolicy(db,root);if(q.scope==='FROZEN_DRAFT')return result(publicPolicy(frozen));const row=await db.v11PolicySnapshot.findUnique({where:{bundleDigest:sha256('SIMULATION_ONLY:'+frozen.bundleDigest)}});if(!row)reject(404,'SIMULATION_POLICY_NOT_CREATED');assertSimulationPolicy(row);return result(publicPolicy(row));});
 app.post(base+'/ops/simulation-policy',async(req)=>{const actor=await principal(req);requireRole(actor,'OPS');const v=parse(z.object({sourcePolicyId:identifier}).strict(),req.body);const source=await db.v11PolicySnapshot.findUniqueOrThrow({where:{id:v.sourcePolicyId}});if(object(source.docsJson).scope!=='FROZEN_DRAFT')reject(409,'SOURCE_POLICY_REQUIRED');const docs={...object(source.docsJson),scope:'TEST_ONLY'};const digest=sha256('SIMULATION_ONLY:'+source.bundleDigest);const row=await db.v11PolicySnapshot.upsert({where:{bundleDigest:digest},update:{},create:{bundleDigest:digest,bundleVersion:'SIMULATION_ONLY:'+source.bundleVersion,baselineHash:source.baselineHash,status:'LOCAL_DRAFT',docsJson:json(docs),blockersJson:source.blockersJson as never}});return result(publicPolicy(row));});
 app.put(base+'/profile',async(req)=>{const actor=await principal(req);requireRole(actor,'USER');if(!actor.userId)reject(403,'USER_ID_REQUIRED');const v=parse(profileInput,req.body);const row=await db.v11Profile.upsert({where:{userId:actor.userId},create:{userId:actor.userId,gender:v.gender,adultConfirmed:true,adaptationConfirmed:true,availableTimes:v.timePreferences},update:{gender:v.gender,adultConfirmed:true,adaptationConfirmed:true,availableTimes:v.timePreferences,version:{increment:1}}});return result({profile:{gender:row.gender,adultConfirmed:row.adultConfirmed,version:row.version}});});
 app.post(base+'/consents',async(req)=>{
   const actor=await principal(req);requireRole(actor,'USER');if(!actor.userId)reject(403,'USER_ID_REQUIRED');
   const v=parse(z.object({policyId:identifier,documentHashes:z.record(z.string(),z.string()),publicHashes:z.record(z.string(),z.string()),confirm:z.literal(true)}).strict(),req.body);
   const consent=await db.$transaction(async tx=>{
     await tx.$queryRaw`SELECT id FROM "V11PolicySnapshot" WHERE id=${v.policyId} FOR UPDATE`;
     const row=await tx.v11PolicySnapshot.findUniqueOrThrow({where:{id:v.policyId}});
     const policy=publicPolicy(row);
     if(row.status!=='LOCAL_DRAFT'||!['FROZEN_DRAFT','TEST_ONLY'].includes(String(policy.scope)))reject(409,'POLICY_INTEGRITY_INVALID');
     if(!matchesConsentDocuments(policy.documents,v.documentHashes,v.publicHashes))reject(409,'POLICY_HASH_MISMATCH');
     return tx.v11BundleConsent.create({data:{userId:actor.userId!,policyId:row.id,documentHashesJson:json(v.documentHashes),publicHashesJson:json(v.publicHashes),acceptedAt:await dbNow(tx),source:'SIMULATION_ONLY'}});
   });return result({consentId:consent.id});
 });
 app.get(base+'/ops/time-demand',async(req)=>{const actor=await principal(req);requireRole(actor,'OPS','REVIEWER');const actors=await db.v11Actor.findMany({where:{enabled:true,role:'USER',userId:{not:null}},select:{userId:true}});const profiles=await db.v11Profile.findMany({where:{userId:{in:actors.flatMap(a=>a.userId?[a.userId]:[])}},select:{availableTimes:true}});return result({demand:summarizeTimePreferences(profiles)});});
 app.get(base+'/activities',async(req)=>{const actor=req.headers.authorization?await principal(req):null;const profile=actor?.role==='USER'&&actor.userId?await db.v11Profile.findUnique({where:{userId:actor.userId},select:{availableTimes:true}}):null;const rows=await db.activity.findMany({where:{status:{in:['PUBLISHED','REGISTRATION_OPEN']},v11SupplyRevision_activityId:{some:{status:'SIMULATION_APPROVED'}}},...paging(req)});const page=paged(rows,req);const activities=[];for(const row of page.rows as typeof rows){const supply=await db.v11SupplyRevision.findFirst({where:{activityId:row.id,status:'SIMULATION_APPROVED'},orderBy:{revision:'desc'}});if(supply)activities.push({id:row.id,title:row.title,startsAt:row.startsAt,preferenceMatched:matchesTimePreference(row.startsAt,profile?.availableTimes??[]),supplyId:supply.id,policyId:supply.policyId,F:supply.serviceFeeCents,D:supply.depositCents,capacity:supply.capacity,waitlistMax:supply.waitlistMax,estimatedMealMinCents:object(supply.snapshot).estimatedMealMinCents,estimatedMealMaxCents:object(supply.snapshot).estimatedMealMaxCents,fixedFees:object(supply.snapshot).fixedFees});}return result({activities,nextCursor:page.nextCursor});});
 app.post(base+'/registrations',async(req,reply)=>{const actor=await principal(req);const row=await createRegistration(db,actor,parse(regSchema,req.body));if('eligibilityState'in row)return result(await registrationDetail(db,actor,row.id));reply.code(202);return result({request:publicRequest(row),state:'BLOCKED_POLICY',blockerIds:row.blockerIds});});
 app.get(base+'/registrations',async(req)=>{const actor=await principal(req);requireRole(actor,'USER');const q=parse(pageQuery,req.query);const rows=await db.v11Registration.findMany({where:{userId:actor.userId!},orderBy:{id:'asc'},take:q.limit+1,...(q.cursor?{cursor:{id:q.cursor},skip:1}:{})});const selected=rows.slice(0,q.limit);return result({registrations:await Promise.all(selected.map(row=>registrationDetail(db,actor,row.id))),nextCursor:rows.length>q.limit?selected.at(-1)!.id:null});});
 app.get(base+'/registrations/:id',async req=>result({registration:await registrationDetail(db,await principal(req),parse(z.object({id:identifier}).strict(),req.params).id)}));
 app.post(base+'/registrations/:id/pay',async(req,reply)=>{parse(empty,req.body);const id=parse(z.object({id:identifier}).strict(),req.params).id;const intent=await startPayment(db,await principal(req),id);reply.code(202);return result({payment:{id:intent.id,state:intent.state}});});
 app.post(base+'/registrations/:id/cancel',async(req,reply)=>{const id=parse(z.object({id:identifier}).strict(),req.params).id;const v=parse(z.object({businessKey}).strict(),req.body);const row=await acceptCancellation(db,await principal(req),id,v.businessKey);
 const intents=await db.v11PaymentIntent.findMany({where:{registrationId:id,active:true}});
 const reg=await db.v11Registration.findUniqueOrThrow({where:{id}});
 if(!reg.active)for(const intent of intents){channel.assertBinding(intent);const fact=await channel.query('PAYMENT',intent.merchantOrderNo)??await channel.closePayment(intent.merchantOrderNo,intent.totalCents);if(fact.status==='SUCCEEDED')await persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});}
 reply.code(202);return result({request:publicRequest(row)});});
 app.get(base+'/requests',async(req)=>{const a=await principal(req);requireRole(a,'USER');const q=parse(pageQuery,req.query);const rows=await db.v11Request.findMany({where:{userId:a.userId!},...paging(req)});const page=paged(rows,req);return result({requests:(page.rows as typeof rows).map(r=>({...publicRequest(r),allowedActions:r.kind==='DISPUTE'?(object(r.payload).firstReviewerPersonId?object(r.payload).finalReviewUsed?[]:['REVIEW']:['EXPLANATION']):[]})),nextCursor:page.nextCursor});});
 app.get(base+'/notices',async(req)=>{const a=await principal(req);requireRole(a,'USER');const rows=await db.v11DeliveryProof.findMany({where:{registration:{userId:a.userId!}},...paging(req)});const page=paged(rows,req);return result({nextCursor:page.nextCursor,notices:(page.rows as typeof rows).map(r=>({id:r.id,kind:r.kind,state:r.state,receivedAt:r.receivedAt}))});});
 app.post(base+'/ops/restaurants',async(req)=>{const a=await principal(req);requireRole(a,'OPS');const v=parse(z.object({name:text,district:text,businessArea:text,address:text,capacity:cents.positive(),budgetCents:cents}).strict(),req.body);const row=await db.$transaction(async tx=>{const row=await tx.restaurant.create({data:{...v,name:safeCopy(v.name),contactName:'SIMULATION_ONLY',contactPhone:'synthetic-local',cuisineTags:[]}});await audit(tx,'restaurant.create','Restaurant',row.id,a);return row;});return result({id:row.id});});
 app.post(base+'/ops/activities',async(req)=>{const a=await principal(req);requireRole(a,'OPS');const v=parse(z.object({restaurantId:identifier,title:text,startsAt:z.iso.datetime(),endsAt:z.iso.datetime(),registrationEndsAt:z.iso.datetime()}).strict(),req.body);const restaurant=await db.restaurant.findUniqueOrThrow({where:{id:v.restaurantId}});if(new Date(v.endsAt)<=new Date(v.startsAt)||new Date(v.registrationEndsAt)>=new Date(v.startsAt))reject(400,'INVALID_INPUT');const row=await db.activity.create({data:{restaurantId:restaurant.id,title:safeCopy(v.title),theme:'SIMULATION_ONLY',description:'合成本地测试',district:restaurant.district,businessArea:restaurant.businessArea,startsAt:new Date(v.startsAt),endsAt:new Date(v.endsAt),registrationEndsAt:new Date(v.registrationEndsAt),serviceFeeCents:0,mealFeePolicyText:'餐费到店自理',capacity:restaurant.capacity}});return result({id:row.id});});
 app.post(base+'/ops/actors/:id/restaurant',async(req)=>{const a=await principal(req);requireRole(a,'OPS');const id=parse(z.object({id:identifier}).strict(),req.params).id;const v=parse(z.object({restaurantId:identifier}).strict(),req.body);return result(await db.$transaction(async tx=>{const actor=await tx.v11Actor.findUniqueOrThrow({where:{id}});if(actor.role!=='RESTAURANT'||actor.restaurantId!==null||actor.personId===a.personId)reject(409,'ACTOR_SCOPE_BINDING_REJECTED');await tx.restaurant.findUniqueOrThrow({where:{id:v.restaurantId}});const changed=await tx.v11Actor.updateMany({where:{id,version:actor.version,restaurantId:null,role:'RESTAURANT'},data:{restaurantId:v.restaurantId,version:{increment:1}}});if(changed.count!==1)reject(409,'ACTOR_SCOPE_BINDING_CONFLICT');await audit(tx,'actor.restaurant-bound','V11Actor',id,a);return {id,restaurantId:v.restaurantId,reloginRequired:true};}));});
 const supplySchema=z.object({activityId:identifier,policyId:identifier,min:z.number().int().min(4).max(8),target:z.number().int().min(4).max(8),max:z.number().int().min(4).max(8),maxTables:z.number().int().min(1).max(100),capacity:z.number().int().min(1),F:cents,D:cents,WAITLIST_MAX:z.number().int().min(0).max(1000).nullable(),strategy:z.enum(['FILL_TO_TARGET','FILL_TO_MAX']),estimatedMealMinCents:cents,estimatedMealMaxCents:cents,fixedFees:z.array(z.object({label:text,amountCents:cents}).strict()).max(20)}).strict();
 app.post(base+'/ops/supplies',async(req)=>{const a=await principal(req);requireRole(a,'OPS');const v=parse(supplySchema,req.body);if(v.min>v.target||v.target>v.max||v.capacity<v.min||v.capacity>v.max*v.maxTables||v.estimatedMealMinCents>v.estimatedMealMaxCents||v.F+v.D>2147483647||v.F+v.D<=0)reject(400,'SUPPLY_INVALID');const row=await db.$transaction(async tx=>{await activityLock(tx,v.activityId);const activity=await tx.activity.findUniqueOrThrow({where:{id:v.activityId},include:{restaurant:true}});const policy=await tx.v11PolicySnapshot.findUniqueOrThrow({where:{id:v.policyId}});assertSimulationPolicy(policy);if(v.capacity>activity.restaurant.capacity)reject(409,'CAPACITY_EXCEEDED');if(await tx.v11Registration.count({where:{activityId:v.activityId}}))reject(409,'CORE_CHANGE_REQUIRED');const prior=await tx.v11SupplyRevision.aggregate({where:{activityId:v.activityId},_max:{revision:true}});return tx.v11SupplyRevision.create({data:{activityId:v.activityId,restaurantId:activity.restaurantId,policyId:v.policyId,revision:(prior._max.revision??0)+1,minSize:v.min,targetSize:v.target,maxSize:v.max,maxTables:v.maxTables,capacity:v.capacity,serviceFeeCents:v.F,depositCents:v.D,waitlistMax:v.WAITLIST_MAX,strategy:v.strategy,snapshot:json({...v,scope:'TEST_ONLY'}),digest:sha256(JSON.stringify(v))}});});return result({id:row.id});});
 app.get(base+'/waitlist',async(req)=>{const actor=await principal(req);requireRole(actor,'USER');if(!actor.userId)reject(403,'USER_ID_REQUIRED');const q=parse(z.object({activityId:identifier}).strict(),req.query);const own=await db.v11Registration.findFirst({where:{userId:actor.userId,activityId:q.activityId,active:true,eligibilityState:'WAITLIST'}});if(!own)reject(404,'RESOURCE_NOT_FOUND');const ahead=own.queueOrdinal===null?null:await db.v11Registration.count({where:{activityId:q.activityId,active:true,eligibilityState:'WAITLIST',queueOrdinal:{lt:own.queueOrdinal}}});const total=await db.v11Registration.count({where:{activityId:q.activityId,active:true,eligibilityState:'WAITLIST'}});return result({queue:{registrationId:own.id,ordinal:own.queueOrdinal?.toString()??null,position:ahead===null?null:ahead+1,total,rankingClock:'TEST_ONLY_TRANSACTION_ORDINAL',officialClockBlockers:['OP-05'],scope:'SIMULATION_ONLY'}});});
 app.get(base+'/ops/activities/:id/waitlist',async(req)=>{const actor=await principal(req);requireRole(actor,'OPS','REVIEWER');const id=parse(z.object({id:identifier}).strict(),req.params).id;const q=parse(pageQuery,req.query);const rows=await db.v11Registration.findMany({where:{activityId:id,eligibilityState:'WAITLIST',active:true},orderBy:[{queueOrdinal:'asc'},{id:'asc'}],take:q.limit+1,...(q.cursor?{cursor:{id:q.cursor},skip:1}:{})});const selected=rows.slice(0,q.limit);return result({queue:selected.map(r=>({id:r.id,ordinal:r.queueOrdinal?.toString()??null,state:r.eligibilityState})),nextCursor:rows.length>q.limit?selected.at(-1)!.id:null,rankingClock:'TEST_ONLY_TRANSACTION_ORDINAL',officialClockBlockers:['OP-05']});});
 for(const prefix of ['ops','restaurant']as const){
  app.get(base+`/${prefix}/supplies/:id`,async(req)=>{const actor=await principal(req);requireRole(actor,...(prefix==='ops'?['OPS','REVIEWER']as const:['RESTAURANT']as const));const id=parse(z.object({id:identifier}).strict(),req.params).id;const row=await db.v11SupplyRevision.findUnique({where:{id}});if(!row||(prefix==='restaurant'&&row.restaurantId!==actor.restaurantId))reject(404,'RESOURCE_NOT_FOUND');return result({supply:row,scope:'SIMULATION_ONLY',immutableRevision:true});});
  app.get(base+`/${prefix}/supplies/:id/history`,async(req)=>{const actor=await principal(req);requireRole(actor,...(prefix==='ops'?['OPS','REVIEWER']as const:['RESTAURANT']as const));const id=parse(z.object({id:identifier}).strict(),req.params).id;const row=await db.v11SupplyRevision.findUnique({where:{id}});if(!row||(prefix==='restaurant'&&row.restaurantId!==actor.restaurantId))reject(404,'RESOURCE_NOT_FOUND');const rows=await db.v11SupplyRevision.findMany({where:{activityId:row.activityId},...paging(req)});const page=paged(rows,req);return result({history:page.rows,nextCursor:page.nextCursor,scope:'SIMULATION_ONLY'});});
 }
 app.post(base+'/ops/supplies/:id/revision',async(req)=>{const actor=await principal(req);requireRole(actor,'OPS');const id=parse(z.object({id:identifier}).strict(),req.params).id;const change=parse(supplySchema.omit({activityId:true,policyId:true}),req.body);if(change.min>change.target||change.target>change.max||change.capacity<change.min||change.capacity>change.max*change.maxTables||change.estimatedMealMinCents>change.estimatedMealMaxCents||change.F+change.D>2147483647||change.F+change.D<=0)reject(400,'SUPPLY_INVALID');const row=await db.$transaction(async tx=>{const previous=await tx.v11SupplyRevision.findUniqueOrThrow({where:{id}});await activityLock(tx,previous.activityId);const activity=await tx.activity.findUniqueOrThrow({where:{id:previous.activityId},include:{restaurant:true}});if(change.capacity>activity.restaurant.capacity)reject(409,'CAPACITY_EXCEEDED');const revision=await tx.v11SupplyRevision.aggregate({where:{activityId:previous.activityId},_max:{revision:true}});const snapshot={...change,activityId:previous.activityId,policyId:previous.policyId,parentRevisionId:id,scope:'TEST_ONLY'};const next=await tx.v11SupplyRevision.create({data:{activityId:previous.activityId,restaurantId:previous.restaurantId,policyId:previous.policyId,revision:(revision._max.revision??0)+1,minSize:change.min,targetSize:change.target,maxSize:change.max,maxTables:change.maxTables,capacity:change.capacity,serviceFeeCents:change.F,depositCents:change.D,waitlistMax:change.WAITLIST_MAX,strategy:change.strategy,snapshot:json(snapshot),digest:sha256(JSON.stringify(snapshot))}});await audit(tx,'supply.revision-created','V11SupplyRevision',next.id,actor);return next;});return result({supply:row,oldRevisionId:id,existingOrdersChanged:false,requiresRestaurantConfirmation:true,requiresCoreChangeApproval:true});});
 app.post(base+'/restaurant/supplies/:id/confirm',async(req)=>{parse(empty,req.body);const a=await principal(req);requireRole(a,'RESTAURANT');const id=parse(z.object({id:identifier}).strict(),req.params).id;const row=await db.v11SupplyRevision.findUniqueOrThrow({where:{id}});if(a.restaurantId!==row.restaurantId)reject(404,'RESOURCE_NOT_FOUND');const updated=await db.v11SupplyRevision.updateMany({where:{id,status:'DRAFT'},data:{personId:a.personId,signedAt:new Date(),status:'SIMULATION_SIGNED'}});if(!updated.count&&row.status!=='SIMULATION_SIGNED')reject(409,'SUPPLY_STATE_CONFLICT');return result({id,status:'SIMULATION_SIGNED'});});
 app.post(base+'/ops/supplies/:id/approve',async(req)=>{const a=await principal(req);requireRole(a,'OPS');const id=parse(z.object({id:identifier}).strict(),req.params).id;const v=parse(z.object({D_MIN:cents,D_MAX:cents,simulationBatchHour:z.number().int().min(0).max(23)}).strict(),req.body);const row=await db.v11SupplyRevision.findUniqueOrThrow({where:{id},include:{policy:true}});assertSimulationPolicy(row.policy);if(await db.v11Registration.count({where:{activityId:row.activityId,supplyId:{not:id}}}))reject(409,'CORE_CHANGE_APPROVAL_REQUIRED',['OP-09']);if(row.status!=='SIMULATION_SIGNED'||!row.personId||row.personId===a.personId||v.D_MIN>v.D_MAX||row.depositCents<v.D_MIN||row.depositCents>v.D_MAX)reject(409,'SUPPLY_APPROVAL_REQUIRED');await db.v11SupplyRevision.update({where:{id},data:{status:'SIMULATION_APPROVED',snapshot:json({...object(row.snapshot),approval:{...v,scope:'TEST_ONLY',actorId:a.id}})}});return result({id,status:'SIMULATION_APPROVED'});});
 app.post(base+'/ops/activities/:id/publish',async(req)=>{parse(empty,req.body);const a=await principal(req);requireRole(a,'OPS');const id=parse(z.object({id:identifier}).strict(),req.params).id;await db.$transaction(async tx=>{await activityLock(tx,id);const row=await tx.activity.findUniqueOrThrow({where:{id}});const supply=await tx.v11SupplyRevision.findFirst({where:{activityId:id,status:'SIMULATION_APPROVED'},orderBy:{revision:'desc'},include:{policy:true}});if(!supply)reject(409,'SUPPLY_NOT_APPROVED');assertSimulationPolicy(supply.policy);if(!['DRAFT','PUBLISHED'].includes(row.status))reject(409,'ACTIVITY_STATE_CONFLICT');await tx.activity.update({where:{id},data:{status:'PUBLISHED'}});await enqueue(tx,'V11_T24',`v11:t24:${id}`,id,new Date(row.startsAt.getTime()-24*3600_000));await enqueue(tx,'V11_T8',`v11:t8:${id}`,id,new Date(row.startsAt.getTime()-8*3600_000));await enqueue(tx,'V11_FULFILLMENT_CHECK',`v11:fulfillment:${id}`,id,simulationNextDay(row.endsAt,10));await audit(tx,'activity.publish','Activity',id,a);});return result({id,status:'PUBLISHED'});});
 for(const prefix of ['ops','restaurant'] as const){
 app.get(base+`/${prefix}/supplies`,async(req)=>{const a=await principal(req);requireRole(a,...(prefix==='ops'?['OPS','REVIEWER'] as const:['RESTAURANT'] as const));const rows=await db.v11SupplyRevision.findMany({where:prefix==='restaurant'?{restaurantId:a.restaurantId!}:{},...paging(req)});const page=paged(rows,req);return result({nextCursor:page.nextCursor,supplies:(page.rows as typeof rows).map(r=>({id:r.id,activityId:r.activityId,status:r.status,F:r.serviceFeeCents,D:r.depositCents,snapshot:r.snapshot}))});});
 app.get(base+`/${prefix}/registrations`,async(req)=>{const a=await principal(req);requireRole(a,...(prefix==='ops'?['OPS','REVIEWER'] as const:['RESTAURANT'] as const));const rows=await db.v11Registration.findMany({where:prefix==='restaurant'?{activity:{restaurantId:a.restaurantId!}}:{},...paging(req)});const page=paged(rows,req);return result({nextCursor:page.nextCursor,registrations:(page.rows as typeof rows).map(r=>({id:r.id,activityId:r.activityId,state:r.eligibilityState,F:r.serviceFeeCents,D:r.depositCents}))});}); }
 app.get(base+'/ops/requests',async(req)=>{const a=await principal(req);requireRole(a,'OPS','REVIEWER');const rows=await db.v11Request.findMany(paging(req));const page=paged(rows,req);return result({nextCursor:page.nextCursor,requests:(page.rows as typeof rows).map(r=>({...publicRequest(r),allowedActions:r.kind==='SPECIAL_REFUND'&&r.state==='SIMULATION_REVIEW_PENDING'?['REFUND_D','REFUND_FD','REJECT']:r.kind==='DISPUTE'&&(!object(r.payload).firstReviewerPersonId||r.state==='FINAL_REVIEW_PENDING')?(r.state==='FINAL_REVIEW_PENDING'&&object(r.payload).firstReviewerPersonId===a.personId?[]:['REFUND_D','BREACH']):[]}))});});
 app.get(base+'/ops/jobs',async(req)=>{requireRole(await principal(req),'OPS','REVIEWER');const rows=await db.durableJob.findMany({where:{kind:{startsWith:'V11_'}},...paging(req)});const page=paged(rows,req);return result({nextCursor:page.nextCursor,jobs:(page.rows as typeof rows).map(r=>({id:r.id,kind:r.kind,state:r.state,attempts:r.attempts}))});});
 app.get(base+'/ops/financial-cases',async(req)=>{const actor=await principal(req);requireRole(actor,'OPS','REVIEWER');const rows=await db.financialCase.findMany(paging(req));const page=paged(rows,req);return result({nextCursor:page.nextCursor,cases:(page.rows as typeof rows).map(r=>({id:r.id,kind:r.category,state:r.state,owner:r.owner,deadline:r.deadline,reviewedAt:r.reviewedAt,allowedActions:actor.role==='OPS'&&r.state!=='RESOLVED'?(r.owner===actor.id?['RESOLVE']:['local-simulation-ops','local-review-required'].includes(r.owner)?['CLAIM']:[]):[]}))});});
 app.post(base+'/ops/financial-cases/:id/claim',async(req)=>{parse(empty,req.body);const actor=await principal(req);const id=parse(z.object({id:identifier}).strict(),req.params).id;return result(await claimFinancialCase(db,actor,id));});
 app.post(base+'/ops/financial-cases/:id/resolve',async(req)=>{const actor=await principal(req);const id=parse(z.object({id:identifier}).strict(),req.params).id;const body=parse(z.object({reason:z.string().trim().min(1).max(500)}).strict(),req.body);return result(await resolveFinancialCase(db,channelDb,actor,id,body.reason));});
 app.post(base+'/ops/reconciliation',async(req)=>{parse(empty,req.body);const actor=await principal(req);requireRole(actor,'OPS');return result(await reconcileMockChannel(db,channelDb,actor));});
 app.get(base+'/ops/funding-summary',async(req)=>{requireRole(await principal(req),'OPS','REVIEWER');return result(await fundingBuckets(db));});
 app.get(base+'/ops/summary',async(req)=>{requireRole(await principal(req),'OPS','REVIEWER');const [registrations,requests,jobs,receipts]=await Promise.all([db.v11Registration.count(),db.v11Request.count(),db.durableJob.count({where:{kind:{startsWith:'V11_'}}}),db.v11ReceiptBinding.count()]);return result({summary:{registrations,requests,jobs,receipts,funding:await fundingBuckets(db),scope:'SIMULATION_ONLY'}});});
 app.post(base+'/ops/registrations/:id/query',async(req)=>{parse(empty,req.body);const actor=await principal(req);requireRole(actor,'OPS');const id=parse(z.object({id:identifier}).strict(),req.params).id;await db.v11Registration.findUniqueOrThrow({where:{id}});let recovered=0;for(const intent of await db.v11PaymentIntent.findMany({where:{registrationId:id}})){channel.assertBinding(intent);const fact=await channel.query('PAYMENT',intent.merchantOrderNo);if(fact?.status==='SUCCEEDED'){await persistMockEvent(db,{kind:'PAYMENT',sourceId:intent.id,channelNo:fact.channelNo,amountCents:fact.amountCents});recovered++;}}for(const instruction of await db.v11RefundInstruction.findMany({where:{registrationId:id}})){channel.assertBinding(instruction);const fact=await channel.query('REFUND',instruction.merchantRefundNo);if(fact?.status==='SUCCEEDED'){await persistMockEvent(db,{kind:'REFUND',sourceId:instruction.id,channelNo:fact.channelNo,amountCents:fact.amountCents,originalTradeNo:instruction.originalTradeNo});recovered++;}}await db.$transaction(tx=>audit(tx,'registration.queried','V11Registration',id,actor));return result({registrationId:id,recoveredFacts:recovered,newMoneySubmitted:false});});
 const dispatch:[string,'GET'|'POST',string][]=[['/registrations/:id/special-refund','POST','specialRefund'],['/rights','GET','listRights'],['/rights/:id','GET','getRight'],['/rights','POST','createRight'],['/changes','GET','listChanges'],['/changes/:id/respond','POST','respondChange'],['/registrations/:id/checkin','POST','checkin'],['/requests/:id/explanation','POST','explanation'],['/requests/:id/review','POST','review'],['/notices/:id/receive','POST','receiveNotice'],['/ops/rights','GET','listRights'],['/ops/rights/:id/process','POST','processRight'],['/ops/changes','GET','listChanges'],['/ops/changes','POST','createChange'],['/ops/activities','GET','listOpsActivities'],['/ops/activities/:id/cancel','POST','cancelActivity'],['/ops/activities/:id/close','POST','closeActivity'],['/ops/requests/:id/decision','POST','decision'],['/restaurant/activities','GET','listRestaurantActivities'],['/restaurant/activities/:id/checkin-code','POST','checkinCode'],['/restaurant/registrations/:id/fulfillment','POST','fulfillment']];
 for(const [path,method,action]of dispatch)app.route({method,url:base+path,handler:async(req,reply)=>{const actor=await principal(req);if(path.startsWith('/ops/'))requireRole(actor,'OPS','REVIEWER');if(path.startsWith('/restaurant/'))requireRole(actor,'RESTAURANT');const params=parse(z.object({id:identifier.optional()}).strict(),req.params);const body=['checkin','fulfillment'].includes(action)?{...object(req.body),registrationId:params.id}:req.body;const value=await aftersalesRoute(db,actor,action,{...params,body,query:req.query});if(method==='POST')reply.code(202);return result(value);}});
 return app;
}
